#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""migrate_to_vault.py — Format-normalize comprehensive notes for the vault.

Companion to ``triage_stubs.py``. Takes the ``already-comprehensive/`` bucket
(notes that are already fully written but use the v3 pipeline format) and
rewrites them to match the canonical vault format used in
``999-report-organizing/_permanent-notes/llm-generated-permanent-notes/``.

What this script does:

1.  **Renames files** to aggressive kebab-case, ASCII-only:
        "4CID Blueprint Completeness Checklist.md"
            -> "4cid-blueprint-completeness-checklist.md"

2.  **Normalizes frontmatter**:
        - Ensures required fields: title, aliases, type, status, tags,
          domain, created, updated, provenance.
        - Adds machine-generated aliases (slug + spaced-title form).
        - Converts inline-list tags/aliases/subdomains to YAML block lists
          (matches vault style).
        - Preserves all source-provided fields it does not need to touch.

3.  **Cleans the body**:
        - Dedupes the `**Related:**` wiki-link line, keeping the top-N most
          frequent links (default 25). Some 4CID-era files repeat the same
          link 20+ times — this preserves the implicit "centrality" signal
          while making the line readable.

4.  **Detects collisions** against the canonical vault folder. If a
    normalized filename already exists in the target, the file is skipped
    and logged for manual review.

5.  **Writes** to a staging dir for human review BEFORE moving into the
    vault. Default staging dir is ``<triage-output>/_vault-ready/``.

Usage::

    python migrate_to_vault.py --dry-run
    python migrate_to_vault.py
    python migrate_to_vault.py --source-dir D:/some/other/dir
    python migrate_to_vault.py --top-related 50

Exit codes:

    0   success
    1   uncaught error
    2   bad arguments / missing input
    4   no source files found
    130 interrupted (SIGINT)

Version:
    1.0.0

Python:
    >=3.10

Dependencies:
    - stdlib: argparse, csv, dataclasses, logging, pathlib, re, sys
    - third-party: PyYAML (>=5.0)

Author:
    Generated by Python Script Designer & Generator -- Expert v1.0.0
"""
from __future__ import annotations

# -- Standard library --------------------------------------------------------
import argparse
import csv
import logging
import re
import sys
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

# -- Third-party -------------------------------------------------------------
import yaml


# ============================================================================
# Constants
# ============================================================================

__version__ = "1.0.0"

#: Default source: the already-comprehensive bucket from triage_stubs.
DEFAULT_SOURCE_DIR: Path = Path(
    "D:/00-inbox/v3-pipeline-permanet-note-leftovers/_triage-output/already-comprehensive"
)

#: Default staging output. User reviews here BEFORE moving into the vault.
DEFAULT_STAGING_DIR: Path = Path(
    "D:/00-inbox/v3-pipeline-permanet-note-leftovers/_triage-output/_vault-ready"
)

#: Canonical vault folder. Used only for collision detection -- never written.
DEFAULT_VAULT_DIR: Path = Path(
    "D:/10_pur3v4d3r's-vault/999-report-organizing/_permanent-notes/llm-generated-permanent-notes"
)

#: Cap on `**Related:**` wiki-link list per the user's choice.
DEFAULT_TOP_RELATED: int = 25

#: Frontmatter regex.
_FM_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)

#: Wiki-link extractor (handles both `[[A]]` and `[[A|alias]]`).
_WIKI_LINK_RE = re.compile(r"\[\[([^\]\n|]+)(?:\|[^\]\n]+)?\]\]")

#: Matches the `**Related:**` (or `**Related-Concepts:**`) line that the
#: pipeline emits. The line may be very long (20K+ chars in the worst case).
_RELATED_LINE_RE = re.compile(
    r"^(\*\*Related(?:[ -]Concepts?)?:\*\*\s*)(.*?)(\s*)$",
    re.MULTILINE,
)

#: ASCII transliteration table for filename normalization.
_TRANSLIT = {
    "×": "x", "÷": "div", "—": "-", "–": "-",
    "'": "", "\u2019": "", "\u201c": "", "\u201d": "",
    "ä": "a", "ö": "o", "ü": "u", "ß": "ss",
    "é": "e", "è": "e", "ê": "e", "ë": "e",
    "á": "a", "à": "a", "â": "a", "ñ": "n",
    "ç": "c", "í": "i", "ó": "o", "ú": "u",
}


# ============================================================================
# Logging
# ============================================================================

logger = logging.getLogger(__name__)


# ============================================================================
# Custom exceptions
# ============================================================================

class MigrationError(Exception):
    """Base exception for migrate_to_vault-specific errors."""


# ============================================================================
# Data types
# ============================================================================

class Outcome:
    """Migration verdicts. String constants for CSV reporting."""

    MIGRATED = "migrated"
    SKIPPED_COLLISION = "skipped-collision"
    SKIPPED_PARSE_ERROR = "skipped-parse-error"
    DRY_RUN = "dry-run"


@dataclass
class MigrationRecord:
    """One source file plus the outcome of migrating it.

    Attributes:
        source_path: Original file path.
        new_filename: Computed kebab-case filename.
        new_path: Destination path in staging dir.
        outcome: One of the ``Outcome.*`` constants.
        reason: Human-readable explanation.
        related_links_before: Length of `**Related:**` line before cleanup.
        related_links_after: Length after dedup + cap.
        aliases_added: Aliases generated and inserted.
    """

    source_path: Path
    new_filename: str
    new_path: Path
    outcome: str = ""
    reason: str = ""
    related_links_before: int = 0
    related_links_after: int = 0
    aliases_added: list[str] = field(default_factory=list)


# ============================================================================
# Filename normalization
# ============================================================================

def kebab_filename(name: str) -> str:
    """Convert a free-form title or filename to aggressive kebab-case.

    Distinct from ``normalize_key`` in triage_stubs.py: this function
    PRESERVES parenthetical content (slugged) so that distinct concepts like
    ``"Chunk (Miller, 1956)"`` do not collide. Dedup against the source set
    happens during triage; by the time files reach this script they are
    already unique.

    Examples::

        "4CID Blueprint Completeness Checklist.md"
            -> "4cid-blueprint-completeness-checklist"
        "2x2 Achievement Goal Framework"
            -> "2x2-achievement-goal-framework"
        "Chunk (Miller, 1956; Chase & Simon, 1973)"
            -> "chunk-miller-1956-chase-simon-1973"

    Args:
        name: Title or filename (with or without ``.md``).

    Returns:
        Lowercase kebab-case string. Empty string if input has no alpha chars.
    """
    if not name:
        return ""
    s = str(name).strip()
    if s.lower().endswith(".md"):
        s = s[:-3]
    # Transliterate non-ASCII characters to ASCII
    for src_char, ascii_char in _TRANSLIT.items():
        s = s.replace(src_char, ascii_char)
    # Drop any remaining non-ASCII via best-effort encode
    s = s.encode("ascii", errors="ignore").decode("ascii")
    # Replace any non-alphanumeric run with single hyphen
    s = re.sub(r"[^a-zA-Z0-9]+", "-", s)
    s = re.sub(r"-+", "-", s).strip("-").lower()
    return s


# ============================================================================
# Frontmatter handling
# ============================================================================

def parse_frontmatter(text: str) -> tuple[dict[str, Any], str]:
    """Split a Markdown file into (frontmatter dict, body text).

    Returns ``({}, text)`` if no frontmatter block is found or parsing fails.
    """
    match = _FM_RE.match(text)
    if not match:
        return {}, text
    try:
        fm = yaml.safe_load(match.group(1)) or {}
        if not isinstance(fm, dict):
            return {}, text
    except yaml.YAMLError as e:
        logger.debug("YAML parse failed: %s", e)
        return {}, text
    body = text[match.end():]
    return fm, body


def dump_frontmatter(fm: dict[str, Any]) -> str:
    """Serialize a frontmatter dict back to a YAML block.

    Uses block-style sequences for list fields (matches vault style).

    Args:
        fm: Frontmatter dict.

    Returns:
        String including leading ``---`` and trailing ``---\\n``.
    """
    body = yaml.safe_dump(
        fm,
        sort_keys=False,
        allow_unicode=True,
        default_flow_style=False,
        width=120,
    )
    return f"---\n{body}---\n"


def normalize_frontmatter(
    fm: dict[str, Any],
    *,
    source_title: str,
    slug: str,
) -> tuple[dict[str, Any], list[str]]:
    """Return a normalized frontmatter dict plus the list of aliases added.

    Behavior:
        - Sets ``title`` to the source title if missing.
        - Generates ``aliases`` from slug + spaced-title form (per user's
          choice in clarification).
        - Preserves source-provided aliases; merges with generated ones.
        - Ensures required fields exist with sensible defaults.
        - Leaves all other source-provided fields untouched.

    Args:
        fm: Source frontmatter dict (mutated copy returned).
        source_title: Title from the source frontmatter or filename.
        slug: kebab-case slug for this note.

    Returns:
        Tuple of (normalized frontmatter dict, list of aliases newly added).
    """
    out = dict(fm)  # shallow copy

    # title
    if not out.get("title"):
        out["title"] = source_title

    # aliases: merge source + generated
    existing_aliases = out.get("aliases") or []
    if not isinstance(existing_aliases, list):
        existing_aliases = [str(existing_aliases)]
    existing_set = {str(a).strip() for a in existing_aliases if str(a).strip()}

    generated: list[str] = []
    spaced_form = source_title.strip()
    if spaced_form and spaced_form not in existing_set:
        generated.append(spaced_form)
    if slug and slug not in existing_set and slug != spaced_form:
        generated.append(slug)

    out["aliases"] = [
        *(str(a) for a in existing_aliases if str(a).strip()),
        *generated,
    ]

    # Ensure required fields with safe defaults if missing
    out.setdefault("type", "permanent-note")
    out.setdefault("status", "evergreen")
    if "tags" not in out or not out["tags"]:
        out["tags"] = ["permanent-note"]
    elif not isinstance(out["tags"], list):
        out["tags"] = [str(out["tags"])]

    return out, generated


# ============================================================================
# Body cleanup -- the `**Related:**` line
# ============================================================================

def clean_related_line(line_content: str, top_n: int) -> tuple[str, int, int]:
    """Dedupe wiki-links in a `**Related:**` line, keep top-N by frequency.

    Per user's choice in clarification: preserves the implicit centrality
    signal (links appearing many times are likely more central concepts) by
    using frequency-based ranking rather than alphabetical or first-seen.

    Args:
        line_content: The text after `**Related:**` and before EOL.
        top_n: Maximum number of unique links to keep (0 = uncapped).

    Returns:
        Tuple of (cleaned content joined with ` \u00b7 `, count_before, count_after).
    """
    matches = _WIKI_LINK_RE.findall(line_content)
    count_before = len(matches)
    if not matches:
        return line_content.strip(), 0, 0

    # Reconstruct the full link text (handles `[[A|alias]]` form)
    full_links: list[str] = []
    for m in _WIKI_LINK_RE.finditer(line_content):
        full_links.append(m.group(0))

    # Frequency rank, then take top-N preserving order of first appearance
    counter = Counter(full_links)
    ranked = sorted(
        counter.items(),
        key=lambda kv: (-kv[1], full_links.index(kv[0])),
    )
    if top_n > 0:
        ranked = ranked[:top_n]
    cleaned = [link for link, _ in ranked]
    return " \u00b7 ".join(cleaned), count_before, len(cleaned)


def transform_body(body: str, top_related: int) -> tuple[str, int, int]:
    """Find and clean the `**Related:**` line(s) in the body.

    Args:
        body: Full body text (frontmatter already stripped).
        top_related: Cap for the related-links list.

    Returns:
        Tuple of (transformed body, total links before, total links after).
    """
    total_before = 0
    total_after = 0

    def _replace(m: re.Match[str]) -> str:
        nonlocal total_before, total_after
        prefix = m.group(1)
        content = m.group(2)
        cleaned, before, after = clean_related_line(content, top_related)
        total_before += before
        total_after += after
        return f"{prefix}{cleaned}"

    new_body = _RELATED_LINE_RE.sub(_replace, body)
    return new_body, total_before, total_after


# ============================================================================
# Collision detection
# ============================================================================

def build_vault_index(vault_dir: Path) -> set[str]:
    """Set of existing filename stems in the canonical vault folder.

    Used to skip migrations that would overwrite an already-vaulted note.

    Args:
        vault_dir: Path to the canonical vault folder.

    Returns:
        Set of lowercased filename stems. Empty if vault_dir is missing.
    """
    if not vault_dir.is_dir():
        logger.warning("Vault dir not found, collision check disabled: %s", vault_dir)
        return set()
    stems = {p.stem.lower() for p in vault_dir.rglob("*.md")}
    logger.info("Built vault index: %d filenames from %s", len(stems), vault_dir)
    return stems


# ============================================================================
# Migration -- single file
# ============================================================================

def migrate_one(
    src: Path,
    *,
    staging_dir: Path,
    vault_index: set[str],
    top_related: int,
    dry_run: bool,
) -> MigrationRecord:
    """Migrate one source file. Returns a :class:`MigrationRecord`."""
    try:
        text = src.read_text(encoding="utf-8", errors="replace")
    except OSError as e:
        return MigrationRecord(
            source_path=src,
            new_filename="",
            new_path=Path(),
            outcome=Outcome.SKIPPED_PARSE_ERROR,
            reason=f"read failed: {e}",
        )

    fm, body = parse_frontmatter(text)
    source_title = str(fm.get("title", "")).strip().strip('"').strip() or src.stem
    slug = kebab_filename(source_title) or kebab_filename(src.stem)
    if not slug:
        return MigrationRecord(
            source_path=src,
            new_filename="",
            new_path=Path(),
            outcome=Outcome.SKIPPED_PARSE_ERROR,
            reason="could not derive a kebab-case slug",
        )

    new_filename = f"{slug}.md"
    new_path = staging_dir / new_filename

    # Collision against the canonical vault?
    if slug.lower() in vault_index:
        return MigrationRecord(
            source_path=src,
            new_filename=new_filename,
            new_path=new_path,
            outcome=Outcome.SKIPPED_COLLISION,
            reason=f"vault already has {new_filename}",
        )

    # Normalize frontmatter
    new_fm, generated_aliases = normalize_frontmatter(
        fm, source_title=source_title, slug=slug,
    )

    # Clean the body
    new_body, before, after = transform_body(body, top_related)

    # Compose the new file content
    new_text = dump_frontmatter(new_fm) + new_body

    if dry_run:
        return MigrationRecord(
            source_path=src,
            new_filename=new_filename,
            new_path=new_path,
            outcome=Outcome.DRY_RUN,
            reason="dry-run -- no write",
            related_links_before=before,
            related_links_after=after,
            aliases_added=generated_aliases,
        )

    new_path.parent.mkdir(parents=True, exist_ok=True)
    new_path.write_text(new_text, encoding="utf-8")
    return MigrationRecord(
        source_path=src,
        new_filename=new_filename,
        new_path=new_path,
        outcome=Outcome.MIGRATED,
        reason="ok",
        related_links_before=before,
        related_links_after=after,
        aliases_added=generated_aliases,
    )


# ============================================================================
# Orchestration
# ============================================================================

def run_migration(
    source_dir: Path,
    staging_dir: Path,
    vault_dir: Path,
    *,
    top_related: int,
    dry_run: bool,
) -> tuple[list[MigrationRecord], dict[str, int]]:
    """End-to-end migration. Returns (records, stats dict).

    Args:
        source_dir: Folder of already-comprehensive source notes.
        staging_dir: Where to write the normalized output.
        vault_dir: Canonical vault folder (read-only, collision check only).
        top_related: Cap on `**Related:**` wiki-links.
        dry_run: If True, write nothing.
    """
    if not source_dir.is_dir():
        raise MigrationError(f"Source dir not found: {source_dir}")

    vault_index = build_vault_index(vault_dir)
    sources = sorted(source_dir.rglob("*.md"))
    logger.info("Scanning %d source files from %s", len(sources), source_dir)

    records: list[MigrationRecord] = []
    for src in sources:
        rec = migrate_one(
            src,
            staging_dir=staging_dir,
            vault_index=vault_index,
            top_related=top_related,
            dry_run=dry_run,
        )
        records.append(rec)

    by_outcome: dict[str, int] = {}
    total_before = 0
    total_after = 0
    for r in records:
        by_outcome[r.outcome] = by_outcome.get(r.outcome, 0) + 1
        total_before += r.related_links_before
        total_after += r.related_links_after

    stats = {
        "total": len(records),
        "vault_index_size": len(vault_index),
        "related_links_before": total_before,
        "related_links_after": total_after,
        **by_outcome,
    }
    return records, stats


def write_report(records: list[MigrationRecord], report_path: Path) -> None:
    """Write the migration outcomes to CSV."""
    report_path.parent.mkdir(parents=True, exist_ok=True)
    with report_path.open("w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow([
            "outcome", "new_filename", "links_before", "links_after",
            "aliases_added", "source_path", "new_path", "reason",
        ])
        for r in sorted(records, key=lambda r: (r.outcome, r.new_filename)):
            w.writerow([
                r.outcome, r.new_filename,
                r.related_links_before, r.related_links_after,
                "; ".join(r.aliases_added),
                str(r.source_path), str(r.new_path), r.reason,
            ])
    logger.info("Wrote migration report: %s", report_path)


# ============================================================================
# CLI
# ============================================================================

def build_parser() -> argparse.ArgumentParser:
    """Construct the command-line argument parser."""
    parser = argparse.ArgumentParser(
        prog="migrate_to_vault",
        description=(
            "Format-normalize the 'already-comprehensive' bucket from "
            "triage_stubs to match the canonical vault format."
        ),
        epilog=(
            "Examples:\n"
            "  python migrate_to_vault.py --dry-run\n"
            "      Preview the migration; print stats; write nothing.\n"
            "\n"
            "  python migrate_to_vault.py\n"
            "      Migrate everything in the default source dir into the staging dir.\n"
            "\n"
            "  python migrate_to_vault.py --top-related 50\n"
            "      Keep up to 50 unique wiki-links in the **Related:** line.\n"
            "\n"
            "After migration, review files in the staging dir, then move into the vault:\n"
            "  mv <staging>/*.md "
            "<vault>/999-report-organizing/_permanent-notes/llm-generated-permanent-notes/\n"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--source-dir", type=Path, default=DEFAULT_SOURCE_DIR, metavar="PATH",
        help=f"Source folder (default: {DEFAULT_SOURCE_DIR}).",
    )
    parser.add_argument(
        "--staging-dir", type=Path, default=DEFAULT_STAGING_DIR, metavar="PATH",
        help=f"Output folder for normalized files (default: {DEFAULT_STAGING_DIR}).",
    )
    parser.add_argument(
        "--vault-dir", type=Path, default=DEFAULT_VAULT_DIR, metavar="PATH",
        help=(
            "Canonical vault folder, used READ-ONLY for collision detection "
            f"(default: {DEFAULT_VAULT_DIR})."
        ),
    )
    parser.add_argument(
        "--top-related", type=int, default=DEFAULT_TOP_RELATED, metavar="N",
        help=(
            "Max unique wiki-links kept in **Related:** line; ranked by "
            f"frequency. 0 = uncapped (default: {DEFAULT_TOP_RELATED})."
        ),
    )
    parser.add_argument(
        "-n", "--dry-run", action="store_true",
        help="Run the full migration but write nothing. Prints stats.",
    )
    parser.add_argument("-v", "--verbose", action="count", default=0,
                        help="Increase logging verbosity (repeatable).")
    parser.add_argument("-q", "--quiet", action="store_true",
                        help="Suppress non-error output.")
    parser.add_argument("--version", action="version",
                        version=f"%(prog)s {__version__}")
    return parser


def configure_logging(verbosity: int, quiet: bool) -> None:
    """Set the root logger level from CLI flags."""
    if quiet:
        level = logging.ERROR
    elif verbosity >= 2:
        level = logging.DEBUG
    elif verbosity == 1:
        level = logging.INFO
    else:
        level = logging.WARNING
    logging.basicConfig(
        level=level,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        datefmt="%H:%M:%S",
    )


def _print_summary(stats: dict[str, int], staging_dir: Path, dry_run: bool) -> None:
    """Print the migration summary. ASCII only (Windows cp1252 safe)."""
    print()
    print("=" * 64)
    print("  MIGRATION SUMMARY" + ("  (DRY-RUN -- nothing written)" if dry_run else ""))
    print("=" * 64)
    print(f"  Source files scanned:       {stats.get('total', 0):>5}")
    print(f"  Vault index size:           {stats.get('vault_index_size', 0):>5}")
    print()
    print("  Outcomes:")
    rows = [
        ("  migrated",              Outcome.MIGRATED),
        ("  dry-run (would write)", Outcome.DRY_RUN),
        ("  skipped-collision",    Outcome.SKIPPED_COLLISION),
        ("  skipped-parse-error",  Outcome.SKIPPED_PARSE_ERROR),
    ]
    for label, key in rows:
        print(f"  {label:<28} {stats.get(key, 0):>5}")
    print()
    print("  **Related:** line cleanup:")
    print(f"    total wiki-links before:  {stats.get('related_links_before', 0):>6}")
    print(f"    total wiki-links after:   {stats.get('related_links_after', 0):>6}")
    print()
    if not dry_run:
        print(f"  Staging dir:  {staging_dir}")
        print(f"  Report CSV:   {staging_dir / 'migration-report.csv'}")
    print("=" * 64)


def main(argv: list[str] | None = None) -> int:
    """Main entry point. Returns the process exit code."""
    parser = build_parser()
    args = parser.parse_args(argv)
    configure_logging(args.verbose, args.quiet)

    if not args.source_dir.is_dir():
        logger.error("Source directory not found: %s", args.source_dir)
        logger.error(
            "Hint: run triage_stubs.py first to populate the "
            "'already-comprehensive' bucket."
        )
        return 2

    try:
        records, stats = run_migration(
            source_dir=args.source_dir,
            staging_dir=args.staging_dir,
            vault_dir=args.vault_dir,
            top_related=args.top_related,
            dry_run=args.dry_run,
        )
    except MigrationError as e:
        logger.error("Migration failed: %s", e)
        return 2
    except KeyboardInterrupt:
        logger.warning("Interrupted by user")
        return 130
    except Exception:  # noqa: BLE001 -- top-level safety net
        logger.exception("Unexpected error during migration")
        return 1

    if stats.get("total", 0) == 0:
        logger.warning("No source files found in %s", args.source_dir)
        return 4

    if not args.dry_run:
        write_report(records, args.staging_dir / "migration-report.csv")

    _print_summary(stats, args.staging_dir, args.dry_run)
    return 0


# ============================================================================
# Entry-point guard
# ============================================================================

if __name__ == "__main__":
    sys.exit(main())
