#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""triage_stubs.py — Slim 1,200+ pipeline stubs to a curated enrichment set.

Companion to ``enrich_stubs.py``. Scans the v3 pipeline stub folder, compares
against the existing enriched-notes folder (the canonical target), classifies
every stub, scores keepers by signal strength, and copies the top-N candidates
into a curated working directory ready for ``enrich_stubs.py --input-dir``.

Pipeline:

    Source stubs (1,222)                                           [INPUT]
        │
        ├──▶ Already enriched in target?    ──▶ skip-already-enriched
        ├──▶ Duplicate of higher-scoring stub? ─▶ skip-duplicate
        ├──▶ Empty + zero references?       ──▶ skip-low-signal
        ├──▶ Already comprehensive (full body, headings, real def)? ──▶ ready-vault
        └──▶ Otherwise                      ──▶ candidate (scored)
                                                  │
                                                  ▼
                                            sort by score, take top N
                                                  │
                                                  ▼
                                            curated/  (~200 files)   [OUTPUT]

Output buckets (under ``--output-root``, default
``D:/00-inbox/v3-pipeline-permanet-note-leftovers/_triage-output``):

    curated-for-enrichment/         Top-N stubs ready for enrich_stubs.py
    already-comprehensive/          Stubs that already look done — review and
                                    move directly into the vault, no LLM needed
    triage-report.csv               Full classification of all source stubs

Usage::

    python triage_stubs.py --dry-run
    python triage_stubs.py --top-n 200
    python triage_stubs.py --top-n 250 --output-root D:/triage-out
    python triage_stubs.py --top-n 200 --include-comprehensive

Exit codes:

    0   success
    1   uncaught error
    2   bad arguments / missing input
    4   no stubs found
    130 interrupted (SIGINT)

Version:
    1.0.0

Python:
    >=3.10

Dependencies:
    - stdlib: argparse, csv, dataclasses, logging, pathlib, re, shutil, sys
    - third-party: PyYAML (>=5.0)

Author:
    Generated by Python Script Designer & Generator — Expert v1.0.0
"""
from __future__ import annotations

# ── Standard library ────────────────────────────────────────────────────────
import argparse
import csv
import logging
import re
import shutil
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable

# ── Third-party ─────────────────────────────────────────────────────────────
import yaml


# ════════════════════════════════════════════════════════════════════════════
# Constants
# ════════════════════════════════════════════════════════════════════════════

__version__ = "1.0.0"

#: Default source: the v3 pipeline stub dump.
DEFAULT_SOURCE_DIR: Path = Path(
    "D:/00-inbox/v3-pipeline-permanet-note-leftovers/v3-pipeline-permanent-notes"
)

#: Default target: the canonical enriched-notes folder. Anything whose
#: normalized key already exists here is skipped — that note is already done.
DEFAULT_TARGET_DIR: Path = Path(
    "D:/10_pur3v4d3r's-vault/999-report-organizing/_permanent-notes/llm-generated-permanent-notes"
)

#: Default output root. Three sub-buckets are created under this dir.
DEFAULT_OUTPUT_ROOT: Path = Path(
    "D:/00-inbox/v3-pipeline-permanet-note-leftovers/_triage-output"
)

#: Body length below which a stub is considered effectively empty.
EMPTY_BODY_THRESHOLD: int = 200

#: Body length above which a stub is considered already-comprehensive
#: (combined with structural checks). LLM enrichment would only dilute it.
COMPREHENSIVE_BODY_THRESHOLD: int = 1500

#: Minimum number of top-level H2 headings for "comprehensive" classification.
COMPREHENSIVE_MIN_H2: int = 2

#: Default top-N keepers.
DEFAULT_TOP_N: int = 200

#: Frontmatter regex — leading ``---`` block, very tolerant.
_FM_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)

#: Stub placeholder definition signature (v3 pipeline).
_PLACEHOLDER_DEF_RE = re.compile(r">\s*\*Stub note\s*[—-]", re.IGNORECASE)

#: Auto-generated stub notice line.
_AUTO_STUB_RE = re.compile(r"\*Auto-generated stub[^*\n]*\*", re.IGNORECASE)

#: Top-level H2 heading.
_H2_RE = re.compile(r"^##\s+\S", re.MULTILINE)


# ════════════════════════════════════════════════════════════════════════════
# Logging
# ════════════════════════════════════════════════════════════════════════════

logger = logging.getLogger(__name__)


# ════════════════════════════════════════════════════════════════════════════
# Custom exceptions
# ════════════════════════════════════════════════════════════════════════════

class TriageError(Exception):
    """Base exception for triage_stubs-specific errors."""


# ════════════════════════════════════════════════════════════════════════════
# Data types
# ════════════════════════════════════════════════════════════════════════════

class Decision:
    """Classification verdicts. String constants for CSV-friendly reporting."""

    CANDIDATE = "candidate"
    SKIP_ALREADY_ENRICHED = "skip-already-enriched"
    SKIP_DUPLICATE = "skip-duplicate"
    SKIP_LOW_SIGNAL = "skip-low-signal"
    READY_FOR_VAULT = "ready-for-vault"
    SKIP_PARSE_ERROR = "skip-parse-error"
    NOT_SELECTED = "not-selected"  # Was a candidate but lost the top-N cut


@dataclass
class StubCandidate:
    """One source stub plus everything needed to triage it.

    Attributes:
        path: Absolute path to the source ``.md`` file.
        title: Display title (frontmatter ``title`` or filename stem).
        normalized_key: Canonical kebab-case identifier used for dedup against
            target index and against other source stubs.
        ref_count: ``referenced-by-count`` from frontmatter (0 if missing).
        alias_count: Number of aliases declared in frontmatter.
        body_len: Length of body text (frontmatter stripped).
        h2_count: Number of ``##`` headings in body.
        has_real_definition: True if ``[!definition]`` callout has real prose
            (not the v3 placeholder).
        is_already_enriched: True if a target file with the same key exists.
        score: Composite priority score; higher = better candidate.
        decision: One of the ``Decision.*`` constants.
        reason: Human-readable explanation of the decision.
    """

    path: Path
    title: str
    normalized_key: str
    ref_count: int = 0
    alias_count: int = 0
    body_len: int = 0
    h2_count: int = 0
    has_real_definition: bool = False
    is_already_enriched: bool = False
    score: int = 0
    decision: str = Decision.CANDIDATE
    reason: str = ""
    aliases: list[str] = field(default_factory=list)


# ════════════════════════════════════════════════════════════════════════════
# Frontmatter parsing (standalone — does not depend on lib/frontmatter)
# ════════════════════════════════════════════════════════════════════════════

def parse_frontmatter(text: str) -> tuple[dict[str, Any], str]:
    """Split a Markdown file into (frontmatter dict, body text).

    Returns ``({}, text)`` if no frontmatter block is found or parsing fails.

    Args:
        text: Full file contents.

    Returns:
        A tuple of (frontmatter dict, body string).
    """
    match = _FM_RE.match(text)
    if not match:
        return {}, text
    try:
        fm = yaml.safe_load(match.group(1)) or {}
        if not isinstance(fm, dict):
            return {}, text
    except yaml.YAMLError as e:
        logger.debug("YAML parse failed: %s", e)
        return {}, text
    body = text[match.end():]
    return fm, body


# ════════════════════════════════════════════════════════════════════════════
# Key normalization
# ════════════════════════════════════════════════════════════════════════════

def normalize_key(name: str) -> str:
    """Reduce a title or filename to a canonical kebab-case lookup key.

    Strips parenthetical disambiguators, punctuation, smart-quotes, and
    collapses whitespace + hyphens. Used to dedup variants like::

        "Achievement Goal"                                 → "achievement-goal"
        "Achievement-Goal.md"                              → "achievement-goal"
        "Achievement Goal (Achievement Goal Theory ...)"   → "achievement-goal"
        "achievement-goal-theory.md"                       → "achievement-goal-theory"

    Note: this is an *aggressive* normalizer — it intentionally collapses
    "Achievement Goal" and "Achievement Goal (AGT tradition)" to the same key
    because in your taxonomy they should resolve to one note.

    Args:
        name: Title string or filename (with or without ``.md``).

    Returns:
        Lowercase kebab-case string. Empty string if input has no alpha chars.
    """
    if not name:
        return ""
    s = str(name).strip()
    # Strip extension
    if s.lower().endswith(".md"):
        s = s[:-3]
    # Drop parenthetical content
    s = re.sub(r"\s*\([^)]*\)\s*", " ", s)
    # Normalize separators and unicode dashes to ASCII hyphen
    s = s.replace("—", "-").replace("–", "-").replace("'", "").replace("\u2019", "")
    # Replace any non-alphanumeric run with single hyphen
    s = re.sub(r"[^a-zA-Z0-9]+", "-", s)
    # Collapse repeated hyphens, strip edge hyphens, lowercase
    s = re.sub(r"-+", "-", s).strip("-").lower()
    return s


# ════════════════════════════════════════════════════════════════════════════
# Target index — the "already done" lookup
# ════════════════════════════════════════════════════════════════════════════

def build_target_index(target_dir: Path) -> set[str]:
    """Build the set of normalized keys already present in the target folder.

    A stub matching any of these keys is classified as already enriched.

    Args:
        target_dir: Directory of canonical enriched notes.

    Returns:
        Set of normalized keys. Empty set if target_dir is missing.
    """
    if not target_dir.is_dir():
        logger.warning("Target dir not found, index will be empty: %s", target_dir)
        return set()

    index: set[str] = set()
    for md_path in target_dir.rglob("*.md"):
        # Filename-derived key
        index.add(normalize_key(md_path.stem))
        # Title- and alias-derived keys (titles may differ from filenames)
        try:
            text = md_path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        fm, _ = parse_frontmatter(text)
        title = fm.get("title")
        if title:
            index.add(normalize_key(str(title)))
        for alias in (fm.get("aliases") or []):
            index.add(normalize_key(str(alias)))

    index.discard("")
    logger.info("Built target index: %d unique keys from %s", len(index), target_dir)
    return index


# ════════════════════════════════════════════════════════════════════════════
# Stub classification
# ════════════════════════════════════════════════════════════════════════════

def _strip_boilerplate(body: str) -> str:
    """Remove placeholder callouts and auto-stub notices to compute true body length."""
    cleaned = _AUTO_STUB_RE.sub("", body)
    # Drop "Referenced By" section (auto-generated, not real content)
    cleaned = re.sub(
        r"## Referenced By\s*\n(?:- \[\[.*?\]\]\s*\n)*", "", cleaned
    )
    return cleaned.strip()


def _has_real_definition(body: str) -> bool:
    """True iff ``[!definition]`` callout exists and is NOT the v3 stub placeholder."""
    if "!definition" not in body.lower():
        return False
    return not bool(_PLACEHOLDER_DEF_RE.search(body))


def _looks_comprehensive(stub: StubCandidate) -> bool:
    """True iff the stub is already a fully fleshed-out note."""
    return (
        stub.body_len >= COMPREHENSIVE_BODY_THRESHOLD
        and stub.h2_count >= COMPREHENSIVE_MIN_H2
        and stub.has_real_definition
    )


def parse_stub(path: Path) -> StubCandidate | None:
    """Parse one source stub file into a :class:`StubCandidate`.

    Args:
        path: Path to a ``.md`` file.

    Returns:
        StubCandidate, or None if the file cannot be read.
    """
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError as e:
        logger.warning("Read failed for %s: %s", path, e)
        return None

    fm, body = parse_frontmatter(text)
    raw_title = str(fm.get("title", "")).strip().strip('"').strip()
    title = raw_title if raw_title else path.stem

    aliases_raw = fm.get("aliases") or []
    aliases = [str(a).strip() for a in aliases_raw if str(a).strip()]

    # ref-count: try multiple frontmatter keys
    ref_count = 0
    for key in ("referenced-by-count", "ref-count", "incoming-links"):
        v = fm.get(key)
        if isinstance(v, int):
            ref_count = max(ref_count, v)
        elif isinstance(v, str) and v.isdigit():
            ref_count = max(ref_count, int(v))

    cleaned_body = _strip_boilerplate(body)

    return StubCandidate(
        path=path,
        title=title,
        normalized_key=normalize_key(title or path.stem),
        ref_count=ref_count,
        alias_count=len(aliases),
        body_len=len(cleaned_body),
        h2_count=len(_H2_RE.findall(body)),
        has_real_definition=_has_real_definition(body),
        aliases=aliases,
    )


def classify_stub(stub: StubCandidate, target_index: set[str]) -> None:
    """Assign ``decision`` and ``reason`` in-place. Does not handle dedup
    against other stubs — that runs in a second pass after scoring.

    Args:
        stub: A parsed stub. Mutated.
        target_index: Set of keys already present in the target folder.
    """
    # Check #1: already enriched in target?
    if stub.normalized_key and stub.normalized_key in target_index:
        stub.is_already_enriched = True
        stub.decision = Decision.SKIP_ALREADY_ENRICHED
        stub.reason = f"key {stub.normalized_key!r} present in target"
        return

    # Check #2: aliases already enriched?
    for alias in stub.aliases:
        if normalize_key(alias) in target_index:
            stub.is_already_enriched = True
            stub.decision = Decision.SKIP_ALREADY_ENRICHED
            stub.reason = f"alias {alias!r} present in target"
            return

    # Check #3: already comprehensive — bypass LLM entirely
    if _looks_comprehensive(stub):
        stub.decision = Decision.READY_FOR_VAULT
        stub.reason = (
            f"body={stub.body_len}c, h2={stub.h2_count}, real-def=yes"
        )
        return

    # Check #4: low signal — empty body AND zero references
    if stub.body_len < EMPTY_BODY_THRESHOLD and stub.ref_count == 0:
        stub.decision = Decision.SKIP_LOW_SIGNAL
        stub.reason = f"body={stub.body_len}c, refs=0"
        return

    # Default: candidate
    stub.decision = Decision.CANDIDATE
    stub.reason = (
        f"body={stub.body_len}c, refs={stub.ref_count}, h2={stub.h2_count}"
    )


# ════════════════════════════════════════════════════════════════════════════
# Scoring
# ════════════════════════════════════════════════════════════════════════════

def score_stub(stub: StubCandidate) -> int:
    """Compute the priority score for a candidate stub.

    Heuristic: ``referenced-by-count`` is the strongest signal (it counts how
    many other notes already wiki-link to this concept — a measure of how
    central the concept is to the existing graph). Aliases and existing body
    content add smaller bonuses.

    Args:
        stub: A candidate stub.

    Returns:
        Integer score. Higher = higher priority.
    """
    score = stub.ref_count * 10
    score += stub.alias_count * 5
    if stub.body_len >= EMPTY_BODY_THRESHOLD:
        score += 10
    if stub.has_real_definition:
        score += 25
    # Mild penalty for very long titles (often disambiguator-heavy variants)
    if len(stub.title) > 60:
        score -= 5
    return score


def dedupe_by_key(candidates: list[StubCandidate]) -> list[StubCandidate]:
    """Within candidates, keep the highest-scoring stub per normalized key.

    Mutates losing candidates' ``decision`` to ``SKIP_DUPLICATE``.

    Args:
        candidates: All scored stubs (kept and rejected).

    Returns:
        The list unchanged (mutated in place); the winners are those still
        with ``decision == CANDIDATE``.
    """
    by_key: dict[str, StubCandidate] = {}
    for stub in candidates:
        if stub.decision != Decision.CANDIDATE or not stub.normalized_key:
            continue
        winner = by_key.get(stub.normalized_key)
        if winner is None or stub.score > winner.score:
            if winner is not None:
                winner.decision = Decision.SKIP_DUPLICATE
                winner.reason = (
                    f"lost to {stub.path.name!r} (score {stub.score} vs {winner.score})"
                )
            by_key[stub.normalized_key] = stub
        else:
            stub.decision = Decision.SKIP_DUPLICATE
            stub.reason = (
                f"lost to {winner.path.name!r} (score {winner.score} vs {stub.score})"
            )
    return candidates


def select_top_n(candidates: list[StubCandidate], top_n: int) -> list[StubCandidate]:
    """Return the top-N candidates by score; mark the rest as ``NOT_SELECTED``.

    Args:
        candidates: All scored stubs.
        top_n: Maximum keepers (0 = no cap).

    Returns:
        The selected list (sorted by score descending).
    """
    keepers = [s for s in candidates if s.decision == Decision.CANDIDATE]
    keepers.sort(key=lambda s: (-s.score, s.title.lower()))
    if top_n > 0 and len(keepers) > top_n:
        for loser in keepers[top_n:]:
            loser.decision = Decision.NOT_SELECTED
            loser.reason = f"score {loser.score} below top-{top_n} cutoff"
        keepers = keepers[:top_n]
    return keepers


# ════════════════════════════════════════════════════════════════════════════
# I/O layer
# ════════════════════════════════════════════════════════════════════════════

def scan_source(source_dir: Path) -> list[StubCandidate]:
    """Recursively parse every ``.md`` file under ``source_dir``.

    Args:
        source_dir: The stub folder to triage.

    Returns:
        List of parsed StubCandidates (unparseable files dropped, with a
        warning logged).
    """
    if not source_dir.is_dir():
        raise TriageError(f"Source dir not found: {source_dir}")

    stubs: list[StubCandidate] = []
    for md_path in sorted(source_dir.rglob("*.md")):
        stub = parse_stub(md_path)
        if stub is not None:
            stubs.append(stub)
    logger.info("Scanned %d source files from %s", len(stubs), source_dir)
    return stubs


def copy_to_curated(
    stubs: Iterable[StubCandidate],
    dest_dir: Path,
    *,
    dry_run: bool = False,
) -> int:
    """Copy each stub's source file into ``dest_dir``. Returns count copied.

    Filename collisions (different source filenames normalizing to same key
    but only one survives dedup, so this should be rare) are resolved by
    appending the score: ``<stem>__score-<N>.md``.

    Args:
        stubs: Stubs to copy.
        dest_dir: Destination directory (created if absent).
        dry_run: If True, log only — do not write.

    Returns:
        Number of files actually copied (0 in dry-run).
    """
    if not dry_run:
        dest_dir.mkdir(parents=True, exist_ok=True)
    n = 0
    for stub in stubs:
        target = dest_dir / stub.path.name
        if target.exists() and target.resolve() != stub.path.resolve():
            target = dest_dir / f"{stub.path.stem}__score-{stub.score}.md"
        if dry_run:
            logger.debug("[dry-run] would copy %s → %s", stub.path.name, target.name)
        else:
            shutil.copy2(stub.path, target)
            n += 1
    return n


def write_report(stubs: list[StubCandidate], report_path: Path) -> None:
    """Write the full classification of every scanned stub to CSV.

    Args:
        stubs: All stubs (kept and rejected).
        report_path: Output ``.csv`` path.
    """
    report_path.parent.mkdir(parents=True, exist_ok=True)
    with report_path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerow([
            "decision", "score", "ref_count", "body_len", "h2_count",
            "real_def", "key", "title", "path", "reason",
        ])
        # Sort: candidates first by score, then everything else by decision
        ordered = sorted(
            stubs,
            key=lambda s: (
                0 if s.decision == Decision.CANDIDATE else
                1 if s.decision == Decision.READY_FOR_VAULT else
                2 if s.decision == Decision.NOT_SELECTED else 3,
                -s.score,
                s.title.lower(),
            ),
        )
        for s in ordered:
            writer.writerow([
                s.decision, s.score, s.ref_count, s.body_len, s.h2_count,
                "yes" if s.has_real_definition else "no",
                s.normalized_key, s.title, str(s.path), s.reason,
            ])
    logger.info("Wrote triage report: %s", report_path)


# ════════════════════════════════════════════════════════════════════════════
# Orchestration
# ════════════════════════════════════════════════════════════════════════════

def run_triage(
    source_dir: Path,
    target_dir: Path,
    output_root: Path,
    *,
    top_n: int,
    include_comprehensive: bool,
    dry_run: bool,
) -> dict[str, int]:
    """End-to-end triage. Returns a stats dict for the summary table.

    Args:
        source_dir: Folder containing the 1,200+ stubs.
        target_dir: Folder containing the canonical enriched notes.
        output_root: Parent dir for the three output buckets.
        top_n: Maximum curated keepers (0 = uncapped).
        include_comprehensive: If True, also copy ``ready-for-vault`` stubs to
            the curated dir (so enrich_stubs.py touches them too). Off by
            default — comprehensive notes shouldn't be re-LLM'd.
        dry_run: If True, no files are written.

    Returns:
        Dict of counts per bucket.
    """
    target_index = build_target_index(target_dir)
    all_stubs = scan_source(source_dir)

    # Phase A: per-stub classification
    for stub in all_stubs:
        classify_stub(stub, target_index)
        stub.score = score_stub(stub)

    # Phase B: cross-stub dedup
    dedupe_by_key(all_stubs)

    # Phase C: top-N selection
    keepers = select_top_n(all_stubs, top_n)
    comprehensive = [s for s in all_stubs if s.decision == Decision.READY_FOR_VAULT]

    # Phase D: I/O
    curated_dir = output_root / "curated-for-enrichment"
    comp_dir = output_root / "already-comprehensive"
    report_path = output_root / "triage-report.csv"

    n_curated = copy_to_curated(keepers, curated_dir, dry_run=dry_run)
    n_comp = copy_to_curated(comprehensive, comp_dir, dry_run=dry_run)

    if include_comprehensive and not dry_run:
        # Also copy comprehensive into the curated dir so enrich_stubs sees them
        copy_to_curated(comprehensive, curated_dir, dry_run=False)

    if not dry_run:
        write_report(all_stubs, report_path)

    # Build stats dict
    by_decision: dict[str, int] = {}
    for s in all_stubs:
        by_decision[s.decision] = by_decision.get(s.decision, 0) + 1

    return {
        "total": len(all_stubs),
        "target_index_size": len(target_index),
        "curated_copied": n_curated,
        "comprehensive_copied": n_comp,
        **by_decision,
    }


# ════════════════════════════════════════════════════════════════════════════
# CLI
# ════════════════════════════════════════════════════════════════════════════

def build_parser() -> argparse.ArgumentParser:
    """Construct the command-line argument parser."""
    parser = argparse.ArgumentParser(
        prog="triage_stubs",
        description=(
            "Slim a 1,200+ stub dump down to ~200 high-signal candidates "
            "ready for enrich_stubs.py."
        ),
        epilog=(
            "Examples:\n"
            "  python triage_stubs.py --dry-run\n"
            "      Preview the triage; print stats; write nothing.\n"
            "\n"
            "  python triage_stubs.py --top-n 200\n"
            "      Triage with defaults; copy 200 stubs to the curated dir.\n"
            "\n"
            "  python triage_stubs.py --top-n 250 --output-root D:/triage-out\n"
            "      Custom output location and slightly larger keeper set.\n"
            "\n"
            "Then chain into enrichment:\n"
            "  python enrich_stubs.py --input-dir <output-root>/curated-for-enrichment \\\n"
            "                         --dry-run --limit 5\n"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--source-dir", type=Path, default=DEFAULT_SOURCE_DIR, metavar="PATH",
        help=f"Stub folder to triage (default: {DEFAULT_SOURCE_DIR}).",
    )
    parser.add_argument(
        "--target-dir", type=Path, default=DEFAULT_TARGET_DIR, metavar="PATH",
        help=f"Canonical enriched-notes folder (default: {DEFAULT_TARGET_DIR}).",
    )
    parser.add_argument(
        "--output-root", type=Path, default=DEFAULT_OUTPUT_ROOT, metavar="PATH",
        help=(
            "Parent dir for output buckets: curated-for-enrichment/, "
            f"already-comprehensive/, triage-report.csv (default: {DEFAULT_OUTPUT_ROOT})."
        ),
    )
    parser.add_argument(
        "--top-n", type=int, default=DEFAULT_TOP_N, metavar="N",
        help=f"Max curated keepers; 0 = uncapped (default: {DEFAULT_TOP_N}).",
    )
    parser.add_argument(
        "--include-comprehensive", action="store_true",
        help=(
            "Also copy already-comprehensive stubs into the curated dir so "
            "enrich_stubs.py processes them. Off by default — comprehensive "
            "notes are usually better moved straight into the vault."
        ),
    )
    parser.add_argument(
        "-n", "--dry-run", action="store_true",
        help="Run the full triage but write nothing. Prints the stats table.",
    )
    parser.add_argument("-v", "--verbose", action="count", default=0,
                        help="Increase logging verbosity (repeatable: -v, -vv).")
    parser.add_argument("-q", "--quiet", action="store_true",
                        help="Suppress non-error output.")
    parser.add_argument("--version", action="version",
                        version=f"%(prog)s {__version__}")
    return parser


def configure_logging(verbosity: int, quiet: bool) -> None:
    """Set the root logger level from CLI flags."""
    if quiet:
        level = logging.ERROR
    elif verbosity >= 2:
        level = logging.DEBUG
    elif verbosity == 1:
        level = logging.INFO
    else:
        level = logging.WARNING
    logging.basicConfig(
        level=level,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        datefmt="%H:%M:%S",
    )


def _print_summary(stats: dict[str, int], output_root: Path, dry_run: bool) -> None:
    """Pretty-print the final triage summary.

    Uses ASCII separators only — the default Windows console codepage
    (cp1252) cannot encode box-drawing characters and crashes on print.
    """
    print()
    print("=" * 64)
    print("  TRIAGE SUMMARY" + ("  (DRY-RUN -- nothing written)" if dry_run else ""))
    print("=" * 64)
    print(f"  Source files scanned:     {stats.get('total', 0):>5}")
    print(f"  Target index size:        {stats.get('target_index_size', 0):>5} keys")
    print()
    print("  Decisions:")
    rows = [
        ("  candidate (curated)",         Decision.CANDIDATE),
        ("  ready-for-vault",             Decision.READY_FOR_VAULT),
        ("  not-selected (below cutoff)", Decision.NOT_SELECTED),
        ("  skip-already-enriched",       Decision.SKIP_ALREADY_ENRICHED),
        ("  skip-duplicate",              Decision.SKIP_DUPLICATE),
        ("  skip-low-signal",             Decision.SKIP_LOW_SIGNAL),
        ("  skip-parse-error",            Decision.SKIP_PARSE_ERROR),
    ]
    for label, key in rows:
        print(f"  {label:<36} {stats.get(key, 0):>5}")
    print()
    if not dry_run:
        print(f"  Curated dir:        {output_root / 'curated-for-enrichment'}")
        print(f"                      -> {stats.get('curated_copied', 0)} files copied")
        print(f"  Already-comp. dir:  {output_root / 'already-comprehensive'}")
        print(f"                      -> {stats.get('comprehensive_copied', 0)} files copied")
        print(f"  Report CSV:         {output_root / 'triage-report.csv'}")
    print("=" * 64)


def main(argv: list[str] | None = None) -> int:
    """Main entry point. Returns the process exit code."""
    parser = build_parser()
    args = parser.parse_args(argv)
    configure_logging(args.verbose, args.quiet)

    if not args.source_dir.is_dir():
        logger.error("Source directory not found: %s", args.source_dir)
        return 2

    try:
        stats = run_triage(
            source_dir=args.source_dir,
            target_dir=args.target_dir,
            output_root=args.output_root,
            top_n=args.top_n,
            include_comprehensive=args.include_comprehensive,
            dry_run=args.dry_run,
        )
    except TriageError as e:
        logger.error("Triage failed: %s", e)
        return 2
    except KeyboardInterrupt:
        logger.warning("Interrupted by user")
        return 130
    except Exception:  # noqa: BLE001 — top-level safety net
        logger.exception("Unexpected error during triage")
        return 1

    if stats.get("total", 0) == 0:
        logger.warning("No stubs found in %s", args.source_dir)
        return 4

    _print_summary(stats, args.output_root, args.dry_run)
    return 0


# ════════════════════════════════════════════════════════════════════════════
# Entry-point guard
# ════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    sys.exit(main())
