#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""reports_to_tts.py — Convert Obsidian-flavored academic markdown reports into audio.

Pipeline:
    Markdown report  →  clean plain text  →  chunked sections  →  TTS backend
                    →  per-chunk audio segments  →  concatenated MP3 (or WAV)
                    →  ID3-tagged output file (one per report)

Backends (pluggable):
    edge   : Microsoft Edge / Azure neural voices via edge-tts (default — zero-setup, free)
    kokoro : Local Kokoro-82M TTS via the `kokoro` Python package (RTX-class GPU)
    xtts   : Coqui XTTS-v2 voice-cloning via TTS package (RTX-class GPU; supports a
             reference WAV to approximate the user's husky-alto voice goal)

Voice-goal reference (from the spec):
    "Husky, lived-in female voice, lower register. Rich alto with noticeable gravel and
    vocal fry on sustained vowels. Thirties, American, conversational and warm. Speaks
    unhurriedly with a slight smile in the tone."
The closest off-the-shelf approximation in the default `edge` backend is
en-US-AriaNeural at rate=-10%. For a faithful match, use the `xtts` backend with a
6-15 second reference clip of the desired voice (see README).

Usage:
    # Single report → MP3 with default voice
    python reports_to_tts.py path/to/report.md

    # Whole folder, write next to each report under ./_audio/
    python reports_to_tts.py path/to/reports_dir --output-dir ./_audio

    # Choose voice + slow it down + use Kokoro local GPU backend
    python reports_to_tts.py reports/ --backend kokoro --voice af_bella --rate -10

    # XTTS voice-clone with a reference clip
    python reports_to_tts.py report.md --backend xtts --speaker-wav ./voice_ref.wav

    # Dry run — preview what would happen, no audio synthesized
    python reports_to_tts.py reports/ --dry-run -vv

Version:
    1.0.0

Python:
    >=3.10

Dependencies:
    Required (stdlib + lightweight):
        - argparse, asyncio, dataclasses, hashlib, logging, pathlib, re, sys (stdlib)
    Required (third-party):
        - pydub>=0.25         # audio concat / format conversion (calls ffmpeg)
        - mutagen>=1.47       # ID3 tagging
    External:
        - ffmpeg              # must be on PATH for pydub to encode MP3
    Backend-specific (install only what you use):
        - edge-tts>=6.1       # `edge` backend
        - kokoro>=0.7         # `kokoro` backend (also: pip install soundfile)
        - TTS>=0.22           # `xtts` backend (Coqui)

Author:
    Generated by Python Script Designer & Generator — Expert v1.0.0
"""
from __future__ import annotations

# ─── Standard library ────────────────────────────────────────────────────
import argparse
import asyncio
import hashlib
import logging
import re
import shutil
import sys
import tempfile
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable, Sequence

# ─── Third-party (lazy-imported per backend; eagerly import only the universal ones) ──
try:
    from pydub import AudioSegment  # type: ignore
    from pydub.utils import which as _pydub_which  # type: ignore

    # On Windows, subprocess.Popen does not search PATH for bare program names,
    # so we resolve ffmpeg/ffprobe to absolute paths and pin them on AudioSegment.
    _FFMPEG = _pydub_which("ffmpeg")
    _FFPROBE = _pydub_which("ffprobe")
    if _FFMPEG:
        AudioSegment.converter = _FFMPEG
    if _FFPROBE:
        AudioSegment.ffprobe = _FFPROBE
except ImportError:  # pragma: no cover - import-time check
    AudioSegment = None  # we'll error clearly in main() if user actually runs synthesis

try:
    from mutagen.easyid3 import EasyID3  # type: ignore
    from mutagen.id3 import ID3NoHeaderError  # type: ignore
except ImportError:  # pragma: no cover
    EasyID3 = None
    ID3NoHeaderError = Exception  # placeholder


# ═════════════════════════════════════════════════════════════════════════
# Constants
# ═════════════════════════════════════════════════════════════════════════

__version__ = "1.0.0"

# Approximate per-request character ceilings per backend. Edge TTS handles ~5k
# safely per WS frame; Kokoro/XTTS prefer ~500-1500 for prosody quality.
DEFAULT_CHUNK_CHARS: dict[str, int] = {
    "edge": 4000,
    "kokoro": 1200,
    # NOTE: XTTS-v2 hard-caps at 400 generation tokens. The tokenizer warns
    # at 250 chars but only crashes on very long single sentences. The chunker
    # splits on sentences first, then hard-wraps anything still too long.
    # 400 keeps short sentences batched (faster) and lets _hard_wrap handle
    # pathological academic run-ons.
    "xtts": 400,
    # F5-TTS handles multi-sentence inputs well via its internal cross-fade;
    # bigger chunks = fewer GPU calls = much faster end-to-end.
    "f5tts": 1200,
}

# Default voice IDs per backend (closest match to the husky-alto target).
DEFAULT_VOICE: dict[str, str] = {
    "edge": "en-US-AriaNeural",   # warm conversational alto
    "kokoro": "af_bella",          # rich female alto in Kokoro voicebank
    "xtts": "Sofia Hellen",        # XTTS preset; override with --speaker-wav
    "f5tts": "F5TTS_v1_Base",      # F5-TTS model name; voice comes from --speaker-wav
}

# Inter-section silence padding (ms) injected between chunks for natural pacing.
SECTION_PAUSE_MS = 700
SENTENCE_PAUSE_MS = 250

SUPPORTED_FORMATS = ("mp3", "wav", "ogg")


# ═════════════════════════════════════════════════════════════════════════
# Logging
# ═════════════════════════════════════════════════════════════════════════

logger = logging.getLogger("reports_to_tts")


# ═════════════════════════════════════════════════════════════════════════
# Custom exceptions
# ═════════════════════════════════════════════════════════════════════════


class ReportToTTSError(Exception):
    """Base exception for reports_to_tts."""


class BackendUnavailableError(ReportToTTSError):
    """A required TTS backend package is not installed or not callable."""


class SynthesisError(ReportToTTSError):
    """A backend failed to synthesize a chunk."""


class AudioAssemblyError(ReportToTTSError):
    """Assembling per-chunk audio into a final file failed."""


# ═════════════════════════════════════════════════════════════════════════
# Data types
# ═════════════════════════════════════════════════════════════════════════


@dataclass(frozen=True)
class Report:
    """A single source report ready for synthesis.

    Attributes:
        path:    Absolute path to the source markdown file.
        title:   Display title (from frontmatter or H1 or filename).
        author:  Optional author string for ID3 tagging.
        text:    Cleaned plain-text body suitable for a TTS engine.
    """
    path: Path
    title: str
    author: str | None
    text: str


@dataclass(frozen=True)
class Chunk:
    """A bounded slice of report text submitted as one TTS request."""
    index: int
    text: str
    is_section_break: bool  # True = preceded by a heading; insert longer pause


@dataclass(frozen=True)
class SynthesisResult:
    """Outcome of processing one report."""
    report: Report
    output_path: Path | None
    ok: bool
    chunk_count: int
    duration_ms: int
    error: str | None = None


# ═════════════════════════════════════════════════════════════════════════
# Markdown cleaning
# ═════════════════════════════════════════════════════════════════════════


# Pre-compiled patterns. Order matters: we strip code/HTML first so they
# can't shadow later regex (e.g. a `**` inside a code block).
# Tolerates CRLF, optional BOM, and a closing `---` at EOF without trailing newline.
_FRONTMATTER_RE = re.compile(r"\A\ufeff?---\r?\n.*?\r?\n---[ \t]*(?:\r?\n|\Z)", re.DOTALL)
# Matches a heading line introducing an appendix / references / bibliography /
# footnotes / endnotes / works-cited section. Any heading level (#..######).
# We cut the body at this point so the TTS does not read citation dumps.
_APPENDIX_CUTOFF_RE = re.compile(
    r"^#{1,6}\s+(?:appendix|appendices|appendix\s+[a-z0-9]+"
    r"|references?|bibliography|works\s+cited|footnotes?|endnotes?|"
    r"further\s+reading|sources)\b.*$",
    re.IGNORECASE | re.MULTILINE,
)
_FENCED_CODE_RE = re.compile(r"```.*?```", re.DOTALL)
_INLINE_CODE_RE = re.compile(r"`[^`\n]+`")
_HTML_TAG_RE = re.compile(r"<[^>]+>")
# Obsidian callout marker on its own line: `> [!note] Title` → keep "Title" as a sentence.
_CALLOUT_HEADER_RE = re.compile(r"^>\s*\[!([a-zA-Z0-9_-]+)\][+-]?\s*(.*)$", re.MULTILINE)
# Wiki-links: [[Target|Display]] → Display ;  [[Target]] → Target
_WIKILINK_RE = re.compile(r"\[\[([^\]|]+?)(?:\|([^\]]+?))?\]\]")
# Markdown links [text](url) → text
_MDLINK_RE = re.compile(r"\[([^\]]+?)\]\(([^)]+?)\)")
# Image syntax ![alt](url)
_IMAGE_RE = re.compile(r"!\[[^\]]*\]\([^)]*\)")
# Emphasis markers — strip leaving the inner text
_EMPHASIS_RE = re.compile(r"(\*\*\*|\*\*|\*|___|__|_|~~)(.+?)\1", re.DOTALL)
# Markdown table rows (lines composed entirely of pipes/dashes/spaces)
_TABLE_DIVIDER_RE = re.compile(r"^\s*\|?[\s\-:|]+\|?\s*$", re.MULTILINE)
# Block-quote markers at line start
_BLOCKQUOTE_RE = re.compile(r"^>\s?", re.MULTILINE)
# List bullets and numbers at line start
_LIST_BULLET_RE = re.compile(r"^\s*([-*+]|\d+[.)])\s+", re.MULTILINE)
# Heading markers (#, ##, ...) at line start; we keep the text but mark a section
_HEADING_RE = re.compile(r"^(#{1,6})\s+(.+?)\s*#*\s*$", re.MULTILINE)
# Multiple consecutive blank lines → single blank line
_MULTI_BLANK_RE = re.compile(r"\n{3,}")
# Standalone horizontal rules
_HRULE_RE = re.compile(r"^\s*([-*_])\1{2,}\s*$", re.MULTILINE)

# Standalone Obsidian-style tags or stray "#word" tokens left behind after
# heading + wikilink processing. Matches "#tag", "#tag-name", "#area/sub" but
# not characters embedded in a word (e.g. "C#" stays intact because of \B).
_STRAY_HASHTAG_RE = re.compile(r"(?<!\w)#([\w][\w/_-]*)")

# Unicode glyphs that are unspeakable AND that crash Windows cp1252 stdout
# inside F5-TTS's internal `print(gen_text...)`. We map each to a sensible
# spoken / printable substitute. Add new entries here when a new symbol blows
# up encoding.
_UNICODE_SUBSTITUTIONS = {
    "\u2192": " to ",       # → rightwards arrow
    "\u2190": " from ",     # ← leftwards arrow
    "\u2194": " versus ",   # ↔ left-right arrow
    "\u21d2": " implies ",  # ⇒
    "\u21d4": " iff ",      # ⇔
    "\u00a7": "section ",  # § section sign
    "\u00b6": "",            # ¶ pilcrow
    "\u2013": "-",          # – en dash
    "\u2014": " - ",        # — em dash
    "\u2026": "...",        # … ellipsis
    "\u2018": "'",          # ' left single quote
    "\u2019": "'",          # ' right single quote
    "\u201c": '"',          # " left double quote
    "\u201d": '"',          # " right double quote
    "\u2022": "",            # • bullet
    "\u00d7": " by ",       # × multiplication sign  (e.g. "2×2 framework")
    "\u00f7": " divided by ",  # ÷
    "\u2260": " not equal to ",  # ≠
    "\u2264": " less than or equal to ",   # ≤
    "\u2265": " greater than or equal to ",  # ≥
    "\u00b1": " plus or minus ",  # ±
}


# Sentinel used internally to mark section boundaries before chunking. It is
# stripped before audio synthesis but preserved by the chunker so we know where
# to insert longer inter-section pauses.
SECTION_MARK = "@@SECTION@@"


def _extract_frontmatter(text: str) -> tuple[dict[str, str], str]:
    """Parse a minimal YAML frontmatter block.

    We do NOT pull in PyYAML — we only need top-level scalar fields (title,
    author, etc.). Anything more exotic falls through and is ignored.

    Args:
        text: Full raw markdown source.

    Returns:
        A tuple ``(fields, body)`` where ``fields`` is a string→string mapping
        and ``body`` is the markdown content after the frontmatter block.
    """
    m = _FRONTMATTER_RE.match(text)
    if not m:
        return {}, text
    block = m.group(0).strip("-\n")
    fields: dict[str, str] = {}
    for line in block.splitlines():
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        fields[key.strip().lower()] = value.strip().strip('"').strip("'")
    return fields, text[m.end():]


def _truncate_at_appendix(text: str) -> str:
    """Drop everything from the first appendix/references-style heading onward.

    Avoids spending TTS time on appendices, bibliographies, footnotes, etc.
    Matches headings like ``# Appendix``, ``## Appendix A``, ``## References``,
    ``### Bibliography``, ``# Works Cited``, ``## Footnotes``, ``# Sources``.
    """
    m = _APPENDIX_CUTOFF_RE.search(text)
    if m:
        return text[: m.start()].rstrip()
    return text


def clean_markdown(text: str) -> str:
    """Convert Obsidian-flavored markdown into clean speakable plain text.

    Pipeline (order matters):
        1. Drop fenced code blocks, inline code, raw HTML, images.
        2. Reformat Obsidian callout headers into a sentence form.
        3. Resolve wiki-links and markdown links to their visible text.
        4. Strip emphasis markers.
        5. Reduce table rows / blockquote markers / list bullets to plain lines.
        6. Convert headings to a sentinel-marked sentence.
        7. Collapse whitespace.

    Args:
        text: Raw markdown body (frontmatter already removed).

    Returns:
        Plain text with section markers (``SECTION_MARK``) where headings were.
    """
    # 1. Code / HTML / images — these MUST go first so their contents can't
    #    leak into later regex passes.
    text = _FENCED_CODE_RE.sub("", text)
    text = _INLINE_CODE_RE.sub("", text)
    text = _IMAGE_RE.sub("", text)
    text = _HTML_TAG_RE.sub("", text)

    # 2. Callout headers: "> [!important] Read this" → "Important. Read this."
    def _callout_repl(m: re.Match[str]) -> str:
        kind = m.group(1).replace("-", " ").strip().capitalize()
        rest = m.group(2).strip()
        return f"{kind}. {rest}".rstrip(". ") + "."
    text = _CALLOUT_HEADER_RE.sub(_callout_repl, text)

    # 3. Links → display text
    #    Wikilinks: prefer the display alias; otherwise use the target. Strip
    #    Obsidian section anchors (e.g. ``[[Note#Heading]]`` -> "Note, Heading"
    #    and ``[[#Heading]]`` -> "Heading") so the TTS does not say "hashtag".
    def _wiki_repl(m: re.Match[str]) -> str:
        chosen = (m.group(2) or m.group(1)).strip()
        # If no display alias, sanitise the raw target.
        if not m.group(2):
            chosen = chosen.lstrip("#")
            chosen = chosen.replace("#", ", ")
        return chosen
    text = _WIKILINK_RE.sub(_wiki_repl, text)
    text = _MDLINK_RE.sub(lambda m: m.group(1), text)

    # 4. Emphasis (run twice in case of nested **_x_**)
    for _ in range(2):
        text = _EMPHASIS_RE.sub(lambda m: m.group(2), text)

    # 5. Tables / blockquotes / lists / hrules
    text = _TABLE_DIVIDER_RE.sub("", text)
    text = _HRULE_RE.sub("", text)
    text = _BLOCKQUOTE_RE.sub("", text)
    text = _LIST_BULLET_RE.sub("", text)

    # 6. Headings → sentinel-marked sentence. We keep the heading TEXT because
    #    skipping it removes structure the listener depends on.
    def _heading_repl(m: re.Match[str]) -> str:
        title = m.group(2).strip().rstrip(".").rstrip()
        return f"\n\n{SECTION_MARK}{title}.\n\n"
    text = _HEADING_RE.sub(_heading_repl, text)

    # 6b. Strip stray "#word" tokens that survived (Obsidian tags / link
    #     anchor fragments not caught by the wikilink rule). Replace the
    #     leading "#" with nothing so "#A.1" -> "A.1", "#far-transfer" ->
    #     "far-transfer". Words like "C#" are preserved by the (?<!\w) guard.
    text = _STRAY_HASHTAG_RE.sub(lambda m: m.group(1).replace("-", " ").replace("_", " "), text)

    # 7. Whitespace normalization
    text = _MULTI_BLANK_RE.sub("\n\n", text)
    text = "\n".join(line.rstrip() for line in text.splitlines())

    # 8. Replace unspeakable Unicode glyphs with readable substitutes.
    for src, dst in _UNICODE_SUBSTITUTIONS.items():
        text = text.replace(src, dst)
    return text.strip()


def _apply_cp1252_safety(text: str) -> str:
    """Drop characters that can't encode to cp1252.

    F5-TTS on Windows calls ``print(gen_text)`` internally, which crashes on
    non-cp1252 codepoints. Apply this only when using the f5tts backend.
    """
    return text.encode("cp1252", errors="ignore").decode("cp1252")


def derive_title(fields: dict[str, str], cleaned_text: str, fallback: str) -> str:
    """Derive a display title from frontmatter, the first heading, or filename."""
    if "title" in fields and fields["title"]:
        return fields["title"]
    # First section-marked heading in the cleaned text
    for line in cleaned_text.splitlines():
        if line.startswith(SECTION_MARK):
            return line.removeprefix(SECTION_MARK).rstrip(".").strip()
    return fallback


# ═════════════════════════════════════════════════════════════════════════
# Chunking
# ═════════════════════════════════════════════════════════════════════════


_SENTENCE_SPLIT_RE = re.compile(r"(?<=[.!?])\s+(?=[A-Z\"'\u201c\u2018(])")


def chunk_text(text: str, max_chars: int) -> list[Chunk]:
    """Split cleaned text into TTS-sized chunks at safe linguistic boundaries.

    Strategy:
        - Split on section markers first (each section becomes its own chunk
          family with ``is_section_break=True`` on its first chunk).
        - Within each section, if the section exceeds ``max_chars``, sub-split
          at sentence boundaries; if a single sentence still exceeds the
          ceiling, hard-wrap at the nearest whitespace under the limit.

    Args:
        text:      Cleaned text (output of ``clean_markdown``).
        max_chars: Per-chunk character ceiling.

    Returns:
        A list of ``Chunk`` records in narration order.
    """
    if max_chars <= 0:
        raise ValueError("max_chars must be positive")

    # INVARIANT: ``sections`` preserves narration order. The leading split
    # on SECTION_MARK can produce an empty first element if the document
    # opens with a heading; we filter empties below.
    raw_sections = text.split(SECTION_MARK)
    sections = [s.strip() for s in raw_sections if s.strip()]

    chunks: list[Chunk] = []
    idx = 0
    for s_i, section in enumerate(sections):
        # Each section's first chunk is the section break (only s_i>0 actually
        # follows a heading boundary; the first section is the document opener
        # with no preceding silence).
        first_in_section = True
        for piece in _split_section(section, max_chars):
            chunks.append(Chunk(
                index=idx,
                text=piece,
                is_section_break=(first_in_section and s_i > 0),
            ))
            idx += 1
            first_in_section = False
    return chunks


def _split_section(section: str, max_chars: int) -> Iterable[str]:
    """Yield sub-strings of ``section`` each under ``max_chars``."""
    if len(section) <= max_chars:
        yield section
        return
    sentences = _SENTENCE_SPLIT_RE.split(section)
    buf: list[str] = []
    buf_len = 0
    for sent in sentences:
        if buf_len + len(sent) + 1 > max_chars and buf:
            yield " ".join(buf)
            buf, buf_len = [], 0
        if len(sent) > max_chars:
            # PERF: pathological long sentence — hard-wrap at whitespace.
            yield from _hard_wrap(sent, max_chars)
            continue
        buf.append(sent)
        buf_len += len(sent) + 1
    if buf:
        yield " ".join(buf)


def _hard_wrap(s: str, max_chars: int) -> Iterable[str]:
    """Last-resort wrap a single overlong sentence at whitespace."""
    while len(s) > max_chars:
        cut = s.rfind(" ", 0, max_chars)
        if cut == -1:
            cut = max_chars
        yield s[:cut].strip()
        s = s[cut:].strip()
    if s:
        yield s


# ═════════════════════════════════════════════════════════════════════════
# TTS backend abstraction
# ═════════════════════════════════════════════════════════════════════════


@dataclass
class BackendConfig:
    """Backend-tunable parameters surfaced via the CLI."""
    voice: str
    rate_pct: int = 0          # percentage adjust, e.g. -10 = 10% slower
    pitch_hz: int = 0          # ± Hz adjustment (edge backend)
    speaker_wav: Path | None = None  # XTTS reference clip


class TTSBackend(ABC):
    """Abstract synthesizer.

    Implementations must take a piece of text plus a destination path and
    write a playable WAV/MP3 to that path. Concatenation is handled by the
    caller, not the backend.
    """

    name: str = "abstract"

    def __init__(self, config: BackendConfig) -> None:
        self.config = config

    @abstractmethod
    def synthesize(self, text: str, dest: Path) -> None:
        """Render ``text`` to ``dest`` (a .mp3 or .wav file)."""

    def warmup(self) -> None:
        """Optional model preload hook. Default is a no-op."""


class EdgeTTSBackend(TTSBackend):
    """Microsoft Edge / Azure neural voices via the `edge-tts` package.

    Free, no API key, ~250 voices. Output is MP3.
    """
    name = "edge"

    def __init__(self, config: BackendConfig) -> None:
        super().__init__(config)
        try:
            import edge_tts  # type: ignore
        except ImportError as exc:
            raise BackendUnavailableError(
                "edge-tts not installed. Run: pip install edge-tts"
            ) from exc
        self._edge_tts = edge_tts

    def synthesize(self, text: str, dest: Path) -> None:
        rate_str = f"{self.config.rate_pct:+d}%"
        pitch_str = f"{self.config.pitch_hz:+d}Hz"
        comm = self._edge_tts.Communicate(
            text=text,
            voice=self.config.voice,
            rate=rate_str,
            pitch=pitch_str,
        )
        # edge-tts is async-only. We isolate the event loop per call so we
        # don't fight any caller-side loop policy.
        try:
            asyncio.run(comm.save(str(dest)))
        except Exception as exc:  # pragma: no cover - network / service errors
            raise SynthesisError(f"edge-tts failed: {exc}") from exc


class KokoroBackend(TTSBackend):
    """Local Kokoro-82M pipeline via the `kokoro` package.

    Runs on CPU but is dramatically faster on CUDA. Output is WAV.
    """
    name = "kokoro"

    def __init__(self, config: BackendConfig) -> None:
        super().__init__(config)
        try:
            from kokoro import KPipeline  # type: ignore
            import soundfile as sf  # type: ignore
        except ImportError as exc:
            raise BackendUnavailableError(
                "kokoro/soundfile not installed. Run: "
                "pip install kokoro soundfile"
            ) from exc
        self._sf = sf
        # NOTE: lang_code is derived from voice prefix: 'af_*' / 'am_*' = American.
        self._pipe = KPipeline(lang_code=config.voice[0] if config.voice else "a")

    def synthesize(self, text: str, dest: Path) -> None:
        # PERF: Kokoro emits a generator of audio fragments; we concatenate
        #       them in-memory. Speed is controlled by the `speed` parameter
        #       (1.0 = nominal). Map rate_pct → multiplicative factor.
        speed = max(0.5, min(2.0, 1.0 + self.config.rate_pct / 100.0))
        try:
            fragments = list(self._pipe(text, voice=self.config.voice, speed=speed))
        except Exception as exc:
            raise SynthesisError(f"kokoro failed: {exc}") from exc
        if not fragments:
            raise SynthesisError("kokoro produced no audio")
        # Each fragment yields (graphemes, phonemes, audio_tensor). Concat audio.
        import numpy as np  # local import — only needed if user picked kokoro
        audio = np.concatenate([np.asarray(frag[2]) for frag in fragments])
        self._sf.write(str(dest), audio, 24000)


class XTTSBackend(TTSBackend):
    """Coqui XTTS-v2 with optional voice cloning from a reference WAV.

    This is the path to actually approximate the husky-alto target voice:
    supply a 6-15 second reference clip via ``--speaker-wav``.
    """
    name = "xtts"

    def __init__(self, config: BackendConfig) -> None:
        super().__init__(config)
        try:
            from TTS.api import TTS  # type: ignore
        except ImportError as exc:
            raise BackendUnavailableError(
                "Coqui TTS not installed. Run: pip install TTS"
            ) from exc
        # NOTE: model download on first use; takes a moment.
        self._tts = TTS(model_name="tts_models/multilingual/multi-dataset/xtts_v2",
                        progress_bar=False)

    def synthesize(self, text: str, dest: Path) -> None:
        kwargs: dict = {"text": text, "file_path": str(dest), "language": "en"}
        if self.config.speaker_wav:
            kwargs["speaker_wav"] = str(self.config.speaker_wav)
        else:
            kwargs["speaker"] = self.config.voice
        # XTTS speed parameter: 1.0 nominal; map rate_pct.
        kwargs["speed"] = max(0.5, min(2.0, 1.0 + self.config.rate_pct / 100.0))
        try:
            self._tts.tts_to_file(**kwargs)
        except Exception as exc:
            raise SynthesisError(f"xtts failed: {exc}") from exc


class F5TTSBackend(TTSBackend):
    """F5-TTS voice-cloning backend.

    F5-TTS is a flow-matching TTS that clones a target voice from a short
    reference clip. It runs ~3-5x faster than XTTS-v2 on the same hardware
    and handles longer multi-sentence inputs gracefully via internal
    cross-fading.

    Reference text:
        F5-TTS needs a transcription of the reference clip. We auto-transcribe
        on first use via Whisper (bundled in f5-tts) and cache the result in a
        sidecar ``.txt`` next to the reference WAV. Subsequent runs reuse it.

    Args:
        config: Must include ``speaker_wav`` (path to a 6-15s reference clip).
    """
    name = "f5tts"

    def __init__(self, config: BackendConfig) -> None:
        super().__init__(config)
        if not config.speaker_wav:
            raise BackendUnavailableError(
                "f5tts backend requires --speaker-wav (reference clip)"
            )
        try:
            from f5_tts.api import F5TTS  # type: ignore
        except ImportError as exc:
            raise BackendUnavailableError(
                "f5-tts not installed. Run: pip install f5-tts"
            ) from exc
        # NOTE: model is downloaded from HF on first use; cached afterwards.
        # ``F5TTS_v1_Base`` is the default English model (~330M params).
        model_name = config.voice or "F5TTS_v1_Base"
        self._f5 = F5TTS(model=model_name)
        # Resolve / cache the reference transcription.
        self._ref_file = str(Path(config.speaker_wav).resolve())
        self._ref_text = self._load_or_transcribe_ref()

    def _load_or_transcribe_ref(self) -> str:
        """Load cached reference transcript or auto-transcribe via Whisper."""
        ref_path = Path(self._ref_file)
        sidecar = ref_path.with_suffix(".txt")
        if sidecar.exists():
            text = sidecar.read_text(encoding="utf-8").strip()
            if text:
                logger.info("Using cached reference transcript: %s", sidecar.name)
                return text
        logger.info("Auto-transcribing reference clip (one-time, ~10-20s)...")
        try:
            from f5_tts.infer.utils_infer import preprocess_ref_audio_text
            _, ref_text = preprocess_ref_audio_text(self._ref_file, "")
        except Exception as exc:
            raise SynthesisError(f"f5tts ref transcription failed: {exc}") from exc
        ref_text = ref_text.strip()
        try:
            sidecar.write_text(ref_text, encoding="utf-8")
            logger.info("Cached reference transcript → %s", sidecar.name)
        except OSError as exc:  # NOTE: non-fatal; we still have the text in memory
            logger.warning("Could not cache ref transcript: %s", exc)
        return ref_text

    def synthesize(self, text: str, dest: Path) -> None:
        speed = max(0.5, min(2.0, 1.0 + self.config.rate_pct / 100.0))
        try:
            # PERF: file_wave avoids extra in-memory round-trip; F5-TTS writes
            # the WAV directly. We then let the assembler convert format.
            self._f5.infer(
                ref_file=self._ref_file,
                ref_text=self._ref_text,
                gen_text=text,
                speed=speed,
                file_wave=str(dest),
                remove_silence=False,
                show_info=lambda *_a, **_k: None,  # suppress per-call print spam
            )
        except Exception as exc:
            raise SynthesisError(f"f5tts failed: {exc}") from exc


# DESIGN: Factory pattern — four concrete backends share one interface;
# user selects one at runtime via CLI flag, swappable without touching
# orchestration code.
def build_backend(name: str, config: BackendConfig) -> TTSBackend:
    """Instantiate the requested backend or raise ``BackendUnavailableError``."""
    name = name.lower()
    if name == "edge":
        return EdgeTTSBackend(config)
    if name == "kokoro":
        return KokoroBackend(config)
    if name == "xtts":
        return XTTSBackend(config)
    if name == "f5tts":
        return F5TTSBackend(config)
    raise BackendUnavailableError(
        f"Unknown backend {name!r}. Choose one of: edge, kokoro, xtts, f5tts."
    )


# ═════════════════════════════════════════════════════════════════════════
# Audio assembly
# ═════════════════════════════════════════════════════════════════════════


def assemble_audio(
    chunk_files: Sequence[Path],
    chunks: Sequence[Chunk],
    dest: Path,
    out_format: str,
) -> int:
    """Concatenate per-chunk audio with appropriate inter-chunk silences.

    Args:
        chunk_files: One audio file per chunk (same length / order).
        chunks:      The Chunk metadata aligned with ``chunk_files``.
        dest:        Final output file path.
        out_format:  One of SUPPORTED_FORMATS (``mp3`` | ``wav`` | ``ogg``).

    Returns:
        Total duration of the assembled audio in milliseconds.

    Raises:
        AudioAssemblyError: pydub or ffmpeg failed.
    """
    if AudioSegment is None:
        raise AudioAssemblyError(
            "pydub is not installed. Run: pip install pydub  (and ensure "
            "ffmpeg is on PATH)."
        )
    if len(chunk_files) != len(chunks):
        raise AudioAssemblyError("chunk_files / chunks length mismatch")

    try:
        combined = AudioSegment.silent(duration=0)
        for cf, ch in zip(chunk_files, chunks):
            seg = AudioSegment.from_file(cf)
            if combined.duration_seconds > 0:
                pause = SECTION_PAUSE_MS if ch.is_section_break else SENTENCE_PAUSE_MS
                combined += AudioSegment.silent(duration=pause)
            combined += seg
        dest.parent.mkdir(parents=True, exist_ok=True)
        combined.export(dest, format=out_format)
        return int(combined.duration_seconds * 1000)
    except Exception as exc:  # pragma: no cover - ffmpeg / IO failures
        raise AudioAssemblyError(f"failed to assemble audio: {exc}") from exc


def tag_mp3(path: Path, *, title: str, author: str | None) -> None:
    """Write minimal ID3 tags to an MP3 file. No-op for non-MP3 formats.

    Quietly logs and continues on tagging failure — bad tags should not
    invalidate an otherwise successful synthesis.
    """
    if path.suffix.lower() != ".mp3" or EasyID3 is None:
        return
    try:
        try:
            tags = EasyID3(path)
        except ID3NoHeaderError:
            tags = EasyID3()
            tags.save(path)
            tags = EasyID3(path)
        tags["title"] = title
        if author:
            tags["artist"] = author
        tags["genre"] = "Spoken & Audio"
        tags.save(path)
    except Exception as exc:  # pragma: no cover
        logger.warning("ID3 tagging failed for %s: %s", path.name, exc)


# ═════════════════════════════════════════════════════════════════════════
# Orchestration
# ═════════════════════════════════════════════════════════════════════════


def load_report(path: Path) -> Report:
    """Read a markdown file and produce a ready-to-synthesize ``Report``."""
    raw = path.read_text(encoding="utf-8")
    fields, body = _extract_frontmatter(raw)
    body = _truncate_at_appendix(body)
    cleaned = clean_markdown(body)
    title = derive_title(fields, cleaned, fallback=path.stem)
    author = fields.get("author") or fields.get("by")
    # Strip the section sentinel from the title we tag (it's only useful
    # internally to the chunker).
    title = title.replace(SECTION_MARK, "").strip() or path.stem
    return Report(path=path.resolve(), title=title, author=author, text=cleaned)


def discover_reports(target: Path) -> list[Path]:
    """Resolve a file or folder argument to a list of markdown paths."""
    if target.is_file():
        return [target]
    if target.is_dir():
        # NOTE: rglob walks recursively; sort for deterministic ordering.
        return sorted(p for p in target.rglob("*.md") if p.is_file())
    raise FileNotFoundError(f"Not a file or directory: {target}")


def synthesize_report(
    report: Report,
    backend: TTSBackend,
    *,
    out_dir: Path,
    out_format: str,
    chunk_chars: int,
    overwrite: bool,
    dry_run: bool,
) -> SynthesisResult:
    """Run the full per-report pipeline.

    Returns a ``SynthesisResult``; never raises for ordinary synthesis
    failures (those are recorded on the result), but DOES raise for caller-
    bug conditions like a missing output directory we can't create.
    """
    out_path = out_dir / f"{_safe_stem(report.path.stem)}.{out_format}"
    if out_path.exists() and not overwrite and not dry_run:
        logger.info("Skipping %s (exists; use --overwrite to replace)", out_path.name)
        return SynthesisResult(report, out_path, ok=True, chunk_count=0,
                               duration_ms=0, error="skipped-exists")

    chunks = chunk_text(report.text, chunk_chars)
    if not chunks:
        return SynthesisResult(report, None, ok=False, chunk_count=0,
                               duration_ms=0, error="no-content")

    logger.info("Report %r → %d chunks (~%d chars total)",
                report.title, len(chunks), len(report.text))

    if dry_run:
        for ch in chunks[:3]:
            preview = ch.text[:120].replace("\n", " ")
            logger.info("  chunk %d (break=%s): %s%s",
                        ch.index, ch.is_section_break, preview,
                        "…" if len(ch.text) > 120 else "")
        return SynthesisResult(report, out_path, ok=True,
                               chunk_count=len(chunks), duration_ms=0)

    out_dir.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="rtt_") as td:
        td_path = Path(td)
        chunk_files: list[Path] = []
        for ch in chunks:
            # Use a content-hash filename so a re-run of the same chunk text
            # is at least debug-traceable in the temp dir.
            h = hashlib.sha1(ch.text.encode("utf-8")).hexdigest()[:10]
            cf = td_path / f"{ch.index:04d}_{h}.{_chunk_format(backend)}"
            try:
                chunk_text_final = (
                    _apply_cp1252_safety(ch.text)
                    if backend.name == "f5tts" else ch.text
                )
                backend.synthesize(chunk_text_final, cf)
            except SynthesisError as exc:
                logger.error("chunk %d synthesis failed: %s", ch.index, exc)
                return SynthesisResult(report, None, ok=False,
                                       chunk_count=len(chunks), duration_ms=0,
                                       error=str(exc))
            chunk_files.append(cf)
        try:
            duration = assemble_audio(chunk_files, chunks, out_path, out_format)
        except AudioAssemblyError as exc:
            return SynthesisResult(report, None, ok=False,
                                   chunk_count=len(chunks), duration_ms=0,
                                   error=str(exc))

    tag_mp3(out_path, title=report.title, author=report.author)
    return SynthesisResult(report, out_path, ok=True,
                           chunk_count=len(chunks), duration_ms=duration)


def _chunk_format(backend: TTSBackend) -> str:
    """Per-backend natural output extension for individual chunk files."""
    if backend.name == "edge":
        return "mp3"
    return "wav"  # kokoro and xtts both write WAV natively


_INVALID_CHARS_RE = re.compile(r'[<>:"/\\|?*\x00-\x1f]')


def _safe_stem(stem: str) -> str:
    """Sanitize a filename stem for cross-platform safety."""
    cleaned = _INVALID_CHARS_RE.sub("_", stem).strip(" .")
    return cleaned or "report"


# ═════════════════════════════════════════════════════════════════════════
# CLI
# ═════════════════════════════════════════════════════════════════════════


def build_parser() -> argparse.ArgumentParser:
    """Construct the command-line argument parser."""
    parser = argparse.ArgumentParser(
        prog="reports_to_tts",
        description=(
            "Convert Obsidian-flavored academic markdown reports into spoken "
            "audio files via a pluggable TTS backend."
        ),
        allow_abbrev=False,  # prevent --output from silently matching --output-dir
        epilog=(
            "Examples:\n"
            "  reports_to_tts.py report.md\n"
            "      Single file → ./report.mp3 with default Edge voice.\n\n"
            "  reports_to_tts.py reports_dir --output-dir ./_audio\n"
            "      Whole folder → ./_audio/<basename>.mp3 each.\n\n"
            "  reports_to_tts.py reports/ --backend kokoro --voice af_bella -v\n"
            "      Local Kokoro GPU backend, alto voice, info logging.\n\n"
            "  reports_to_tts.py r.md --backend xtts --speaker-wav voice_ref.wav\n"
            "      Voice-clone the husky-alto target from a reference clip.\n\n"
            "  reports_to_tts.py reports/ --rate -10 --format wav\n"
            "      Slower delivery, WAV output instead of MP3.\n\n"
            "  reports_to_tts.py reports/ --dry-run -vv\n"
            "      Preview chunking without synthesizing audio.\n"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("input", type=Path,
                        help="A markdown file OR a directory of markdown files (recursive).")
    parser.add_argument("--output-dir", type=Path, default=None,
                        help="Where to write audio files. "
                             "Default: alongside each input report.")
    parser.add_argument("--backend", choices=("edge", "kokoro", "xtts", "f5tts"),
                        default="edge",
                        help="TTS engine to use. Default: edge. "
                             "f5tts = fast voice-cloning via F5-TTS (HF model).")
    parser.add_argument("--voice", type=str, default=None,
                        help="Backend-specific voice ID. See README. "
                             "Default: en-US-AriaNeural (edge) / af_bella (kokoro).")
    parser.add_argument("--speaker-wav", type=Path, default=None,
                        help="(xtts/f5tts) Path to a 6-15s reference clip for voice cloning. "
                             "For f5tts, a transcription is auto-generated and cached "
                             "as a sibling .txt file.")
    parser.add_argument("--rate", dest="rate_pct", type=int, default=0,
                        help="Speech rate adjustment in percent (e.g. -10 = 10%% slower). "
                             "Default: 0.")
    parser.add_argument("--pitch", dest="pitch_hz", type=int, default=0,
                        help="(edge only) Pitch adjustment in Hz. Default: 0.")
    parser.add_argument("--format", choices=SUPPORTED_FORMATS, default="mp3",
                        help="Output audio format. Default: mp3.")
    parser.add_argument("--chunk-chars", type=int, default=None,
                        help=f"Per-request character ceiling. "
                             f"Defaults: {DEFAULT_CHUNK_CHARS}.")
    parser.add_argument("--overwrite", action="store_true",
                        help="Overwrite existing output files. Default: skip them.")
    parser.add_argument("-n", "--dry-run", action="store_true",
                        help="Plan and show chunking without synthesizing audio.")
    parser.add_argument("--strict", action="store_true",
                        help="Exit non-zero if any report fails.")
    parser.add_argument("-v", "--verbose", action="count", default=0,
                        help="Increase logging verbosity (repeatable).")
    parser.add_argument("-q", "--quiet", action="store_true",
                        help="Suppress non-error output.")
    parser.add_argument("--version", action="version",
                        version=f"%(prog)s {__version__}")
    return parser


def configure_logging(verbosity: int, quiet: bool) -> None:
    """Configure root logger from CLI verbosity flags."""
    if quiet:
        level = logging.ERROR
    elif verbosity >= 2:
        level = logging.DEBUG
    elif verbosity == 1:
        level = logging.INFO
    else:
        level = logging.WARNING
    logging.basicConfig(
        level=level,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        datefmt="%H:%M:%S",
    )


def _resolve_voice(backend_name: str, override: str | None) -> str:
    return override or DEFAULT_VOICE[backend_name]


def _resolve_chunk_chars(backend_name: str, override: int | None) -> int:
    if override is not None:
        if override <= 0:
            raise ValueError("--chunk-chars must be positive")
        return override
    return DEFAULT_CHUNK_CHARS[backend_name]


def main(argv: list[str] | None = None) -> int:
    """Main entry point. Returns a process exit code."""
    parser = build_parser()
    args = parser.parse_args(argv)
    configure_logging(args.verbose, args.quiet)

    # Pre-flight: shared deps
    if not args.dry_run and AudioSegment is None:
        logger.error("pydub is required. Install with: pip install pydub")
        return 5
    if not args.dry_run and shutil.which("ffmpeg") is None:
        logger.error("ffmpeg not found on PATH. Install ffmpeg and retry.")
        return 5

    try:
        report_paths = discover_reports(args.input)
    except FileNotFoundError as exc:
        logger.error("%s", exc)
        return 2
    if not report_paths:
        logger.error("No markdown files found under %s", args.input)
        return 4

    cfg = BackendConfig(
        voice=_resolve_voice(args.backend, args.voice),
        rate_pct=args.rate_pct,
        pitch_hz=args.pitch_hz,
        speaker_wav=args.speaker_wav,
    )
    try:
        backend: TTSBackend | None = None if args.dry_run else build_backend(args.backend, cfg)
    except BackendUnavailableError as exc:
        logger.error("%s", exc)
        return 6

    try:
        chunk_chars = _resolve_chunk_chars(args.backend, args.chunk_chars)
    except ValueError as exc:
        logger.error("%s", exc)
        return 3

    if backend is not None:
        try:
            backend.warmup()
        except Exception:  # pragma: no cover
            logger.exception("backend warmup failed (continuing)")

    failures = 0
    for path in report_paths:
        try:
            report = load_report(path)
        except Exception as exc:
            logger.error("Failed to load %s: %s", path, exc)
            failures += 1
            continue

        out_dir = args.output_dir if args.output_dir else report.path.parent
        # In dry-run mode we may not have a backend; pass a sentinel.
        result = synthesize_report(
            report,
            backend if backend is not None else _DryRunBackend(cfg),
            out_dir=out_dir,
            out_format=args.format,
            chunk_chars=chunk_chars,
            overwrite=args.overwrite,
            dry_run=args.dry_run,
        )
        if result.ok:
            if result.error == "skipped-exists":
                logger.info("• %-40s [skipped]", report.title[:40])
            elif args.dry_run:
                logger.info("• %-40s [dry-run %d chunks]",
                            report.title[:40], result.chunk_count)
            else:
                logger.info("• %-40s → %s (%.1fs)",
                            report.title[:40],
                            result.output_path.name if result.output_path else "?",
                            result.duration_ms / 1000.0)
        else:
            failures += 1
            logger.error("• %-40s FAILED: %s",
                         report.title[:40], result.error)

    log_done = logger.warning if failures else logger.info
    log_done("Done. %d ok / %d failed / %d total",
             len(report_paths) - failures, failures, len(report_paths))
    if failures and args.strict:
        return 7
    return 0


class _DryRunBackend(TTSBackend):
    """Sentinel — never invoked because synthesize_report short-circuits in dry_run."""
    name = "dry-run"
    def synthesize(self, text: str, dest: Path) -> None:  # pragma: no cover
        raise RuntimeError("dry-run backend should not synthesize")


# ═════════════════════════════════════════════════════════════════════════
# Entry-point guard
# ═════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        logger.warning("Interrupted by user")
        sys.exit(130)
