#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""pipeline_v4.py — Report-JSON → condensed permanent notes via local Ollama LLM.

Reads ``_extracted.json`` files produced by ``pkb_extractor.py``, mines concept
candidates from definition/key-claim callouts, asks a local LLM
(qwen2.5-7b-instruct via Ollama by default) to condense the extracted material
into a structured permanent note, and writes one kebab-case markdown file per
concept directly into the vault's permanent-notes directory.

This is the **V4 condenser**: where V3's ``enrich_stubs.py`` operates on
*existing* stubs in the vault, V4 starts from the JSON extractor output and
*generates* atomic permanent notes per definitional concept found in a report.

Pipeline (per JSON file):
    1. Load JSON, validate shape.
    2. Mine concept candidates from extracted_items.callouts:
         - all type == 'definition'
         - optionally type == 'key-claim' (with --include-key-claims)
    3. For each candidate, build a ConceptBundle:
         - the definition body
         - same-report callouts mentioning the concept (person, example,
           open-question, tension, far-transfer, claude-insight, key-claim)
         - report frontmatter context (domain, aliases, related wiki-links)
    4. Call Ollama with structured JSON prompt → EnrichmentResponse.
    5. Render markdown using the permanent-note template structure.
    6. Resolve filename collisions according to --mode (skip|overwrite|merge).
    7. Write atomically (.tmp → replace).

Reuses v3's ``lib/llm_client.py``, ``lib/markdown.py`` (no v3 source files
modified — v3 path is added to ``sys.path`` at startup).

Usage:
    # Dry run — preview 2 concepts from a single report
    python pipeline_v4.py --report self-determination-theory --limit 2 --dry-run

    # Process all JSONs in a single batch directory
    python pipeline_v4.py --input-dir "D:/10_pur3v4d3r's-vault/999-report-organizing/_extractor-output/2026-04-21-__pur3v4d3r-house-voice-reports"

    # Full run, overwrite existing v4 notes, include key-claim callouts as concepts
    python pipeline_v4.py --mode overwrite --include-key-claims --strict

Exit codes:
    0   success
    1   uncaught error
    2   bad arguments / missing input dir
    4   no JSON inputs found / no concept candidates mined
    5   one or more conversions failed (only with --strict)
    6   Ollama unreachable
    130 interrupted (SIGINT)

Version: 1.0.0
Python:  >=3.10
Author:  Generated by Python Script Designer & Generator — Expert v1.0.0
"""
from __future__ import annotations

# ── Standard library ─────────────────────────────────────────────────────
import argparse
import datetime as dt
import json
import logging
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable

# ── sys.path injection for v3 lib reuse ──────────────────────────────────
_HERE = Path(__file__).resolve().parent
_V3_DIR = _HERE.parent / "report-extraction-to-permanent-notes-building-v3"
for _p in (_HERE, _V3_DIR):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

# ── Third-party ──────────────────────────────────────────────────────────
try:
    from rich.console import Console
    from rich.progress import (
        BarColumn,
        MofNCompleteColumn,
        Progress,
        SpinnerColumn,
        TextColumn,
        TimeElapsedColumn,
    )
    _RICH_AVAILABLE = True
except ImportError:  # pragma: no cover - optional dep
    Console = None  # type: ignore[assignment,misc]
    Progress = None  # type: ignore[assignment,misc]
    _RICH_AVAILABLE = False

try:
    from pydantic import BaseModel, Field, field_validator
    _PYDANTIC_AVAILABLE = True
except ImportError:  # pragma: no cover - optional dep
    BaseModel = object  # type: ignore[assignment,misc]
    _PYDANTIC_AVAILABLE = False

# ── v3 reused libraries ──────────────────────────────────────────────────
import config_v3  # noqa: E402
from lib.llm_client import (  # noqa: E402
    LLMError,
    OllamaClient,
    OllamaUnavailableError,
    StructuredOutputError,
)
from lib.markdown import callout, join_wikilinks, safe_filename, to_kebab  # noqa: E402

logger = logging.getLogger(__name__)

__version__ = "1.0.0"


# ════════════════════════════════════════════════════════════════════════════
# Constants
# ════════════════════════════════════════════════════════════════════════════

#: Bump when prompt contract changes semantically. Invalidates LLM cache.
PROMPT_CONTRACT_VERSION: str = "v4-condense-v2"  # bumped: added worthiness gate

#: Default destination directory for V4 condensed notes.
DEFAULT_OUTPUT_DIR: Path = (
    config_v3.VAULT_ROOT
    / "999-report-organizing"
    / "_permanent-notes"
    / "v4-llm-condensed"
)

#: Default extractor-output root scanned when --input-dir is not specified.
DEFAULT_INPUT_DIR: Path = (
    config_v3.VAULT_ROOT / "999-report-organizing" / "_extractor-output"
)

#: Callout types treated as concept candidates.
PRIMARY_CONCEPT_CALLOUTS: frozenset[str] = frozenset({"definition"})
SECONDARY_CONCEPT_CALLOUTS: frozenset[str] = frozenset({"key-claim"})

#: Callout types harvested as supporting context for any concept.
SUPPORT_CALLOUT_TYPES: frozenset[str] = frozenset({
    "definition", "key-claim", "person", "example", "open-question",
    "tension", "far-transfer", "claude-insight", "original-synthesis",
    "warning", "principle-point", "evidence", "key-distinction",
    "section-summary",
})

#: Minimum length (chars) for a concept title to be considered usable.
MIN_TITLE_LEN: int = 3
#: Maximum length for a concept title (longer = probably prose, skip).
MAX_TITLE_LEN: int = 80
#: Maximum number of supporting context callouts bundled per concept.
MAX_SUPPORT_CALLOUTS: int = 8
#: Maximum chars per supporting callout body.
MAX_SUPPORT_BODY_CHARS: int = 600

#: Statuses that mark a note already at or beyond V4 quality (skip in merge).
ENRICHED_STATUSES: frozenset[str] = frozenset({"enriched", "evergreen", "budding"})

#: Frontmatter delimiter regex for parsing existing notes.
_FM_RE = re.compile(r"^---\n(.*?)\n---\n?(.*)$", re.DOTALL)

#: Strip trailing parenthetical qualifiers from definition titles, e.g.
#: ``"Cognitive Load (Sweller, 1988)"`` → ``"Cognitive Load"``.
_TITLE_PAREN_RE = re.compile(r"\s*\([^)]+\)\s*$")
_TITLE_DASH_RE = re.compile(r"\s*[—–-]\s+.+$")  # ``"X — qualifier"`` → ``"X"``


SYSTEM_PROMPT: str = (
    "You are a careful academic knowledge-base author working from extracted "
    "source material. Your job is to condense the provided callouts and "
    "context into a single, atomic permanent note about ONE concept. Write "
    "in a neutral scholarly tone. NEVER invent citations, dates, or "
    "biographical claims that are not present in the supplied material — if "
    "uncertain, omit. Reply with valid JSON only — no markdown fences, no "
    "preamble, no commentary."
)

USER_PROMPT_TEMPLATE: str = """\
Concept: {title!r}
Source report: {report_title}
Primary domain: {domain}
Report aliases: {aliases}
Related wiki-links from report: {related_links}

Source definition (from extracted [!definition] callout):
\"\"\"
{definition_body}
\"\"\"

Supporting callouts from the same report (use as evidence — do not invent
beyond them):
{support_block}

FIRST: judge whether this concept warrants its own atomic permanent note in
a Personal Knowledge Base. A concept is WORTHY only if it meets ALL of these:
  1. It is a NAMED, TEACHABLE concept — a theory, framework, principle,
     mechanism, technique, model, or distinction with explanatory power
     beyond a single example.
  2. It is RE-USABLE across multiple contexts — not a one-off observation,
     not a single statistic, not a passing remark, not a section heading.
  3. The supplied material gives you ENOUGH SUBSTANCE to write at least a
     definition and one paragraph of core explanation that is not just a
     restatement of the title.
  4. It is NOT redundant with a more canonical concept already present in
     'related_links' or 'aliases' (e.g. an obvious synonym or sub-aspect
     of a parent concept that should own the note instead).

UNWORTHY examples to reject (worthy=false):
  - Generic verbs/nouns ("Learning", "Thinking", "Process")
  - Article/section titles masquerading as concepts
  - Author names alone (people belong in 'key_figures', not as standalone notes)
  - Single empirical findings ("60% of subjects showed X")
  - Vague phrases ("The Modern Approach", "A Better Way")
  - Concepts that are an obvious sub-case of a broader related_link

If worthy=false, set 'definition' to a single short sentence explaining what
the concept refers to (still required), set all list fields to empty arrays
[], and put the rejection reason in 'worthy_reason'. The pipeline will skip
writing the note.

Produce a JSON object with EXACTLY these fields:
{{
  "worthy": true,
  "worthy_reason": "1 short sentence justifying the worthy decision. If \
worthy=false, explain why this concept should NOT become a permanent note.",
  "definition": "1-2 sentence plain-English definition of {title!r}. \
REQUIRED. Must paraphrase or compress the source definition above; do not \
copy verbatim if it is over 50 words.",
  "core_explanation": [
    "Paragraph 1: foundational mechanism or core meaning.",
    "Paragraph 2: how it operates / is applied.",
    "Paragraph 3: nuances, sub-variants, or theoretical roots.",
    "(Optional paragraph 4: historical or empirical grounding.)"
  ],
  "practical_implications": [
    "Implication 1: a concrete consequence or application.",
    "Implication 2: a second distinct consequence.",
    "(Optional implication 3: a cautionary note or boundary condition.)"
  ],
  "key_figures": [
    "Person Name — role/contribution (only if a [!person] callout or the \
source definition explicitly attributes the work; empty array otherwise)"
  ],
  "related_concepts": [
    "Concept Name A", "Concept Name B", "Concept Name C"
  ],
  "tensions_or_questions": [
    "(Optional) A tension or open question grounded in the supplied material."
  ],
  "key_distinctions": [
    "(Optional) A common-misconception or distinction worth flagging."
  ]
}}

Hard rules:
- ALL ten keys MUST be present in your JSON response.
- "worthy" MUST be a boolean. "worthy_reason" MUST NOT be empty.
- "definition" MUST NOT be empty or null. This is the most important field.
- Array fields may be empty arrays [] but must exist as JSON arrays.
- When worthy=false, populate ONLY "worthy", "worthy_reason", and "definition";
  leave every other array empty.
- "related_concepts" entries are concept names only (not sentences).
- Do NOT include {title!r} itself in "related_concepts".
- Do NOT invent citations, years, or claims absent from the supplied material.
- Respond with a single JSON object only. No markdown fences.
"""


# ════════════════════════════════════════════════════════════════════════════
# Pydantic schema
# ════════════════════════════════════════════════════════════════════════════

if _PYDANTIC_AVAILABLE:

    class EnrichmentResponse(BaseModel):  # type: ignore[misc,valid-type]
        """Validated LLM output for one condensed permanent note."""

        worthy: bool = True
        worthy_reason: str = ""
        definition: str = Field(min_length=1)
        core_explanation: list[str] = Field(default_factory=list)
        practical_implications: list[str] = Field(default_factory=list)
        key_figures: list[str] = Field(default_factory=list)
        related_concepts: list[str] = Field(default_factory=list)
        tensions_or_questions: list[str] = Field(default_factory=list)
        key_distinctions: list[str] = Field(default_factory=list)

        @field_validator("definition")
        @classmethod
        def _def_nonblank(cls, v: str) -> str:
            v = v.strip()
            if not v:
                raise ValueError("definition must not be blank")
            return v

        @field_validator(
            "core_explanation", "practical_implications", "key_figures",
            "related_concepts", "tensions_or_questions", "key_distinctions",
            mode="before",
        )
        @classmethod
        def _coerce_list(cls, v: Any) -> list[Any]:
            if v is None:
                return []
            if isinstance(v, str):
                return [v] if v.strip() else []
            return v if isinstance(v, list) else []
else:  # pragma: no cover
    EnrichmentResponse = None  # type: ignore[assignment,misc]


# ════════════════════════════════════════════════════════════════════════════
# Data types
# ════════════════════════════════════════════════════════════════════════════

@dataclass(frozen=True)
class SourceCallout:
    """One supporting callout with the fields V4 cares about."""
    type: str
    title: str
    body: str


@dataclass(frozen=True)
class ConceptBundle:
    """Everything needed to ask the LLM to write one permanent note."""
    title: str                              # cleaned concept name
    raw_title: str                          # original callout title, untouched
    callout_type: str                       # 'definition' or 'key-claim'
    definition_body: str                    # body of the source [!definition]
    support: tuple[SourceCallout, ...]      # related same-report callouts
    domain: str                             # primary domain (kebab)
    subdomains: tuple[str, ...]
    aliases: tuple[str, ...]                # from report frontmatter
    related_links: tuple[str, ...]          # report's frontmatter + extracted wiki-links
    report_title: str                       # human-readable report title
    report_stem: str                        # filename stem for source-reports field
    confidence: str                         # report-level confidence

    @property
    def filename_stem(self) -> str:
        """Kebab-case filename stem for the rendered note."""
        return safe_filename(to_kebab(self.title)) or to_kebab(self.title)


@dataclass(frozen=True)
class ConvertResult:
    """Outcome of converting one ConceptBundle into a written note."""
    bundle: ConceptBundle
    ok: bool
    cached: bool
    written_path: Path | None
    skipped_reason: str = ""
    error: str = ""
    unworthy_reason: str = ""  # set when LLM judged worthy=false


# ════════════════════════════════════════════════════════════════════════════
# Title cleanup & concept mining
# ════════════════════════════════════════════════════════════════════════════

def _clean_title(raw: str) -> str:
    """Normalize a callout title into a concept name.

    Strips trailing parentheticals (``"X (Author, Year)"``) and ``"X — extra"``
    qualifiers. Collapses whitespace. Removes wiki-link brackets if present.
    """
    if not raw:
        return ""
    t = raw.replace("[[", "").replace("]]", "").strip()
    t = _TITLE_PAREN_RE.sub("", t)
    t = _TITLE_DASH_RE.sub("", t)
    t = re.sub(r"\s+", " ", t).strip(" .:;,")
    return t


def _is_usable_title(title: str) -> bool:
    """Return True if a title looks like a real concept name (not prose)."""
    if not (MIN_TITLE_LEN <= len(title) <= MAX_TITLE_LEN):
        return False
    # Reject titles that look like full sentences (multiple spaces + ends w/ period)
    if title.count(" ") > 8:
        return False
    return True


def mine_concepts(
    payload: dict[str, Any],
    *,
    include_key_claims: bool,
) -> list[tuple[str, dict[str, Any]]]:
    """Yield ``(callout_type, callout_dict)`` pairs that qualify as concepts.

    Deduplicates by cleaned title (case-insensitive); keeps the first occurrence,
    preferring ``definition`` callouts over ``key-claim`` callouts on collision.
    """
    callouts = (payload.get("extracted_items") or {}).get("callouts") or []
    accepted: dict[str, tuple[str, dict[str, Any]]] = {}

    def _consider(co: dict[str, Any], allowed: frozenset[str]) -> None:
        ctype = (co.get("type") or "").lower()
        if ctype not in allowed:
            return
        cleaned = _clean_title(co.get("title") or "")
        if not _is_usable_title(cleaned):
            return
        key = cleaned.lower()
        # Definition wins over key-claim on collision
        if key in accepted and accepted[key][0] == "definition":
            return
        accepted[key] = (ctype, co)

    # First pass: definitions (preferred)
    for co in callouts:
        _consider(co, PRIMARY_CONCEPT_CALLOUTS)
    # Second pass: key-claims (only if requested and no definition exists)
    if include_key_claims:
        for co in callouts:
            _consider(co, SECONDARY_CONCEPT_CALLOUTS)

    return list(accepted.values())


# ════════════════════════════════════════════════════════════════════════════
# Bundle construction
# ════════════════════════════════════════════════════════════════════════════

def _truncate(text: str, limit: int) -> str:
    text = (text or "").strip()
    if len(text) <= limit:
        return text
    return text[: limit - 1].rstrip() + "…"


def _gather_support(
    payload: dict[str, Any],
    *,
    title: str,
    skip_raw_title: str,
) -> tuple[SourceCallout, ...]:
    """Collect callouts from the same report that mention the target title.

    A callout supports a concept if either (a) its title contains the cleaned
    concept name or (b) its body mentions it as substring (case-insensitive).
    The originating callout is excluded by raw-title equality.
    """
    callouts = (payload.get("extracted_items") or {}).get("callouts") or []
    needle = title.lower()
    out: list[SourceCallout] = []
    for co in callouts:
        ctype = (co.get("type") or "").lower()
        if ctype not in SUPPORT_CALLOUT_TYPES:
            continue
        ctitle = co.get("title") or ""
        if ctitle == skip_raw_title and ctype == "definition":
            continue
        cbody = co.get("body") or ""
        haystack = (ctitle + " " + cbody).lower()
        if needle not in haystack:
            continue
        out.append(SourceCallout(
            type=ctype,
            title=ctitle.strip(),
            body=_truncate(cbody, MAX_SUPPORT_BODY_CHARS),
        ))
        if len(out) >= MAX_SUPPORT_CALLOUTS:
            break
    return tuple(out)


def _normalize_domain(raw: str | None) -> str:
    if not raw:
        return "other"
    return to_kebab(raw) or "other"


def _related_links_from_payload(payload: dict[str, Any]) -> tuple[str, ...]:
    """Pull a curated list of related wiki-link targets from the report."""
    fm = (payload.get("document_metadata") or {}).get("frontmatter") or {}
    out: list[str] = []
    for key in ("related", "see-also", "broader", "narrower", "prerequisites"):
        for v in fm.get(key) or []:
            target = str(v).strip().strip("[]").split("|", 1)[0].strip()
            if target and target not in out:
                out.append(target)
    # Add unique extracted wiki-link targets, capped
    kg = payload.get("knowledge_graph") or {}
    for t in (kg.get("unique_wiki_link_targets") or [])[:30]:
        target = str(t).strip().strip("[]").split("|", 1)[0].strip()
        if target and target not in out:
            out.append(target)
    return tuple(out[:40])


def build_bundles(
    payload: dict[str, Any],
    *,
    report_stem: str,
    include_key_claims: bool,
) -> list[ConceptBundle]:
    """Build all ConceptBundles for a single report payload."""
    fm = (payload.get("document_metadata") or {}).get("frontmatter") or {}
    domain = _normalize_domain(fm.get("primary_domain") or fm.get("domain"))
    subdomains = tuple(
        to_kebab(s) for s in (fm.get("secondary_domains") or fm.get("subdomains") or [])
        if s
    )
    aliases = tuple(str(a) for a in (fm.get("aliases") or []) if a)
    related = _related_links_from_payload(payload)
    report_title = str(fm.get("title") or report_stem)
    confidence = str(fm.get("confidence") or fm.get("evidence-quality") or "medium")

    bundles: list[ConceptBundle] = []
    for ctype, co in mine_concepts(payload, include_key_claims=include_key_claims):
        raw_title = co.get("title") or ""
        cleaned = _clean_title(raw_title)
        body = (co.get("body") or "").strip()
        support = _gather_support(payload, title=cleaned, skip_raw_title=raw_title)
        bundles.append(ConceptBundle(
            title=cleaned,
            raw_title=raw_title,
            callout_type=ctype,
            definition_body=_truncate(body, 1800),
            support=support,
            domain=domain,
            subdomains=subdomains,
            aliases=aliases,
            related_links=related,
            report_title=report_title,
            report_stem=report_stem,
            confidence=confidence,
        ))
    return bundles


# ════════════════════════════════════════════════════════════════════════════
# LLM call
# ════════════════════════════════════════════════════════════════════════════

def _build_user_prompt(b: ConceptBundle) -> str:
    """Render the user prompt from a ConceptBundle."""
    if b.support:
        support_lines = []
        for sc in b.support:
            head = f"- [{sc.type}] {sc.title}".strip()
            body = sc.body.replace("\n", " ").strip()
            if body:
                head += f": {body}"
            support_lines.append(head)
        support_block = "\n".join(support_lines)
    else:
        support_block = "(No additional supporting callouts found.)"

    return USER_PROMPT_TEMPLATE.format(
        title=b.title,
        report_title=b.report_title,
        domain=b.domain,
        aliases=", ".join(b.aliases) if b.aliases else "(none)",
        related_links=", ".join(b.related_links[:15]) if b.related_links else "(none)",
        definition_body=b.definition_body or "(no body — use only the title and supporting callouts)",
        support_block=support_block,
    )


def condense_concept(
    bundle: ConceptBundle,
    client: OllamaClient,
    *,
    model: str,
    bypass_cache: bool,
) -> tuple[Any, bool]:
    """Call the LLM for one ConceptBundle. Returns ``(response, cached)``.

    Raises:
        OllamaUnavailableError: server unreachable.
        StructuredOutputError: invalid JSON or schema violation.
        LLMError: any other LLM failure.
    """
    user_prompt = _build_user_prompt(bundle)
    rsp = client.chat_json(
        system=SYSTEM_PROMPT,
        user=user_prompt,
        schema=EnrichmentResponse if _PYDANTIC_AVAILABLE else None,
        model=model,
        cache_key_inputs=(
            PROMPT_CONTRACT_VERSION,
            model,
            bundle.title.lower(),
            bundle.report_stem,
            (bundle.definition_body or "")[:300],
        ),
        bypass_cache=bypass_cache,
    )
    return rsp.parsed, rsp.cached


# ════════════════════════════════════════════════════════════════════════════
# Markdown rendering
# ════════════════════════════════════════════════════════════════════════════

def _yaml_list(items: Iterable[str], *, quote: bool = True, wikilink: bool = False) -> str:
    """Render a list-of-strings as a YAML block sequence."""
    items = [s for s in (str(x).strip() for x in items) if s]
    if not items:
        return "  - \"\""
    out: list[str] = []
    for s in items:
        if wikilink:
            out.append(f"  - \"[[{s}]]\"")
        elif quote:
            out.append(f"  - \"{s}\"")
        else:
            out.append(f"  - {s}")
    return "\n".join(out)


def _yaml_inline_list(items: Iterable[str]) -> str:
    items = [str(x).strip() for x in items if str(x).strip()]
    if not items:
        return "[]"
    return "[" + ", ".join(items) + "]"


def _quote(s: str) -> str:
    return s.replace("\\", "\\\\").replace("\"", "\\\"")


def render_frontmatter_block(
    bundle: ConceptBundle,
    response: Any,
    *,
    today: dt.date,
) -> str:
    """Render the YAML frontmatter for the V4 condensed note."""
    title = bundle.title
    aliases = list(dict.fromkeys([title, *bundle.aliases]))[:8]
    domain = bundle.domain or "other"
    subdomains = list(bundle.subdomains)[:4]
    related = list(getattr(response, "related_concepts", None) or [])[:8]
    confidence_map = {"high": "high", "medium": "medium", "low": "low"}
    confidence = confidence_map.get(bundle.confidence.lower(), "medium")
    complexity = "advanced-practitioner"

    fm_lines = [
        "---",
        f"title: \"{_quote(title)}\"",
        "aliases:",
        _yaml_list(aliases),
        "type: permanent-note",
        "status: enriched",
        f"confidence: {confidence}",
        "",
        "tags:",
        _yaml_list([
            "permanent-note",
            "v4-llm-condensed",
            domain,
        ], quote=False),
        "",
        f"domain: {domain}",
        "subdomains:",
        _yaml_list(subdomains, quote=False) if subdomains else "  - ",
        "",
        f"created: {today.isoformat()}",
        f"updated: {today.isoformat()}",
        "",
        "source-type: report-extraction",
        "source-reports:",
        f"  - \"{_quote(bundle.report_stem)}\"",
        f"evidence-quality: {confidence}",
        "extraction-method: \"pkb-extractor-v1 → pipeline-v4-condenser\"",
        "",
        f"complexity-level: {complexity}",
        "depth-level: condensed",
        "",
        "related:",
        _yaml_list(related, wikilink=True) if related else "  - \"[[]]\"",
        "see-also:",
        "  - \"[[]]\"",
        "broader:",
        "  - \"[[]]\"",
        "narrower:",
        "  - \"[[]]\"",
        "",
        "review-frequency: quarterly",
        "mastery-stage: budding",
        "importance: medium",
        "",
        "provenance:",
        "  pipeline-version: \"v4.0.0\"",
        f"  prompt-contract: \"{PROMPT_CONTRACT_VERSION}\"",
        "---",
    ]
    return "\n".join(fm_lines)


def render_body(bundle: ConceptBundle, response: Any) -> str:
    """Render the markdown body sections from the LLM response."""
    title = bundle.title
    definition = getattr(response, "definition", "") or ""
    core = list(getattr(response, "core_explanation", None) or [])
    practical = list(getattr(response, "practical_implications", None) or [])
    figures = list(getattr(response, "key_figures", None) or [])
    related = list(getattr(response, "related_concepts", None) or [])
    tensions = list(getattr(response, "tensions_or_questions", None) or [])
    distinctions = list(getattr(response, "key_distinctions", None) or [])

    parts: list[str] = [f"# {title}", ""]

    # ── Definition callout (mandatory primary output) ────────────────────
    parts.append(callout("definition", f"**{title}**", definition.strip()))
    parts.append("")

    # ── Core Explanation ─────────────────────────────────────────────────
    if core:
        parts.append("## Core Explanation")
        parts.append("")
        for para in core:
            text = (para or "").strip()
            if text:
                parts.append(text)
                parts.append("")

    # ── Practical Implications ───────────────────────────────────────────
    if practical:
        parts.append("## Practical Implications")
        parts.append("")
        for i, imp in enumerate(practical, start=1):
            text = (imp or "").strip()
            if text:
                parts.append(callout("example", f"**Application {i}**", text))
                parts.append("")

    # ── Key Distinctions ─────────────────────────────────────────────────
    if distinctions:
        parts.append("## Key Distinctions")
        parts.append("")
        for d in distinctions:
            text = (d or "").strip()
            if text:
                parts.append(callout("warning", "**Distinction**", text))
                parts.append("")

    # ── Key Figures ──────────────────────────────────────────────────────
    if figures:
        parts.append("## Key Figures")
        parts.append("")
        for fig in figures:
            text = (fig or "").strip()
            if text:
                parts.append(f"- {text}")
        parts.append("")

    # ── Open Threads ─────────────────────────────────────────────────────
    if tensions:
        parts.append("## Open Threads")
        parts.append("")
        for q in tensions:
            text = (q or "").strip()
            if text:
                parts.append(callout("open-question", "**Question**", text))
                parts.append("")

    # ── Connections & Context ────────────────────────────────────────────
    parts.append("## Connections & Context")
    parts.append("")
    if related:
        parts.append("**Related:** " + join_wikilinks(related))
        parts.append("")
    parts.append(f"**Source:** [[{bundle.report_stem}]]")
    parts.append("")
    return "\n".join(parts).rstrip() + "\n"


def render_note(bundle: ConceptBundle, response: Any, *, today: dt.date) -> str:
    """Render the full markdown file (frontmatter + body) as a single string."""
    fm = render_frontmatter_block(bundle, response, today=today)
    body = render_body(bundle, response)
    return f"{fm}\n\n{body}"


# ════════════════════════════════════════════════════════════════════════════
# I/O layer
# ════════════════════════════════════════════════════════════════════════════

def load_payload(path: Path) -> dict[str, Any]:
    """Load and minimally validate a single _extracted.json file."""
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, dict):
        raise ValueError(f"{path.name}: top-level JSON is not an object")
    if "extracted_items" not in data:
        raise ValueError(f"{path.name}: missing extracted_items key")
    return data


def discover_jsons(
    input_dir: Path,
    *,
    report_filter: str | None,
) -> list[Path]:
    """Recursively discover ``*_extracted.json`` files under input_dir."""
    if not input_dir.exists():
        raise FileNotFoundError(f"Input dir does not exist: {input_dir}")
    paths = sorted(input_dir.rglob("*_extracted.json"))
    if report_filter:
        needle = report_filter.lower()
        paths = [p for p in paths if needle in p.stem.lower()]
    return paths


def write_atomic(path: Path, content: str) -> None:
    """Atomically write ``content`` to ``path`` via .tmp → replace."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    tmp.replace(path)


def existing_status(path: Path) -> str | None:
    """Return the ``status:`` field of an existing note, or None if absent."""
    if not path.exists():
        return None
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return None
    m = _FM_RE.match(text)
    if not m:
        return None
    fm_block = m.group(1)
    for line in fm_block.splitlines():
        if line.lower().startswith("status:"):
            return line.split(":", 1)[1].strip().strip("\"'").lower()
    return None


def resolve_destination(
    bundle: ConceptBundle,
    output_dir: Path,
    *,
    mode: str,
) -> tuple[Path, str | None]:
    """Resolve the output path and return (path, skip_reason_or_None).

    Modes:
        skip      — if file exists, return skip reason
        overwrite — write regardless (atomic replace)
        merge     — write only if existing status is not in ENRICHED_STATUSES
    """
    dest = output_dir / f"{bundle.filename_stem}.md"
    if not dest.exists():
        return dest, None
    if mode == "overwrite":
        return dest, None
    status = existing_status(dest) or ""
    if mode == "merge":
        if status in ENRICHED_STATUSES:
            return dest, f"existing status '{status}' is enriched"
        return dest, None
    # mode == 'skip'
    return dest, f"file exists (status='{status}')"


# ════════════════════════════════════════════════════════════════════════════
# Orchestration
# ════════════════════════════════════════════════════════════════════════════

def convert_one(
    bundle: ConceptBundle,
    client: OllamaClient,
    output_dir: Path,
    *,
    model: str,
    mode: str,
    dry_run: bool,
    bypass_cache: bool,
    today: dt.date,
    no_gate: bool = False,
) -> ConvertResult:
    """End-to-end conversion of one ConceptBundle into a written note."""
    dest, skip_reason = resolve_destination(bundle, output_dir, mode=mode)
    if skip_reason and not dry_run:
        return ConvertResult(
            bundle=bundle, ok=True, cached=False, written_path=None,
            skipped_reason=skip_reason,
        )
    try:
        response, cached = condense_concept(
            bundle, client, model=model, bypass_cache=bypass_cache,
        )
    except (StructuredOutputError, LLMError) as e:
        return ConvertResult(
            bundle=bundle, ok=False, cached=False, written_path=None,
            error=f"{type(e).__name__}: {e}",
        )

    # ── LLM worthiness gate ──────────────────────────────────────────────
    worthy = bool(getattr(response, "worthy", True))
    worthy_reason = str(getattr(response, "worthy_reason", "") or "").strip()
    if not worthy and not no_gate:
        return ConvertResult(
            bundle=bundle, ok=True, cached=cached, written_path=None,
            skipped_reason=f"unworthy: {worthy_reason or '(no reason given)'}",
            unworthy_reason=worthy_reason,
        )

    content = render_note(bundle, response, today=today)
    if dry_run:
        return ConvertResult(
            bundle=bundle, ok=True, cached=cached, written_path=dest,
            skipped_reason="dry-run",
        )
    try:
        write_atomic(dest, content)
    except OSError as e:
        return ConvertResult(
            bundle=bundle, ok=False, cached=cached, written_path=None,
            error=f"OSError: {e}",
        )
    return ConvertResult(
        bundle=bundle, ok=True, cached=cached, written_path=dest,
    )


def process_jsons(
    json_paths: list[Path],
    output_dir: Path,
    client: OllamaClient,
    *,
    model: str,
    mode: str,
    dry_run: bool,
    bypass_cache: bool,
    include_key_claims: bool,
    limit: int | None,
    today: dt.date,
    no_gate: bool = False,
) -> tuple[list[ConvertResult], dict[str, int]]:
    """Process a list of JSON paths sequentially, returning results + stats."""
    all_results: list[ConvertResult] = []
    stats = {
        "jsons": 0, "concepts": 0, "written": 0, "skipped": 0,
        "cached": 0, "failed": 0, "unworthy": 0,
    }

    # Mine all bundles up front so progress bar has accurate totals
    all_bundles: list[ConceptBundle] = []
    for jp in json_paths:
        stats["jsons"] += 1
        try:
            payload = load_payload(jp)
        except (OSError, json.JSONDecodeError, ValueError) as e:
            logger.warning("Skipping %s: %s", jp.name, e)
            continue
        report_stem = jp.stem.removesuffix("_extracted")
        bundles = build_bundles(
            payload, report_stem=report_stem,
            include_key_claims=include_key_claims,
        )
        all_bundles.extend(bundles)
        if limit and len(all_bundles) >= limit:
            all_bundles = all_bundles[:limit]
            break
    stats["concepts"] = len(all_bundles)

    if not all_bundles:
        return all_results, stats

    progress_ctx = _make_progress()
    with progress_ctx as progress:
        task = progress.add_task("Condensing", total=len(all_bundles))
        for bundle in all_bundles:
            try:
                result = convert_one(
                    bundle, client, output_dir,
                    model=model, mode=mode, dry_run=dry_run,
                    bypass_cache=bypass_cache, today=today,
                    no_gate=no_gate,
                )
            except KeyboardInterrupt:
                raise
            all_results.append(result)
            if result.ok:
                if result.unworthy_reason and not no_gate:
                    stats["unworthy"] += 1
                elif result.skipped_reason and result.skipped_reason != "dry-run":
                    stats["skipped"] += 1
                elif result.written_path is not None:
                    stats["written"] += 1
                if result.cached:
                    stats["cached"] += 1
            else:
                stats["failed"] += 1
                logger.warning(
                    "Failed: %s — %s", bundle.title, result.error,
                )
            progress.update(task, advance=1, description=f"Condensing — {bundle.title[:40]}")
    return all_results, stats


# ════════════════════════════════════════════════════════════════════════════
# UI helpers
# ════════════════════════════════════════════════════════════════════════════

def _make_progress():  # noqa: ANN202
    """Return a Rich ``Progress`` context manager, or a no-op fallback."""
    if _RICH_AVAILABLE:
        return Progress(
            SpinnerColumn(),
            TextColumn("[progress.description]{task.description}"),
            BarColumn(),
            MofNCompleteColumn(),
            TimeElapsedColumn(),
            transient=False,
        )
    # Fallback: minimal no-op Progress
    class _NoopTask:
        def update(self, *a, **kw):  # noqa: ANN001,ANN002,ANN003
            pass

    class _NoopProgress:
        def __enter__(self):
            return self

        def __exit__(self, *a, **kw):  # noqa: ANN001,ANN002,ANN003
            return False

        def add_task(self, description, total=None):  # noqa: ANN001
            return 0

        def update(self, *a, **kw):  # noqa: ANN001,ANN002,ANN003
            pass

    return _NoopProgress()


# ════════════════════════════════════════════════════════════════════════════
# CLI
# ════════════════════════════════════════════════════════════════════════════

def build_parser() -> argparse.ArgumentParser:
    """Construct the V4 CLI parser."""
    parser = argparse.ArgumentParser(
        prog="pipeline_v4",
        description=(
            "V4 Condenser: Report-JSON → atomic permanent notes via local LLM."
        ),
        epilog=(
            "Examples:\n"
            "  pipeline_v4.py --dry-run --limit 2\n"
            "      Preview the first 2 concepts without writing.\n\n"
            "  pipeline_v4.py --report self-determination-theory\n"
            "      Process every JSON whose stem matches that substring.\n\n"
            "  pipeline_v4.py --input-dir D:/.../2026-04-21-batch --mode overwrite\n"
            "      Reprocess a batch in-place, replacing existing v4 notes.\n\n"
            "  pipeline_v4.py --include-key-claims --strict\n"
            "      Include [!key-claim] callouts as concepts; fail on any error.\n"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--version", action="version", version=f"%(prog)s {__version__}")
    parser.add_argument(
        "--input-dir", type=Path, default=DEFAULT_INPUT_DIR,
        help=f"Directory to scan recursively for *_extracted.json (default: {DEFAULT_INPUT_DIR})",
    )
    parser.add_argument(
        "--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR,
        help=f"Destination for condensed notes (default: {DEFAULT_OUTPUT_DIR})",
    )
    parser.add_argument(
        "--report", type=str, default=None,
        help="Substring filter on JSON filename stem (case-insensitive).",
    )
    parser.add_argument(
        "--limit", type=int, default=None,
        help="Process only the first N concept candidates across all matched JSONs.",
    )
    parser.add_argument(
        "--include-key-claims", action="store_true",
        help="Treat [!key-claim] callouts as concept candidates (in addition to [!definition]).",
    )
    parser.add_argument(
        "--mode", choices=("skip", "overwrite", "merge"), default="skip",
        help="What to do when an output file already exists (default: skip).",
    )
    parser.add_argument(
        "-n", "--dry-run", action="store_true",
        help="Run LLM calls (and cache them) but write no files.",
    )
    parser.add_argument(
        "--bypass-cache", action="store_true",
        help="Force live LLM calls; ignore cached responses.",
    )
    parser.add_argument(
        "--model", type=str, default=config_v3.LLM_MODEL_SYNTHESIZE,
        help=f"Ollama model identifier (default: {config_v3.LLM_MODEL_SYNTHESIZE}).",
    )
    parser.add_argument(
        "--strict", action="store_true",
        help="Exit non-zero if any concept fails to convert.",
    )
    parser.add_argument(
        "--no-gate", action="store_true",
        help="Disable the LLM worthiness judgment; write a note for EVERY concept.",
    )
    parser.add_argument(
        "-v", "--verbose", action="count", default=0,
        help="Increase logging verbosity (-v INFO, -vv DEBUG).",
    )
    parser.add_argument(
        "-q", "--quiet", action="store_true",
        help="Suppress non-error output.",
    )
    return parser


def configure_logging(verbosity: int, quiet: bool) -> None:
    """Configure root logger based on verbosity flags."""
    if quiet:
        level = logging.ERROR
    elif verbosity >= 2:
        level = logging.DEBUG
    elif verbosity == 1:
        level = logging.INFO
    else:
        level = logging.WARNING
    logging.basicConfig(
        level=level,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        datefmt="%H:%M:%S",
    )


def _print_summary(results: list[ConvertResult], stats: dict[str, int]) -> None:
    """Emit a human-readable summary of the run."""
    if _RICH_AVAILABLE:
        c = Console()
        c.rule("[bold cyan]V4 Condenser — Summary")
        c.print(
            f"JSONs scanned : [bold]{stats['jsons']}[/]   "
            f"Concepts mined: [bold]{stats['concepts']}[/]"
        )
        c.print(
            f"Written       : [green]{stats['written']}[/]   "
            f"Skipped       : [yellow]{stats['skipped']}[/]   "
            f"Unworthy      : [magenta]{stats.get('unworthy', 0)}[/]   "
            f"Cached hits   : [cyan]{stats['cached']}[/]   "
            f"Failed        : [red]{stats['failed']}[/]"
        )
        if stats.get("unworthy", 0):
            c.print("\n[magenta]Rejected as unworthy (no note written):[/]")
            for r in results:
                if r.unworthy_reason:
                    c.print(f"  • {r.bundle.title}: {r.unworthy_reason}")
        if stats["failed"]:
            c.print("\n[red]Failures:[/]")
            for r in results:
                if not r.ok:
                    c.print(f"  • {r.bundle.title}: {r.error}")
    else:  # pragma: no cover
        print("=" * 64)
        print(
            f"JSONs={stats['jsons']} concepts={stats['concepts']} "
            f"written={stats['written']} skipped={stats['skipped']} "
            f"unworthy={stats.get('unworthy', 0)} "
            f"cached={stats['cached']} failed={stats['failed']}"
        )
        for r in results:
            if not r.ok:
                print(f"  FAIL  {r.bundle.title}: {r.error}")


def main(argv: list[str] | None = None) -> int:
    """Main entry point."""
    parser = build_parser()
    args = parser.parse_args(argv)
    configure_logging(args.verbose, args.quiet)

    if not _PYDANTIC_AVAILABLE:
        logger.warning(
            "pydantic not installed — schema validation disabled. "
            "Install with: pip install pydantic"
        )

    try:
        json_paths = discover_jsons(args.input_dir, report_filter=args.report)
    except FileNotFoundError as e:
        logger.error("%s", e)
        return 2
    if not json_paths:
        logger.error("No *_extracted.json files matched under %s", args.input_dir)
        return 4
    logger.info("Discovered %d JSON file(s)", len(json_paths))

    config_v3.LLM_CACHE_DIR.mkdir(parents=True, exist_ok=True)
    today = dt.date.today()

    try:
        with OllamaClient(
            model=args.model,
            url=config_v3.OLLAMA_URL,
            cache_dir=config_v3.LLM_CACHE_DIR,
            timeout_s=config_v3.LLM_REQUEST_TIMEOUT_S,
            max_retries=config_v3.LLM_MAX_RETRIES,
        ) as client:
            try:
                results, stats = process_jsons(
                    json_paths,
                    args.output_dir,
                    client,
                    model=args.model,
                    mode=args.mode,
                    dry_run=args.dry_run,
                    bypass_cache=args.bypass_cache,
                    include_key_claims=args.include_key_claims,
                    limit=args.limit,
                    today=today,
                    no_gate=args.no_gate,
                )
            except OllamaUnavailableError as e:
                logger.error("Ollama unreachable: %s", e)
                return 6
    except OllamaUnavailableError as e:
        logger.error("Ollama unreachable on startup: %s", e)
        return 6
    except KeyboardInterrupt:
        logger.warning("Interrupted by user")
        return 130

    if stats["concepts"] == 0:
        logger.error(
            "No concept candidates mined. Try --include-key-claims, or check "
            "that the JSON files contain [!definition] callouts."
        )
        return 4

    _print_summary(results, stats)

    if args.strict and stats["failed"] > 0:
        return 5
    return 0


# ═════════════════════════════════════════════════════════════════════════
# Entry-point guard
# ═════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    sys.exit(main())
