#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""expand_term_list.py — Term-list batch driver for the synthetic seed workflow.

Converts a single Markdown term list into a batch of YAML briefs (one per term),
then drives ``synth_seed_builder.py`` to materialize each brief as a synthetic
``*_extracted.json`` seed ready for V6 elaboration.

Pipeline position:

    term-list.md
      -> expand_term_list.py expand        (Markdown -> briefs + manifest)
        -> expand_term_list.py build-batch (manifest -> seeds + validation)
          -> pipeline_v6.py                (seeds -> permanent notes)

Subcommands:
    expand       Parse a term-list Markdown file, dedup against existing
                 permanent notes, write one YAML brief per accepted term, and
                 emit a manifest.json describing the batch.
    build-batch  Read a manifest.json and run synth_seed_builder.build for
                 each brief, producing *_extracted.json files.
    run          Convenience: expand + build-batch in a single invocation.

Usage:
    python expand_term_list.py -v expand term-lists/2026-04-24-cluster.md
    python expand_term_list.py -v build-batch briefs/2026-04-24-cluster/manifest.json
    python expand_term_list.py -v run term-lists/2026-04-24-cluster.md

Version:
    1.0.0

Python:
    >=3.10

Dependencies:
    - pyyaml
    - synth_seed_builder (sibling module)

Author:
    Generated by Python Script Designer & Generator -- Expert v1.0.0
"""
from __future__ import annotations

# --- Standard library ---------------------------------------------------
import argparse
import dataclasses
import json
import logging
import re
import subprocess
import sys
from dataclasses import dataclass, field
from datetime import date as _date
from pathlib import Path
from typing import Any, Iterable, Sequence

# --- Third-party --------------------------------------------------------
try:
    import yaml
except ImportError as _exc:  # pragma: no cover
    print(
        "ERROR: PyYAML is required. Install it with:  pip install pyyaml",
        file=sys.stderr,
    )
    raise SystemExit(1) from _exc

# --- Local --------------------------------------------------------------
_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))
import synth_seed_builder as ssb  # noqa: E402  (after sys.path insert)


# ========================================================================
# Constants
# ========================================================================

__version__ = "1.0.0"

# Default home for finished permanent notes (mirrors pipeline_v6.py default).
DEFAULT_PERMANENT_NOTES_DIR: Path = (
    _HERE.parent.parent
    / "999-report-organizing"
    / "_permanent-notes"
    / "v6-llm-elaborated"
)

# Default output roots (siblings of this script).
DEFAULT_BRIEFS_ROOT: Path = _HERE / "briefs"
DEFAULT_SEEDS_ROOT: Path = (
    _HERE.parent.parent
    / "999-report-organizing"
    / "_extractor-output"
    / "_synthetic-seeds"
)
DEFAULT_TERM_LISTS_DIR: Path = _HERE / "term-lists"

# Path to the seed builder script (used by build-batch via subprocess).
SEED_BUILDER_SCRIPT: Path = _HERE / "synth_seed_builder.py"

# Confidence enum (must match the schema).
ALLOWED_CONFIDENCE: frozenset[str] = frozenset({"low", "medium", "high"})
DEFAULT_CONFIDENCE: str = "medium"

# Markdown parsing regexes.
_FRONTMATTER_RE = re.compile(r"\A---\s*\n(.*?)\n---\s*\n", re.DOTALL)
_H2_HEADING_RE = re.compile(r"^##\s+(?P<title>.+?)\s*$", re.MULTILINE)
_BULLET_FIELD_RE = re.compile(
    r"^\s*[-*]\s+(?:\*\*)?(?P<key>[a-z_]+)(?:\*\*)?\s*:\s*(?P<value>.*?)\s*$",
    re.MULTILINE,
)
_BOLD_FIELD_RE = re.compile(
    r"^\*\*(?P<key>definition|key_claim|warning)\*\*\s*:\s*(?P<value>.+?)"
    r"(?=\n\s*\n|\n\*\*[a-z_]+\*\*:|\n##\s+|\Z)",
    re.MULTILINE | re.DOTALL,
)
_INLINE_LIST_RE = re.compile(r"^\[(.*)\]$")

# Per-term link-slot fields (carried verbatim into the brief).
LIST_SLOT_FIELDS: tuple[str, ...] = (
    "secondary_domains",
    "aliases",
    "broader",
    "narrower",
    "related",
    "prerequisites",
)


# ========================================================================
# Logging
# ========================================================================

logger = logging.getLogger("expand_term_list")


# ========================================================================
# Custom exceptions
# ========================================================================


class ExpandError(Exception):
    """Base class for expand_term_list errors."""


class TermListParseError(ExpandError):
    """Raised when a term-list Markdown file cannot be parsed."""


class ManifestError(ExpandError):
    """Raised when a manifest is missing, malformed, or stale."""


class DedupGateError(ExpandError):
    """Raised when the dedup gate cannot be evaluated (e.g. dir missing)."""


# ========================================================================
# Data types
# ========================================================================


@dataclass
class ParsedTerm:
    """One H2 section parsed from the term list."""

    term: str
    domain: str
    secondary_domains: list[str] = field(default_factory=list)
    aliases: list[str] = field(default_factory=list)
    broader: list[str] = field(default_factory=list)
    narrower: list[str] = field(default_factory=list)
    related: list[str] = field(default_factory=list)
    prerequisites: list[str] = field(default_factory=list)
    confidence: str = DEFAULT_CONFIDENCE
    definition: str = ""
    key_claim: str = ""
    warning: str = ""
    line_no: int = 0  # 1-based line where the H2 starts (for diagnostics)


@dataclass
class TermListBatch:
    """Parsed batch: frontmatter + parsed terms."""

    batch_name: str
    batch_date: str  # ISO YYYY-MM-DD
    default_domain: str | None
    default_confidence: str
    notes: str
    terms: list[ParsedTerm]
    source_path: Path


@dataclass
class DedupDecision:
    """Result of the dedup-gate evaluation for a single term."""

    term: str
    kebab: str
    note_path: Path
    exists: bool
    decision: str  # "accept" | "skip"
    reason: str


@dataclass
class ManifestEntry:
    """One row in the manifest: a brief that build-batch should materialize."""

    term: str
    kebab: str
    brief_path: str
    expected_seed_filename: str


# ========================================================================
# Helpers
# ========================================================================


def _parse_inline_list(raw: str) -> list[str]:
    """Parse a YAML-style or comma-separated inline list.

    ``"[a, b]"`` -> ``["a", "b"]``
    ``"a, b"``   -> ``["a", "b"]``
    ``""``       -> ``[]``
    """
    raw = raw.strip()
    if not raw:
        return []
    m = _INLINE_LIST_RE.match(raw)
    inner = m.group(1) if m else raw
    parts = [p.strip().strip("'\"") for p in inner.split(",")]
    # Strip wiki-link brackets if present.
    cleaned = []
    for p in parts:
        if not p:
            continue
        p = ssb.strip_brackets(p)
        cleaned.append(p)
    return cleaned


def _parse_frontmatter(text: str) -> tuple[dict[str, Any], str]:
    """Split YAML frontmatter from the body. Returns (fm_dict, body)."""
    m = _FRONTMATTER_RE.match(text)
    if not m:
        raise TermListParseError(
            "term list missing required YAML frontmatter "
            "(must start with '---' on line 1)"
        )
    try:
        fm = yaml.safe_load(m.group(1)) or {}
    except yaml.YAMLError as exc:
        raise TermListParseError(f"frontmatter is not valid YAML: {exc}") from exc
    if not isinstance(fm, dict):
        raise TermListParseError("frontmatter must be a YAML mapping")
    body = text[m.end():]
    return fm, body


def _split_term_sections(body: str) -> list[tuple[str, int, str]]:
    """Split the body into ``(title, line_no, section_text)`` per H2."""
    sections: list[tuple[str, int, str]] = []
    matches = list(_H2_HEADING_RE.finditer(body))
    for i, m in enumerate(matches):
        title = m.group("title").strip()
        # Compute 1-based line number of the heading.
        line_no = body[: m.start()].count("\n") + 1
        start = m.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(body)
        sections.append((title, line_no, body[start:end]))
    return sections


def _parse_term_section(title: str, line_no: int, section: str) -> dict[str, Any]:
    """Parse a single H2 section into a raw dict of fields."""
    out: dict[str, Any] = {"term": title.strip(), "line_no": line_no}

    # Bullet fields (kebab/scalar settings).
    for m in _BULLET_FIELD_RE.finditer(section):
        key = m.group("key")
        val = m.group("value").strip()
        if key in LIST_SLOT_FIELDS:
            out[key] = _parse_inline_list(val)
        elif key == "domain":
            out["domain"] = ssb.to_kebab(val)
        elif key == "confidence":
            out["confidence"] = val.lower()
        else:
            # Unknown bullet keys are preserved but ignored downstream.
            out.setdefault("_extra", {})[key] = val

    # Bold fields (multi-line prose).
    for m in _BOLD_FIELD_RE.finditer(section):
        key = m.group("key")
        # Take only the first paragraph (collapse internal whitespace).
        val = m.group("value").strip()
        # Stop at the first blank line within the captured value.
        first_para = val.split("\n\n", 1)[0]
        out[key] = re.sub(r"\s+", " ", first_para).strip()

    return out


def parse_term_list(path: Path) -> TermListBatch:
    """Parse a term-list Markdown file into a TermListBatch.

    Raises:
        TermListParseError: on malformed input.
        FileNotFoundError: if the file does not exist.
    """
    if not path.exists():
        raise FileNotFoundError(path)
    text = path.read_text(encoding="utf-8")
    fm, body = _parse_frontmatter(text)

    batch_name = fm.get("batch_name")
    if not isinstance(batch_name, str) or not batch_name:
        raise TermListParseError("frontmatter missing 'batch_name'")
    if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", batch_name):
        raise TermListParseError(
            f"'batch_name' must be kebab-case, got: {batch_name!r}"
        )

    raw_date = fm.get("batch_date")
    if isinstance(raw_date, _date):
        batch_date = raw_date.isoformat()
    elif isinstance(raw_date, str) and re.fullmatch(r"\d{4}-\d{2}-\d{2}", raw_date):
        batch_date = raw_date
    else:
        raise TermListParseError(
            "frontmatter 'batch_date' must be an ISO date (YYYY-MM-DD)"
        )

    default_domain = fm.get("default_domain")
    if default_domain is not None and not isinstance(default_domain, str):
        raise TermListParseError("'default_domain' must be a string if set")
    if default_domain:
        default_domain = ssb.to_kebab(default_domain)

    default_confidence = (fm.get("default_confidence") or DEFAULT_CONFIDENCE).lower()
    if default_confidence not in ALLOWED_CONFIDENCE:
        raise TermListParseError(
            f"'default_confidence' must be one of {sorted(ALLOWED_CONFIDENCE)}"
        )

    notes = str(fm.get("notes") or "").strip()

    sections = _split_term_sections(body)
    if not sections:
        raise TermListParseError("term list contains no H2 term sections")

    parsed_terms: list[ParsedTerm] = []
    seen_kebabs: set[str] = set()
    for title, line_no, section_text in sections:
        raw = _parse_term_section(title, line_no, section_text)
        domain = raw.get("domain") or default_domain
        if not domain:
            raise TermListParseError(
                f"term '{title}' (line {line_no}) has no 'domain' and no "
                "'default_domain' was set in frontmatter"
            )
        confidence = raw.get("confidence", default_confidence)
        if confidence not in ALLOWED_CONFIDENCE:
            raise TermListParseError(
                f"term '{title}' (line {line_no}) has invalid confidence "
                f"{confidence!r}; expected one of {sorted(ALLOWED_CONFIDENCE)}"
            )
        if not raw.get("definition"):
            raise TermListParseError(
                f"term '{title}' (line {line_no}) missing required "
                "'**definition**:' field"
            )
        kebab = ssb.to_kebab(title)
        if kebab in seen_kebabs:
            raise TermListParseError(
                f"duplicate term '{title}' (line {line_no}) — kebab '{kebab}' "
                "already declared earlier in the list"
            )
        seen_kebabs.add(kebab)

        parsed_terms.append(
            ParsedTerm(
                term=ssb.clean_title(title),
                domain=domain,
                secondary_domains=raw.get("secondary_domains", []),
                aliases=raw.get("aliases", []),
                broader=raw.get("broader", []),
                narrower=raw.get("narrower", []),
                related=raw.get("related", []),
                prerequisites=raw.get("prerequisites", []),
                confidence=confidence,
                definition=raw.get("definition", ""),
                key_claim=raw.get("key_claim", ""),
                warning=raw.get("warning", ""),
                line_no=line_no,
            )
        )

    return TermListBatch(
        batch_name=batch_name,
        batch_date=batch_date,
        default_domain=default_domain,
        default_confidence=default_confidence,
        notes=notes,
        terms=parsed_terms,
        source_path=path.resolve(),
    )


# ========================================================================
# Dedup gate
# ========================================================================


def evaluate_dedup(
    terms: Iterable[ParsedTerm],
    *,
    permanent_notes_dir: Path,
    overwrite_existing: bool = False,
) -> list[DedupDecision]:
    """Decide for each term whether to accept or skip based on existing notes.

    Mirrors V6's collision check: the kebab-cased term is compared against
    files matching ``<kebab>.md`` in ``permanent_notes_dir``.

    Args:
        terms: Iterable of parsed terms.
        permanent_notes_dir: Directory holding finished permanent notes.
        overwrite_existing: When True, accept even if a note already exists.

    Returns:
        One DedupDecision per term, in input order.

    Raises:
        DedupGateError: if ``permanent_notes_dir`` does not exist.
    """
    if not permanent_notes_dir.exists():
        raise DedupGateError(
            f"permanent-notes directory not found: {permanent_notes_dir}"
        )
    decisions: list[DedupDecision] = []
    for t in terms:
        kebab = ssb.to_kebab(t.term)
        note_path = permanent_notes_dir / f"{kebab}.md"
        exists = note_path.exists()
        if exists and not overwrite_existing:
            decisions.append(
                DedupDecision(
                    term=t.term,
                    kebab=kebab,
                    note_path=note_path,
                    exists=True,
                    decision="skip",
                    reason=f"permanent note already exists at {note_path.name}",
                )
            )
        elif exists and overwrite_existing:
            decisions.append(
                DedupDecision(
                    term=t.term,
                    kebab=kebab,
                    note_path=note_path,
                    exists=True,
                    decision="accept",
                    reason="overwrite-existing flag set",
                )
            )
        else:
            decisions.append(
                DedupDecision(
                    term=t.term,
                    kebab=kebab,
                    note_path=note_path,
                    exists=False,
                    decision="accept",
                    reason="no existing permanent note",
                )
            )
    return decisions


# ========================================================================
# Brief construction
# ========================================================================


def _term_to_brief_dict(term: ParsedTerm) -> dict[str, Any]:
    """Build the YAML-brief dict for one term.

    Each callout is constructed so that the term name appears in the title,
    satisfying V4's substring-discipline rule by construction.
    """
    name = term.term
    callouts: list[dict[str, str]] = [
        {
            "type": "definition",
            "title": name,
            "body": term.definition,
        }
    ]
    if term.key_claim:
        callouts.append({
            "type": "key-claim",
            "title": f"Key claim about {name}",
            "body": term.key_claim,
        })
    if term.warning:
        callouts.append({
            "type": "warning",
            "title": f"Common pitfall regarding {name}",
            "body": term.warning,
        })

    brief: dict[str, Any] = {
        "concept": name,
        "domain": term.domain,
        "secondary_domains": term.secondary_domains,
        "aliases": term.aliases,
        "broader": term.broader,
        "narrower": term.narrower,
        "related": term.related,
        "prerequisites": term.prerequisites,
        "confidence": term.confidence,
        "callouts": callouts,
    }
    # Strip empty optional collections to keep the brief tidy.
    for k in (
        "secondary_domains",
        "aliases",
        "broader",
        "narrower",
        "related",
        "prerequisites",
    ):
        if not brief[k]:
            brief.pop(k)
    return brief


def write_brief(
    term: ParsedTerm,
    *,
    briefs_dir: Path,
    overwrite: bool,
) -> Path:
    """Serialize a term's brief to YAML in ``briefs_dir``."""
    briefs_dir.mkdir(parents=True, exist_ok=True)
    brief_path = briefs_dir / f"{ssb.to_kebab(term.term)}.yaml"
    if brief_path.exists() and not overwrite:
        raise FileExistsError(brief_path)
    payload = _term_to_brief_dict(term)
    text = yaml.safe_dump(payload, sort_keys=False, allow_unicode=True)
    tmp = brief_path.with_suffix(brief_path.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(brief_path)
    return brief_path


# ========================================================================
# Manifest I/O
# ========================================================================


def write_manifest(
    batch: TermListBatch,
    *,
    accepted: list[tuple[ParsedTerm, Path, DedupDecision]],
    skipped: list[DedupDecision],
    warnings: list[str],
    briefs_dir: Path,
    seeds_dir: Path,
) -> Path:
    """Write the manifest.json describing this batch."""
    briefs_dir.mkdir(parents=True, exist_ok=True)
    manifest_path = briefs_dir / "manifest.json"
    batch_date_obj = _date.fromisoformat(batch.batch_date)

    def _rel(p: Path) -> str:
        try:
            return str(p.resolve().relative_to(_HERE)).replace("\\", "/")
        except ValueError:
            return str(p.resolve()).replace("\\", "/")

    entries = [
        ManifestEntry(
            term=t.term,
            kebab=ssb.to_kebab(t.term),
            brief_path=_rel(brief),
            expected_seed_filename=ssb.filename_for(
                {"concept": t.term}, batch_date=batch_date_obj,
            ),
        )
        for (t, brief, _decision) in accepted
    ]
    payload: dict[str, Any] = {
        "manifest_version": "1.0.0",
        "expand_term_list_version": __version__,
        "batch": {
            "name": batch.batch_name,
            "date": batch.batch_date,
            "source_term_list": str(batch.source_path).replace("\\", "/"),
            "notes": batch.notes,
        },
        "paths": {
            "briefs_dir": str(briefs_dir.resolve()).replace("\\", "/"),
            "seeds_dir": str(seeds_dir.resolve()).replace("\\", "/"),
        },
        "counts": {
            "parsed": len(accepted) + len(skipped),
            "accepted": len(accepted),
            "skipped": len(skipped),
            "warnings": len(warnings),
        },
        "entries": [dataclasses.asdict(e) for e in entries],
        "skipped": [dataclasses.asdict(d) for d in skipped],
        "warnings": warnings,
    }
    # Path objects need to be stringified for json.dumps.
    for d in payload["skipped"]:
        d["note_path"] = str(d["note_path"]).replace("\\", "/")
    tmp = manifest_path.with_suffix(manifest_path.suffix + ".tmp")
    tmp.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    tmp.replace(manifest_path)
    return manifest_path


def load_manifest(path: Path) -> dict[str, Any]:
    """Load and minimally validate a manifest.json file."""
    if not path.exists():
        raise ManifestError(f"manifest not found: {path}")
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ManifestError(f"manifest is not valid JSON: {exc}") from exc
    for required in ("manifest_version", "batch", "paths", "entries"):
        if required not in data:
            raise ManifestError(f"manifest missing required key: {required!r}")
    return data


# ========================================================================
# Subcommand: expand
# ========================================================================


def cmd_expand(args: argparse.Namespace) -> int:
    """Parse a term list, run dedup, write briefs + manifest."""
    list_path = Path(args.list_path).resolve()
    batch = parse_term_list(list_path)
    logger.info(
        "Parsed %d term(s) from %s (batch=%s, date=%s)",
        len(batch.terms), list_path.name, batch.batch_name, batch.batch_date,
    )

    permanent_dir = Path(args.permanent_notes_dir).resolve()
    decisions = evaluate_dedup(
        batch.terms,
        permanent_notes_dir=permanent_dir,
        overwrite_existing=args.overwrite_existing,
    )
    accepted_decisions = [d for d in decisions if d.decision == "accept"]
    skipped_decisions = [d for d in decisions if d.decision == "skip"]
    accepted_terms = [
        t for t, d in zip(batch.terms, decisions) if d.decision == "accept"
    ]
    logger.info(
        "Dedup: %d accepted, %d skipped (existing notes)",
        len(accepted_decisions), len(skipped_decisions),
    )
    for d in skipped_decisions:
        logger.info("  SKIP %s -> %s", d.term, d.reason)

    briefs_dir = Path(args.briefs_dir).resolve() / batch.batch_name
    seeds_dir = (
        Path(args.seeds_dir).resolve() / f"{batch.batch_date}-{batch.batch_name}"
    )

    if args.dry_run:
        logger.info("[dry-run] Would write %d brief(s) to %s",
                    len(accepted_terms), briefs_dir)
        logger.info("[dry-run] Would target seeds dir %s", seeds_dir)
        for t in accepted_terms:
            logger.info("[dry-run]   brief: %s.yaml", ssb.to_kebab(t.term))
        return 0

    warnings: list[str] = []
    accepted_with_paths: list[tuple[ParsedTerm, Path, DedupDecision]] = []
    for term, decision in zip(batch.terms, decisions):
        if decision.decision != "accept":
            continue
        if not term.key_claim:
            warnings.append(
                f"{term.term}: no 'key_claim' supplied — seed will have only "
                "definition + warning callouts"
            )
        if not term.warning:
            warnings.append(
                f"{term.term}: no 'warning' supplied — seed will have only "
                "definition + key_claim callouts"
            )
        try:
            brief_path = write_brief(
                term, briefs_dir=briefs_dir, overwrite=args.overwrite_briefs,
            )
        except FileExistsError as exc:
            logger.error(
                "Brief already exists: %s (use --overwrite-briefs to replace)",
                exc,
            )
            return 4
        logger.info("Wrote brief: %s", brief_path)
        accepted_with_paths.append((term, brief_path, decision))

    manifest_path = write_manifest(
        batch,
        accepted=accepted_with_paths,
        skipped=skipped_decisions,
        warnings=warnings,
        briefs_dir=briefs_dir,
        seeds_dir=seeds_dir,
    )
    logger.info("Manifest written: %s", manifest_path)

    if warnings:
        for w in warnings:
            logger.warning("MANIFEST WARNING: %s", w)
    print(
        f"=== expand summary: parsed={len(batch.terms)} "
        f"accepted={len(accepted_with_paths)} skipped={len(skipped_decisions)} "
        f"warnings={len(warnings)} ==="
    )
    print(f"Manifest: {manifest_path}")
    return 0


# ========================================================================
# Subcommand: build-batch
# ========================================================================


def _run_seed_builder(
    brief_path: Path,
    *,
    out_dir: Path,
    overwrite: bool,
    dry_run: bool,
) -> tuple[int, str]:
    """Invoke synth_seed_builder.py build for one brief. Returns (rc, output)."""
    cmd: list[str] = [
        sys.executable,
        str(SEED_BUILDER_SCRIPT),
        "build",
        str(brief_path),
        "--out-dir", str(out_dir),
    ]
    if overwrite:
        cmd.append("--overwrite")
    if dry_run:
        cmd.append("--dry-run")
    proc = subprocess.run(
        cmd, capture_output=True, text=True,
        encoding="utf-8", errors="replace",
    )
    return proc.returncode, (proc.stdout or "") + (proc.stderr or "")


def cmd_build_batch(args: argparse.Namespace) -> int:
    """Read a manifest and materialize each brief as a synthetic seed."""
    manifest_path = Path(args.manifest_path).resolve()
    manifest = load_manifest(manifest_path)
    seeds_dir = Path(manifest["paths"]["seeds_dir"])
    seeds_dir.mkdir(parents=True, exist_ok=True)
    briefs_dir_root = manifest_path.parent  # briefs/<batch_name>/

    entries = manifest["entries"]
    logger.info(
        "Materializing %d seed(s) into %s", len(entries), seeds_dir,
    )

    rc_total = 0
    built = 0
    failed: list[str] = []
    for entry in entries:
        # brief_path in manifest is relative to _HERE (the script dir).
        brief_path = (_HERE / entry["brief_path"]).resolve()
        if not brief_path.exists():
            # Fall back to looking inside briefs_dir_root.
            alt = briefs_dir_root / Path(entry["brief_path"]).name
            if alt.exists():
                brief_path = alt
            else:
                logger.error("Brief missing for %s: %s", entry["term"], brief_path)
                failed.append(entry["term"])
                rc_total = 4
                continue
        rc, output = _run_seed_builder(
            brief_path,
            out_dir=seeds_dir,
            overwrite=args.overwrite_seeds,
            dry_run=args.dry_run,
        )
        if rc != 0:
            logger.error("Seed build failed for %s (rc=%d):\n%s",
                         entry["term"], rc, output.strip())
            failed.append(entry["term"])
            rc_total = max(rc_total, rc)
        else:
            built += 1
            logger.info("Built seed for %s -> %s", entry["term"],
                        entry["expected_seed_filename"])
            if args.verbose >= 1 and output.strip():
                logger.debug("seed-builder output:\n%s", output.strip())

    print(
        f"=== build-batch summary: built={built} failed={len(failed)} "
        f"target_dir={seeds_dir} ==="
    )
    if failed:
        print("Failed terms: " + ", ".join(failed))
    return rc_total


# ========================================================================
# Subcommand: run (expand + build-batch)
# ========================================================================


def cmd_run(args: argparse.Namespace) -> int:
    """Convenience wrapper: expand then build-batch."""
    rc = cmd_expand(args)
    if rc != 0:
        return rc
    if args.dry_run:
        # Expand was a dry-run; nothing to build.
        return 0
    # Locate the manifest the expand step just wrote.
    list_path = Path(args.list_path).resolve()
    batch = parse_term_list(list_path)
    briefs_dir = Path(args.briefs_dir).resolve() / batch.batch_name
    manifest_path = briefs_dir / "manifest.json"
    build_args = argparse.Namespace(
        manifest_path=str(manifest_path),
        overwrite_seeds=args.overwrite_seeds,
        dry_run=False,
        verbose=args.verbose,
        quiet=args.quiet,
    )
    return cmd_build_batch(build_args)


# ========================================================================
# CLI
# ========================================================================


def build_parser() -> argparse.ArgumentParser:
    """Construct the argparse parser."""
    parser = argparse.ArgumentParser(
        prog="expand_term_list",
        description=(
            "Convert a Markdown term list into a batch of YAML briefs and "
            "synthetic *_extracted.json seeds for the V6 permanent-note "
            "pipeline."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  expand_term_list.py -v expand term-lists/2026-04-24-cluster.md\n"
            "  expand_term_list.py -v expand --dry-run term-lists/foo.md\n"
            "  expand_term_list.py -v build-batch briefs/2026-04-24-cluster/manifest.json\n"
            "  expand_term_list.py -v run term-lists/2026-04-24-cluster.md\n"
        ),
    )
    parser.add_argument("--version", action="version",
                        version=f"%(prog)s {__version__}")
    parser.add_argument("-v", "--verbose", action="count", default=0,
                        help="increase logging verbosity (repeatable)")
    parser.add_argument("-q", "--quiet", action="store_true",
                        help="suppress non-error output")

    sub = parser.add_subparsers(dest="command", metavar="COMMAND", required=True)

    # ---- expand ----
    p_exp = sub.add_parser("expand", help="parse a term list -> briefs + manifest")
    p_exp.add_argument("list_path", help="path to a term-list Markdown file")
    p_exp.add_argument(
        "--briefs-dir",
        default=str(DEFAULT_BRIEFS_ROOT),
        help=f"root directory for generated briefs "
             f"(default: {DEFAULT_BRIEFS_ROOT})",
    )
    p_exp.add_argument(
        "--seeds-dir",
        default=str(DEFAULT_SEEDS_ROOT),
        help=f"root directory for generated seeds "
             f"(default: {DEFAULT_SEEDS_ROOT})",
    )
    p_exp.add_argument(
        "--permanent-notes-dir",
        default=str(DEFAULT_PERMANENT_NOTES_DIR),
        help=f"directory holding finished permanent notes (used for the "
             f"dedup gate; default: {DEFAULT_PERMANENT_NOTES_DIR})",
    )
    p_exp.add_argument(
        "--overwrite-existing", action="store_true",
        help="accept terms even if a permanent note already exists",
    )
    p_exp.add_argument(
        "--overwrite-briefs", action="store_true",
        help="overwrite existing brief files in the briefs dir",
    )
    p_exp.add_argument(
        "-n", "--dry-run", action="store_true",
        help="parse and dedup; print what would be written; produce no files",
    )
    p_exp.set_defaults(func=cmd_expand)

    # ---- build-batch ----
    p_build = sub.add_parser(
        "build-batch", help="materialize seeds from a manifest.json",
    )
    p_build.add_argument("manifest_path", help="path to a manifest.json")
    p_build.add_argument(
        "--overwrite-seeds", action="store_true",
        help="pass --overwrite to synth_seed_builder for each brief",
    )
    p_build.add_argument(
        "-n", "--dry-run", action="store_true",
        help="invoke seed builder in dry-run mode (no files written)",
    )
    p_build.set_defaults(func=cmd_build_batch)

    # ---- run ----
    p_run = sub.add_parser(
        "run", help="convenience: expand + build-batch in one invocation",
    )
    p_run.add_argument("list_path", help="path to a term-list Markdown file")
    p_run.add_argument(
        "--briefs-dir",
        default=str(DEFAULT_BRIEFS_ROOT),
        help=f"root directory for generated briefs "
             f"(default: {DEFAULT_BRIEFS_ROOT})",
    )
    p_run.add_argument(
        "--seeds-dir",
        default=str(DEFAULT_SEEDS_ROOT),
        help=f"root directory for generated seeds "
             f"(default: {DEFAULT_SEEDS_ROOT})",
    )
    p_run.add_argument(
        "--permanent-notes-dir",
        default=str(DEFAULT_PERMANENT_NOTES_DIR),
        help=f"dedup-gate target dir (default: {DEFAULT_PERMANENT_NOTES_DIR})",
    )
    p_run.add_argument(
        "--overwrite-existing", action="store_true",
        help="accept terms even if a permanent note already exists",
    )
    p_run.add_argument(
        "--overwrite-briefs", action="store_true",
        help="overwrite existing brief files",
    )
    p_run.add_argument(
        "--overwrite-seeds", action="store_true",
        help="overwrite existing seed files",
    )
    p_run.add_argument(
        "-n", "--dry-run", action="store_true",
        help="run expand in dry-run mode and skip build-batch",
    )
    p_run.set_defaults(func=cmd_run)

    return parser


def configure_logging(verbosity: int, quiet: bool) -> None:
    """Configure root logger from CLI verbosity flags."""
    if quiet:
        level = logging.ERROR
    elif verbosity >= 2:
        level = logging.DEBUG
    elif verbosity == 1:
        level = logging.INFO
    else:
        level = logging.WARNING
    logging.basicConfig(
        level=level,
        format="%(asctime)s [%(levelname)s] %(message)s",
        datefmt="%H:%M:%S",
    )


def main(argv: Sequence[str] | None = None) -> int:
    """Main entry point.

    Args:
        argv: Argument vector (defaults to ``sys.argv[1:]``).

    Returns:
        Exit code (0 = success; 2 = file-not-found; 4 = parse/validation
        failure; 5 = manifest error; 130 = interrupted; 1 = unhandled).
    """
    parser = build_parser()
    args = parser.parse_args(argv)
    configure_logging(args.verbose, args.quiet)

    try:
        return args.func(args)
    except FileNotFoundError as exc:
        logger.error("File not found: %s", exc)
        return 2
    except TermListParseError as exc:
        logger.error("Term-list parse error: %s", exc)
        return 4
    except ManifestError as exc:
        logger.error("Manifest error: %s", exc)
        return 5
    except DedupGateError as exc:
        logger.error("Dedup gate error: %s", exc)
        return 4
    except KeyboardInterrupt:
        logger.warning("Interrupted by user")
        return 130
    except Exception:
        logger.exception("Unexpected error")
        return 1


# ========================================================================
# Entry-point guard
# ========================================================================


if __name__ == "__main__":
    sys.exit(main())
