#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""detect_orphan_wikilinks.py — Detect wiki-links with no target note in the vault.

Scans a target folder recursively for Markdown files, extracts every wiki-link
(``[[Note]]``, ``[[Note|Alias]]``, ``[[Note#Heading]]``, ``[[folder/Note]]``),
and reports the ones whose target note does not exist anywhere in the vault.
Output is a Markdown report (stdout by default, or file via ``--output``).

The script is **report-only**. It never modifies your vault. The companion
``--suggest-kebab`` flag emits suggested kebab-case rewrites in the report
(it does not apply them) — per the vault rule that any link normalization
must produce kebab-case identifiers.

Usage:
    python detect_orphan_wikilinks.py --scan-folder 03-notes
    python detect_orphan_wikilinks.py --scan-folder 03-notes --output orphans.md
    python detect_orphan_wikilinks.py --scan-folder 03-notes --vault-root . --include-embeds
    python detect_orphan_wikilinks.py --scan-folder 03-notes --suggest-kebab -v

Version:
    1.0.0

Python:
    >=3.10

Dependencies:
    Standard library only (argparse, dataclasses, logging, pathlib, re, sys).

Author:
    Generated by Python Script Designer & Generator — Expert v1.0.0
"""
from __future__ import annotations

import argparse
import logging
import re
import sys
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable

# ═════════════════════════════════════════════════════════════════════════
# Constants
# ═════════════════════════════════════════════════════════════════════════

__version__ = "1.0.0"

# Wiki-link pattern. Captures the inner reference. Excludes [[ and ]] inside.
# Optional leading "!" is captured separately via lookbehind handling in code.
WIKILINK_RE = re.compile(r"(!?)\[\[([^\[\]\n]+?)\]\]")

# Strip fenced code blocks (```...```) and inline code (`...`) before parsing.
FENCED_CODE_RE = re.compile(r"```.*?```", re.DOTALL)
INLINE_CODE_RE = re.compile(r"`[^`\n]+`")

# Folders to skip when building the vault index (large/auto-generated).
DEFAULT_INDEX_EXCLUDES: tuple[str, ...] = (
    ".git", ".obsidian", ".trash", ".venv", "node_modules",
    "__pycache__", ".cache", ".vscode",
)

DEFAULT_SCAN_EXCLUDES: tuple[str, ...] = DEFAULT_INDEX_EXCLUDES


# ═════════════════════════════════════════════════════════════════════════
# Logging
# ═════════════════════════════════════════════════════════════════════════

logger = logging.getLogger(__name__)


# ═════════════════════════════════════════════════════════════════════════
# Custom exceptions
# ═════════════════════════════════════════════════════════════════════════

class OrphanLinkError(Exception):
    """Base exception for orphan-wikilink detection errors."""


class FolderNotFoundError(OrphanLinkError):
    """Raised when a required folder does not exist."""


# ═════════════════════════════════════════════════════════════════════════
# Data types
# ═════════════════════════════════════════════════════════════════════════

@dataclass(frozen=True)
class WikiLink:
    """A parsed wiki-link occurrence in a source file.

    Attributes:
        source_file: Path to the file containing the link (relative to vault root).
        line_number: 1-based line number where the link occurs.
        raw: The raw inner reference (e.g. ``"folder/Note#Heading|Alias"``).
        target: The resolved target note name (no alias, no heading, no extension).
        alias: Optional display alias.
        heading: Optional heading anchor (without the leading ``#``).
        block: Optional block reference (without the leading ``^``).
        is_embed: True if the link was an embed (``![[...]]``).
        is_path: True if the target included a folder component (``folder/Note``).
    """
    source_file: Path
    line_number: int
    raw: str
    target: str
    alias: str | None
    heading: str | None
    block: str | None
    is_embed: bool
    is_path: bool


@dataclass
class ScanResult:
    """Aggregate result of a scan."""
    files_scanned: int = 0
    links_found: int = 0
    orphans: list[WikiLink] = field(default_factory=list)


# ═════════════════════════════════════════════════════════════════════════
# Core business logic
# ═════════════════════════════════════════════════════════════════════════

def to_kebab_case(text: str) -> str:
    """Normalize a string to kebab-case.

    Lowercases, replaces underscores/spaces with hyphens, strips characters
    outside ``[a-z0-9-]``, and collapses repeated hyphens.

    Args:
        text: Arbitrary string (typically a note basename without extension).

    Returns:
        The kebab-cased form.

    Example:
        >>> to_kebab_case("My Note Title_v2")
        'my-note-title-v2'
    """
    s = text.strip().lower()
    s = re.sub(r"[\s_]+", "-", s)
    s = re.sub(r"[^a-z0-9\-]+", "", s)
    s = re.sub(r"-{2,}", "-", s).strip("-")
    return s


def strip_code(text: str) -> str:
    """Remove fenced and inline code regions from Markdown text.

    Wiki-links inside code should not be treated as real links.
    """
    text = FENCED_CODE_RE.sub("", text)
    text = INLINE_CODE_RE.sub("", text)
    return text


def parse_wikilink_inner(inner: str) -> tuple[str, str | None, str | None, str | None, bool]:
    """Parse the inner content of a wiki-link.

    Args:
        inner: Text between ``[[`` and ``]]``, e.g. ``"folder/Note#H|Alias"``.

    Returns:
        Tuple of ``(target, alias, heading, block, is_path)``.
    """
    alias: str | None = None
    heading: str | None = None
    block: str | None = None

    if "|" in inner:
        inner, alias = inner.split("|", 1)
        alias = alias.strip()

    if "^" in inner:
        inner, block = inner.split("^", 1)
        block = block.strip()
    elif "#" in inner:
        inner, heading = inner.split("#", 1)
        heading = heading.strip()

    target = inner.strip()
    is_path = "/" in target
    return target, alias, heading, block, is_path


def extract_wikilinks(file_path: Path, vault_root: Path) -> list[WikiLink]:
    """Extract all wiki-links from a single Markdown file.

    Args:
        file_path: Absolute path to the Markdown file.
        vault_root: Absolute path to the vault root (for relative paths in output).

    Returns:
        List of ``WikiLink`` records (one per occurrence).
    """
    try:
        text = file_path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        logger.warning("Skipping non-UTF-8 file: %s", file_path)
        return []

    cleaned = strip_code(text)
    rel = file_path.relative_to(vault_root)

    # Build a map of cleaned-text offset → original line number.
    # Simpler approach: re-scan original line-by-line (code-strip on whole-file
    # could shift line numbers; per-line stripping preserves them).
    links: list[WikiLink] = []
    in_fence = False
    for lineno, raw_line in enumerate(text.splitlines(), start=1):
        stripped = raw_line.lstrip()
        if stripped.startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        line_no_inline = INLINE_CODE_RE.sub("", raw_line)

        for match in WIKILINK_RE.finditer(line_no_inline):
            bang, inner = match.group(1), match.group(2)
            target, alias, heading, block, is_path = parse_wikilink_inner(inner)
            if not target:
                continue
            links.append(WikiLink(
                source_file=rel,
                line_number=lineno,
                raw=inner,
                target=target,
                alias=alias,
                heading=heading,
                block=block,
                is_embed=(bang == "!"),
                is_path=is_path,
            ))
    _ = cleaned  # cleaned retained for potential future whole-file analysis
    return links


def build_vault_index(
    vault_root: Path,
    excludes: Iterable[str] = DEFAULT_INDEX_EXCLUDES,
) -> tuple[dict[str, list[Path]], set[str]]:
    """Build an index of all Markdown notes in the vault.

    Args:
        vault_root: Absolute path to the vault root.
        excludes: Folder names to skip (matched anywhere in path).

    Returns:
        Tuple of:
          - ``{lowercased_basename: [relative_paths]}`` — for basename matching.
          - Set of lowercased relative paths (POSIX, no extension) — for path matching.
    """
    excludes_set = set(excludes)
    by_basename: dict[str, list[Path]] = defaultdict(list)
    by_path: set[str] = set()

    for md in vault_root.rglob("*.md"):
        if any(part in excludes_set for part in md.parts):
            continue
        rel = md.relative_to(vault_root)
        by_basename[md.stem.lower()].append(rel)
        by_path.add(rel.with_suffix("").as_posix().lower())

    logger.info("Indexed %d notes (%d unique basenames)",
                sum(len(v) for v in by_basename.values()), len(by_basename))
    return dict(by_basename), by_path


def is_orphan(link: WikiLink, by_basename: dict[str, list[Path]], by_path: set[str]) -> bool:
    """Return True if the link's target does not exist in the vault index.

    Resolution order (Obsidian-like):
      1. If the target contains a path separator, match against full path index.
      2. Otherwise, match by basename (case-insensitive).
    """
    if link.is_path:
        return link.target.lower() not in by_path
    return link.target.lower() not in by_basename


def scan_folder(
    scan_folder_path: Path,
    vault_root: Path,
    by_basename: dict[str, list[Path]],
    by_path: set[str],
    include_embeds: bool,
    excludes: Iterable[str] = DEFAULT_SCAN_EXCLUDES,
) -> ScanResult:
    """Scan a folder for orphan wiki-links.

    Args:
        scan_folder_path: Absolute path to the folder to scan.
        vault_root: Absolute path to the vault root.
        by_basename: Vault basename index.
        by_path: Vault path index.
        include_embeds: If False, ``![[...]]`` embeds are skipped.
        excludes: Folder names to skip during the scan.

    Returns:
        ``ScanResult`` aggregating files scanned, links found, and orphans.
    """
    excludes_set = set(excludes)
    result = ScanResult()

    for md in scan_folder_path.rglob("*.md"):
        if any(part in excludes_set for part in md.parts):
            continue
        result.files_scanned += 1
        for link in extract_wikilinks(md, vault_root):
            if link.is_embed and not include_embeds:
                continue
            result.links_found += 1
            if is_orphan(link, by_basename, by_path):
                result.orphans.append(link)

    logger.info("Scanned %d files, found %d links, %d orphans",
                result.files_scanned, result.links_found, len(result.orphans))
    return result


# ═════════════════════════════════════════════════════════════════════════
# Report rendering
# ═════════════════════════════════════════════════════════════════════════

def render_markdown_report(
    result: ScanResult,
    scan_folder_rel: Path,
    vault_root: Path,
    suggest_kebab: bool,
) -> str:
    """Render a Markdown report of orphan wiki-links.

    Args:
        result: Scan result to render.
        scan_folder_rel: Folder that was scanned (relative to vault root).
        vault_root: Vault root (used for context only).
        suggest_kebab: If True, include suggested kebab-case rewrites.

    Returns:
        Markdown string ready to be written to a file or stdout.
    """
    from datetime import datetime

    lines: list[str] = []
    lines.append("# Orphan Wiki-Links Report")
    lines.append("")
    lines.append(f"- **Scanned folder:** `{scan_folder_rel.as_posix()}`")
    lines.append(f"- **Vault root:** `{vault_root.name}`")
    lines.append(f"- **Generated:** {datetime.now().isoformat(timespec='seconds')}")
    lines.append(f"- **Files scanned:** {result.files_scanned}")
    lines.append(f"- **Wiki-links found:** {result.links_found}")
    lines.append(f"- **Orphan links:** {len(result.orphans)}")
    lines.append("")

    if not result.orphans:
        lines.append("> [!success] No orphan wiki-links detected.")
        lines.append("")
        return "\n".join(lines)

    # Group by source file.
    by_file: dict[Path, list[WikiLink]] = defaultdict(list)
    for link in result.orphans:
        by_file[link.source_file].append(link)

    lines.append("## Summary by File")
    lines.append("")
    lines.append("| File | Orphan Count |")
    lines.append("|------|--------------|")
    for src in sorted(by_file.keys(), key=lambda p: p.as_posix()):
        lines.append(f"| `{src.as_posix()}` | {len(by_file[src])} |")
    lines.append("")

    lines.append("## Detailed Findings")
    lines.append("")
    for src in sorted(by_file.keys(), key=lambda p: p.as_posix()):
        lines.append(f"### `{src.as_posix()}`")
        lines.append("")
        header = "| Line | Wiki-Link | Target | Alias | Heading | Embed |"
        sep = "|------|-----------|--------|-------|---------|-------|"
        if suggest_kebab:
            header = header[:-1] + " Suggested (kebab-case) |"
            sep = sep[:-1] + "-------------------------|"
        lines.append(header)
        lines.append(sep)
        for link in sorted(by_file[src], key=lambda L: L.line_number):
            row = (
                f"| {link.line_number} "
                f"| `[[{link.raw}]]` "
                f"| `{link.target}` "
                f"| {link.alias or ''} "
                f"| {link.heading or ''} "
                f"| {'yes' if link.is_embed else ''} |"
            )
            if suggest_kebab:
                row = row[:-1] + f" `{to_kebab_case(link.target)}` |"
            lines.append(row)
        lines.append("")

    if suggest_kebab:
        lines.append("> [!note] Suggestions are **not applied**. "
                     "Per vault policy, any link normalization must use kebab-case. "
                     "Review each suggestion before adopting it.")
        lines.append("")

    return "\n".join(lines)


# ═════════════════════════════════════════════════════════════════════════
# CLI
# ═════════════════════════════════════════════════════════════════════════

def build_parser() -> argparse.ArgumentParser:
    """Construct the command-line argument parser."""
    parser = argparse.ArgumentParser(
        prog="detect_orphan_wikilinks.py",
        description="Detect wiki-links with no target note in the vault and emit a Markdown report.",
        epilog=(
            "Examples:\n"
            "  detect_orphan_wikilinks.py --scan-folder 03-notes\n"
            "  detect_orphan_wikilinks.py --scan-folder 03-notes --output orphans.md\n"
            "  detect_orphan_wikilinks.py --scan-folder 02-projects --include-embeds -v\n"
            "  detect_orphan_wikilinks.py --scan-folder 03-notes --suggest-kebab\n"
            "\n"
            "Exit codes:\n"
            "  0 success | 2 folder not found | 4 bad args | 130 interrupted | 1 unexpected\n"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--version", action="version", version=f"%(prog)s {__version__}")
    parser.add_argument("-v", "--verbose", action="count", default=0,
                        help="increase logging verbosity (repeatable)")
    parser.add_argument("-q", "--quiet", action="store_true",
                        help="suppress non-error output")
    parser.add_argument("--scan-folder", required=True, type=Path,
                        help="folder to scan recursively for wiki-links (relative to --vault-root or absolute)")
    parser.add_argument("--vault-root", type=Path, default=Path.cwd(),
                        help="vault root used to build the note index (default: cwd)")
    parser.add_argument("-o", "--output", type=Path, default=None,
                        help="write the Markdown report to this path (default: stdout)")
    parser.add_argument("--include-embeds", action="store_true",
                        help="also check ![[...]] embeds (default: skipped)")
    parser.add_argument("--suggest-kebab", action="store_true",
                        help="include suggested kebab-case rewrites in the report (does NOT apply them)")
    parser.add_argument("--exclude", action="append", default=None, metavar="DIRNAME",
                        help="folder name to exclude from indexing AND scanning (repeatable)")
    return parser


def configure_logging(verbosity: int, quiet: bool) -> None:
    """Configure the root logger."""
    if quiet:
        level = logging.ERROR
    elif verbosity >= 2:
        level = logging.DEBUG
    elif verbosity == 1:
        level = logging.INFO
    else:
        level = logging.WARNING
    logging.basicConfig(
        level=level,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )


def resolve_paths(scan_folder: Path, vault_root: Path) -> tuple[Path, Path]:
    """Resolve and validate scan-folder and vault-root."""
    vault_root = vault_root.resolve()
    if not vault_root.is_dir():
        raise FolderNotFoundError(f"Vault root is not a directory: {vault_root}")

    if not scan_folder.is_absolute():
        scan_folder = (vault_root / scan_folder).resolve()
    else:
        scan_folder = scan_folder.resolve()
    if not scan_folder.is_dir():
        raise FolderNotFoundError(f"Scan folder is not a directory: {scan_folder}")

    try:
        scan_folder.relative_to(vault_root)
    except ValueError as exc:
        raise FolderNotFoundError(
            f"Scan folder {scan_folder} is not inside vault root {vault_root}"
        ) from exc

    return scan_folder, vault_root


def main(argv: list[str] | None = None) -> int:
    """Main entry point."""
    parser = build_parser()
    args = parser.parse_args(argv)
    configure_logging(args.verbose, args.quiet)

    excludes = tuple(args.exclude) if args.exclude else DEFAULT_INDEX_EXCLUDES

    try:
        scan_folder_abs, vault_root_abs = resolve_paths(args.scan_folder, args.vault_root)
        logger.info("Scan folder: %s", scan_folder_abs)
        logger.info("Vault root:  %s", vault_root_abs)

        by_basename, by_path = build_vault_index(vault_root_abs, excludes=excludes)
        result = scan_folder(
            scan_folder_path=scan_folder_abs,
            vault_root=vault_root_abs,
            by_basename=by_basename,
            by_path=by_path,
            include_embeds=args.include_embeds,
            excludes=excludes,
        )

        report = render_markdown_report(
            result=result,
            scan_folder_rel=scan_folder_abs.relative_to(vault_root_abs),
            vault_root=vault_root_abs,
            suggest_kebab=args.suggest_kebab,
        )

        if args.output:
            args.output.parent.mkdir(parents=True, exist_ok=True)
            args.output.write_text(report, encoding="utf-8")
            logger.info("Report written to %s", args.output)
            if not args.quiet:
                print(f"Report written: {args.output}  "
                      f"({len(result.orphans)} orphans across {result.files_scanned} files)",
                      file=sys.stderr)
        else:
            sys.stdout.write(report)

        return 0

    except FolderNotFoundError as e:
        logger.error("%s", e)
        return 2
    except PermissionError as e:
        logger.error("Permission denied: %s", e)
        return 3
    except KeyboardInterrupt:
        logger.warning("Interrupted by user")
        return 130
    except Exception:
        logger.exception("Unexpected error")
        return 1


# ═════════════════════════════════════════════════════════════════════════
# Entry-point guard
# ═════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    sys.exit(main())
