#!/usr/bin/env python3
"""
obsidian_toc.py
─────────────────────────────────────────────────────────────────────────────
Generate and insert an OBSIDIAN-NATIVE Table of Contents into a Markdown
note. Uses Obsidian wiki-link heading syntax ([[#Heading]]) so links are
fully navigable in both Reading and Live Preview modes — no anchor-slug
computation, full Unicode support, and clickable in the editor.

WHY THIS OVER generate_toc.py?
  - generate_toc.py uses GitHub-style [text](#anchor) links. Those work in
    Obsidian preview but aren't native and break on special characters.
  - This script uses [[#Heading|Display Text]] which is Obsidian's first-
    class internal link syntax — Ctrl+Click, hover-preview, graph-edge,
    backlinks all work as expected.

FEATURES:
  - Skips YAML frontmatter and fenced code blocks (``` and ~~~)
  - Idempotent: re-running replaces the existing TOC in place via sentinels
  - Dry-run by default — pass --execute to write
  - Timestamped .bak before any write (disable with --no-backup)
  - Configurable depth range (--min-depth / --max-depth)
  - Inserts after the first H1 by default (--no-h1-insert to disable)
  - Handles duplicate headings via Obsidian's ^block-id fallback notice
  - Two styles selectable via --style:
      wiki    → [[#Heading]]              (default, Obsidian-native)
      alias   → [[#Heading|Display]]      (cleaner display, same target)
      anchor  → [Display](#anchor-slug)   (GitHub-compatible fallback)

USAGE:
  python obsidian_toc.py <file.md>                       # preview
  python obsidian_toc.py <file.md> --execute             # write
  python obsidian_toc.py <file.md> --max-depth 3
  python obsidian_toc.py <file.md> --style alias --execute
  python obsidian_toc.py <file.md> --skip-h1 --execute

REQUIREMENTS:
  Pure stdlib. No pip installs.

@version  1.0.0
@author   PKB Scripting Architect
"""

from __future__ import annotations

import argparse
import datetime
import re
import shutil
import sys
from pathlib import Path
from typing import NamedTuple

# Ensure UTF-8 stdout on Windows so Unicode box-drawing / emoji print cleanly
if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
    try:
        sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
        sys.stderr.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
    except (AttributeError, OSError):
        pass

# ── CONFIGURATION — edit defaults to suit your vault ─────────────────────────
CONFIG = {
    "min_depth": 2,                 # Skip H1 by default (it's the note title)
    "max_depth": 6,
    "indent": "  ",                 # 2-space indent per level
    "bullet": "-",
    "skip_first_h1": True,          # H1 is usually the title — exclude from TOC list
    "insert_after_h1": True,        # Place TOC after the title H1
    "backup": True,
    "toc_heading": "## 📑 Table of Contents",
    "sentinel_start": "<!-- OBSIDIAN-TOC START — do not edit; regenerated by obsidian_toc.py -->",
    "sentinel_end":   "<!-- OBSIDIAN-TOC END -->",
    "style": "wiki",                # wiki | alias | anchor
}
# ─────────────────────────────────────────────────────────────────────────────

_HEADING_RE = re.compile(r"^(#{1,6})\s+(.+?)\s*#*\s*$")
_FENCE_RE = re.compile(r"^(```|~~~)")


class Heading(NamedTuple):
    depth: int        # 1–6
    text: str         # raw heading text, # markers stripped
    line_index: int   # 0-based position in source


# ── Frontmatter ──────────────────────────────────────────────────────────────

def _find_frontmatter_end(lines: list[str]) -> int:
    """Return index after closing ---, or 0 if no frontmatter."""
    if not lines or lines[0].rstrip() != "---":
        return 0
    for i in range(1, len(lines)):
        if lines[i].rstrip() in ("---", "..."):
            return i + 1
    return 0  # unclosed → ignore


# ── Heading extraction (code-block aware) ────────────────────────────────────

def _extract_headings(
    lines: list[str],
    start: int,
    min_depth: int,
    max_depth: int,
) -> list[Heading]:
    """Return all headings between min_depth and max_depth, ignoring
    headings inside fenced code blocks."""
    out: list[Heading] = []
    in_fence = False

    for idx in range(start, len(lines)):
        line = lines[idx]
        if _FENCE_RE.match(line):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        m = _HEADING_RE.match(line)
        if not m:
            continue
        depth = len(m.group(1))
        text = m.group(2).strip()
        if min_depth <= depth <= max_depth:
            out.append(Heading(depth, text, idx))
    return out


# ── Anchor slug (only used for --style anchor) ───────────────────────────────

def _to_anchor(text: str) -> str:
    text = text.lower()
    text = re.sub(r"[^\w\s-]", "", text, flags=re.UNICODE)
    text = re.sub(r"\s+", "-", text.strip())
    text = re.sub(r"-{2,}", "-", text)
    return text.strip("-")


# ── Sanitise heading text for safe use inside [[# ... ]] ─────────────────────

def _sanitise_for_wikilink(text: str) -> str:
    """Strip characters Obsidian disallows inside [[...]]: pipe, brackets,
    hash, caret. Replace with spaces and collapse."""
    cleaned = re.sub(r"[\[\]|#^]", " ", text)
    return re.sub(r"\s+", " ", cleaned).strip()


# ── TOC line builder ─────────────────────────────────────────────────────────

def _build_toc_lines(
    headings: list[Heading],
    base_depth: int,
    indent: str,
    bullet: str,
    style: str,
) -> tuple[list[str], list[str]]:
    """Return (toc_lines, warnings)."""
    out: list[str] = []
    warnings: list[str] = []
    seen: dict[str, int] = {}

    for h in headings:
        pad = indent * (h.depth - base_depth)
        clean = _sanitise_for_wikilink(h.text)

        # Track duplicates — Obsidian wiki-link will jump to the first match
        seen[clean] = seen.get(clean, 0) + 1
        if seen[clean] > 1:
            warnings.append(
                f"Duplicate heading '{clean}' (occurrence #{seen[clean]}) — "
                f"wiki-link will navigate to the first occurrence only."
            )

        if style == "wiki":
            link = f"[[#{clean}]]"
        elif style == "alias":
            link = f"[[#{clean}|{h.text}]]"
        elif style == "anchor":
            link = f"[{h.text}](#{_to_anchor(h.text)})"
        else:
            raise ValueError(f"Unknown style: {style}")

        out.append(f"{pad}{bullet} {link}")

    return out, warnings


# ── Existing TOC sentinel detection ──────────────────────────────────────────

def _find_existing_toc_range(
    lines: list[str], start_tag: str, end_tag: str
) -> tuple[int, int] | None:
    """Return (start, end_exclusive) of an existing TOC block, or None."""
    s_idx: int | None = None
    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped == start_tag:
            s_idx = i
        elif stripped == end_tag and s_idx is not None:
            return s_idx, i + 1
    return None


# ── Insertion point ──────────────────────────────────────────────────────────

def _find_insertion_point(
    lines: list[str], fm_end: int, after_h1: bool
) -> int:
    if not after_h1:
        return fm_end
    for i in range(fm_end, len(lines)):
        if lines[i].startswith("# ") and _HEADING_RE.match(lines[i]):
            j = i + 1
            while j < len(lines) and lines[j].strip() == "":
                j += 1
            return j
    return fm_end


# ── Main pipeline ────────────────────────────────────────────────────────────

def process_file(
    filepath: Path,
    *,
    min_depth: int,
    max_depth: int,
    indent: str,
    bullet: str,
    skip_first_h1: bool,
    insert_after_h1: bool,
    toc_heading: str,
    sentinel_start: str,
    sentinel_end: str,
    style: str,
    execute: bool,
    backup: bool,
) -> int:
    if not filepath.exists():
        print(f"ERROR: File not found: {filepath}", file=sys.stderr)
        return 1
    if filepath.suffix.lower() not in (".md", ".markdown"):
        print(f"WARNING: '{filepath.name}' does not look like Markdown.")

    raw = filepath.read_text(encoding="utf-8")
    lines = raw.splitlines()

    fm_end = _find_frontmatter_end(lines)
    existing = _find_existing_toc_range(lines, sentinel_start, sentinel_end)

    # Extract headings from the document MINUS any existing TOC block, so the
    # TOC doesn't include itself or its heading.
    if existing:
        scan_lines = lines[:existing[0]] + lines[existing[1]:]
    else:
        scan_lines = lines

    headings = _extract_headings(scan_lines, fm_end, min_depth, max_depth)

    if skip_first_h1 and headings and headings[0].depth == 1:
        headings = headings[1:]

    if not headings:
        print("No headings found in the requested depth range — nothing to do.")
        return 0

    base = min(h.depth for h in headings)
    toc_inner, warnings = _build_toc_lines(headings, base, indent, bullet, style)

    block: list[str] = [sentinel_start]
    if toc_heading:
        block += ["", toc_heading, ""]
    block += toc_inner
    block += ["", sentinel_end]

    if existing:
        new_lines = lines[:existing[0]] + block + lines[existing[1]:]
        action = f"Replaced existing TOC (lines {existing[0] + 1}–{existing[1]})"
    else:
        insert_at = _find_insertion_point(lines, fm_end, insert_after_h1)
        new_lines = lines[:insert_at] + [""] + block + [""] + lines[insert_at:]
        action = f"Inserted new TOC at line {insert_at + 1}"

    # ── Report ────────────────────────────────────────────────────────────
    print()
    print("─" * 64)
    print(f"File    : {filepath}")
    print(f"Style   : {style}")
    print(f"Action  : {action}")
    print(f"Entries : {len(toc_inner)} headings (H{base}–H{max_depth})")
    print("─" * 64)
    print("\nGenerated TOC preview:\n")
    for ln in block:
        print(f"  {ln}")
    print()

    if warnings:
        print("⚠️  Warnings:")
        for w in warnings:
            print(f"   - {w}")
        print()

    if not execute:
        print("DRY RUN — no changes written. Pass --execute to apply.\n")
        return 0

    if backup:
        ts = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
        bak = filepath.with_suffix(filepath.suffix + f".{ts}.bak")
        shutil.copy2(filepath, bak)
        print(f"Backup  : {bak}")

    # Preserve trailing newline behaviour of original file
    trailing_nl = "\n" if raw.endswith("\n") else ""
    filepath.write_text("\n".join(new_lines) + trailing_nl, encoding="utf-8")
    print(f"Written : {filepath}\n")
    return 0


# ── CLI ──────────────────────────────────────────────────────────────────────

def main() -> int:
    p = argparse.ArgumentParser(
        description="Generate an Obsidian-native [[#Heading]] Table of Contents.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("file", help="Path to the Markdown file")
    p.add_argument("--execute", action="store_true",
                   help="Write changes (default: dry run)")
    p.add_argument("--no-backup", action="store_true",
                   help="Skip the timestamped .bak file")
    p.add_argument("--min-depth", type=int, default=CONFIG["min_depth"],
                   metavar="N", help=f"Min heading depth (default: {CONFIG['min_depth']})")
    p.add_argument("--max-depth", type=int, default=CONFIG["max_depth"],
                   metavar="N", help=f"Max heading depth (default: {CONFIG['max_depth']})")
    p.add_argument("--skip-h1", action="store_true", default=CONFIG["skip_first_h1"],
                   help="Exclude leading H1 from TOC entries")
    p.add_argument("--include-h1", dest="skip_h1", action="store_false",
                   help="Include leading H1 in TOC entries")
    p.add_argument("--no-h1-insert", action="store_true",
                   help="Insert TOC right after frontmatter, not after H1")
    p.add_argument("--style", choices=("wiki", "alias", "anchor"),
                   default=CONFIG["style"],
                   help="Link style: wiki (default), alias, or anchor")
    p.add_argument("--heading", default=CONFIG["toc_heading"],
                   help=f"TOC heading text (default: '{CONFIG['toc_heading']}'). "
                        "Pass empty string to omit.")

    args = p.parse_args()

    if args.min_depth < 1 or args.max_depth > 6 or args.min_depth > args.max_depth:
        print("ERROR: invalid --min-depth/--max-depth (must be 1–6, min ≤ max).",
              file=sys.stderr)
        return 2

    return process_file(
        filepath=Path(args.file),
        min_depth=args.min_depth,
        max_depth=args.max_depth,
        indent=CONFIG["indent"],
        bullet=CONFIG["bullet"],
        skip_first_h1=args.skip_h1,
        insert_after_h1=not args.no_h1_insert,
        toc_heading=args.heading,
        sentinel_start=CONFIG["sentinel_start"],
        sentinel_end=CONFIG["sentinel_end"],
        style=args.style,
        execute=args.execute,
        backup=not args.no_backup,
    )


if __name__ == "__main__":
    sys.exit(main())
