#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""wiki_orphan_scanner.py — Detect [[wiki-links]] without permanent notes in an Obsidian vault.

Scans all Markdown files in a specified folder for [[wiki-links]] whose target
notes do not exist anywhere in the vault, then emits a grouped Markdown report.

Usage:
    python wiki_orphan_scanner.py 05-literature
    python wiki_orphan_scanner.py 05-literature --vault D:/vault --recursive
    python wiki_orphan_scanner.py . --output orphan-report.md -v
    python wiki_orphan_scanner.py 99-inbox --dry-run

Version:
    1.0.0

Python:
    >=3.10

Dependencies:
    stdlib only (re, pathlib, argparse, collections, logging, sys)

Author:
    Generated by Python Script Designer & Generator — Expert v1.0.0
"""
from __future__ import annotations

import argparse
import logging
import re
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from pathlib import Path

__version__ = "1.0.0"

# Matches [[Note]], [[Note|Alias]], [[Note#Heading]], [[Note#Heading|Alias]].
# Negative lookbehind on '!' excludes embedded files: ![[image.png]].
WIKI_LINK_RE = re.compile(
    r"(?<!!)\[\[([^\[\]|#\n]+)(?:[#|][^\[\]]*)?\]\]",
    re.IGNORECASE,
)

CODE_FENCE_RE = re.compile(r"```.*?```", re.DOTALL)
INLINE_CODE_RE = re.compile(r"`[^`\n]+`")

logger = logging.getLogger(__name__)


class WikiOrphanScannerError(Exception):
    """Base exception for wiki_orphan_scanner errors."""


class FolderNotFoundError(WikiOrphanScannerError):
    """Raised when the specified scan folder does not exist or is not a directory."""


class VaultNotFoundError(WikiOrphanScannerError):
    """Raised when the specified vault root does not exist or is not a directory."""


@dataclass(frozen=True)
class BrokenLink:
    """A [[wiki-link]] whose target note was not found in the vault index.

    Attributes:
        source_file: Absolute path to the file containing this link.
        link_target: Raw link target text as written (pre-normalisation).
        line_number: 1-based line number of the link in source_file.
    """

    source_file: Path
    link_target: str
    line_number: int


@dataclass
class ScanResult:
    """Aggregated results of a single folder scan run.

    Attributes:
        scanned_files: Number of .md files examined.
        total_links: Total wiki-links encountered across all files.
        broken_links: BrokenLink instances for every unresolvable link.
        vault_note_count: Size of the vault index used for resolution.
    """

    scanned_files: int = 0
    total_links: int = 0
    broken_links: list[BrokenLink] = field(default_factory=list)
    vault_note_count: int = 0


def build_vault_index(vault_root: Path) -> set[str]:
    """Build a case-insensitive set of all note stems in the vault.

    Obsidian resolves [[Wiki Links]] by matching the link target
    case-insensitively against the stem (filename without extension) of
    every .md file anywhere in the vault. This function replicates that.

    Args:
        vault_root: Root directory of the Obsidian vault.

    Returns:
        Lowercase set of .md stems across the entire vault tree.

    Raises:
        VaultNotFoundError: If vault_root does not exist or is not a directory.
    """
    if not vault_root.exists():
        raise VaultNotFoundError(f"Vault root does not exist: {vault_root}")
    if not vault_root.is_dir():
        raise VaultNotFoundError(f"Vault root is not a directory: {vault_root}")

    index: set[str] = {md.stem.lower() for md in vault_root.rglob("*.md")}
    logger.info("Vault index: %d notes indexed from %s", len(index), vault_root)
    return index


def strip_code_spans(text: str) -> str:
    """Remove fenced code blocks and inline code spans from Markdown text.

    Fenced blocks are replaced with equivalent newlines so line numbers of
    surrounding content are preserved. Inline code spans are zeroed out.

    Args:
        text: Raw Markdown content.

    Returns:
        Text safe to run wiki-link extraction against.
    """
    def _preserve_newlines(m: re.Match) -> str:
        return "\n" * m.group(0).count("\n")

    text = CODE_FENCE_RE.sub(_preserve_newlines, text)
    return INLINE_CODE_RE.sub("", text)


def extract_wiki_links(content: str) -> list[tuple[str, int]]:
    """Extract all wiki-link targets and their 1-based line numbers.

    Handles:
      [[Note Name]]
      [[Note Name|Display Alias]]
      [[Note Name#Heading]]
      [[Note Name#Heading|Alias]]
      [[folder/Note Name]]  — resolved to stem only

    Args:
        content: Markdown text with code spans already stripped.

    Returns:
        List of (note_name, line_number) tuples.

    Example:
        >>> extract_wiki_links("See [[PKM]] and [[Zettelkasten#Origins|ZK]].")
        [('PKM', 1), ('Zettelkasten', 1)]
    """
    results: list[tuple[str, int]] = []
    for line_num, line in enumerate(content.splitlines(), start=1):
        for m in WIKI_LINK_RE.finditer(line):
            raw = m.group(1).strip()
            # For path-based links ([[folder/Note]]), keep only the final segment stem.
            # NOTE: stem-only is a conservative approximation of Obsidian's shortest-path
            # resolution; two notes with the same stem in different folders may produce
            # false positives (known limitation, v1.0.0).
            if "/" in raw or "\\" in raw:
                note_name = Path(raw).stem
            else:
                note_name = raw
            results.append((note_name, line_num))
    return results


def resolve_link(link_target: str, vault_index: set[str]) -> bool:
    """Check whether a wiki-link target maps to an existing vault note.

    Args:
        link_target: The raw note name from the wiki-link (e.g. "My Note").
        vault_index: Lowercase set of note stems from build_vault_index().

    Returns:
        True if the link resolves to a known note, False otherwise.
    """
    stem = Path(link_target).stem if link_target.lower().endswith(".md") else link_target
    return stem.lower() in vault_index


def scan_folder(
    folder: Path,
    vault_index: set[str],
    *,
    recursive: bool = False,
) -> ScanResult:
    """Scan Markdown files in a folder for wiki-links with missing targets.

    Args:
        folder: Directory whose .md files are scanned for source links.
        vault_index: Set of lowercase note stems from build_vault_index().
        recursive: If True, descend into subdirectories of folder.

    Returns:
        ScanResult with all broken links found.

    Raises:
        FolderNotFoundError: If folder does not exist or is not a directory.
    """
    if not folder.exists():
        raise FolderNotFoundError(f"Scan folder does not exist: {folder}")
    if not folder.is_dir():
        raise FolderNotFoundError(f"Scan folder is not a directory: {folder}")

    result = ScanResult(vault_note_count=len(vault_index))
    glob_fn = folder.rglob if recursive else folder.glob

    for md_file in sorted(glob_fn("*.md")):
        logger.debug("Scanning: %s", md_file)
        result.scanned_files += 1

        try:
            raw = md_file.read_text(encoding="utf-8", errors="replace")
        except OSError as exc:
            logger.warning("Cannot read %s — skipping: %s", md_file, exc)
            continue

        clean = strip_code_spans(raw)
        links = extract_wiki_links(clean)
        result.total_links += len(links)

        for target, line_num in links:
            if not resolve_link(target, vault_index):
                result.broken_links.append(
                    BrokenLink(source_file=md_file, link_target=target, line_number=line_num)
                )
                logger.debug("Broken: %s:%d → [[%s]]", md_file.name, line_num, target)

    logger.info(
        "Scan complete — files: %d  links: %d  broken: %d",
        result.scanned_files,
        result.total_links,
        len(result.broken_links),
    )
    return result


def generate_report(
    result: ScanResult,
    scanned_folder: Path,
    vault_root: Path,
    *,
    recursive: bool,
) -> str:
    """Render a ScanResult as a Markdown orphan report.

    Args:
        result: Populated ScanResult from scan_folder().
        scanned_folder: Folder that was scanned (display only).
        vault_root: Vault root used for resolution (display only).
        recursive: Whether the scan was recursive (display only).

    Returns:
        Complete Markdown string suitable for direct use in Obsidian.
    """
    out: list[str] = []
    broken_count = len(result.broken_links)
    pct = (broken_count / result.total_links * 100) if result.total_links else 0.0

    out += [
        "# Wiki-Link Orphan Report",
        "",
        f"> **Scan folder:** `{scanned_folder}`  ",
        f"> **Vault root:** `{vault_root}`  ",
        f"> **Recursive:** {'yes' if recursive else 'no'}",
        "",
        "## Summary",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Files scanned | {result.scanned_files} |",
        f"| Notes in vault index | {result.vault_note_count:,} |",
        f"| Total wiki-links found | {result.total_links:,} |",
        f"| **Broken links (no target note)** | **{broken_count:,}** |",
        f"| Broken link rate | {pct:.1f}% |",
        "",
    ]

    if broken_count == 0:
        out += [
            "> [!success] All Clear",
            "> No broken wiki-links detected — every link resolves to an existing note.",
            "",
        ]
        return "\n".join(out)

    out += [
        "> [!warning] Broken Links Detected",
        f"> {broken_count} wiki-link(s) point to notes that do not exist in the vault.",
        "",
    ]

    grouped: dict[Path, list[BrokenLink]] = defaultdict(list)
    for bl in sorted(result.broken_links, key=lambda b: (str(b.source_file), b.line_number)):
        grouped[bl.source_file].append(bl)

    out += ["## Broken Links by File", ""]

    for src in sorted(grouped):
        file_links = grouped[src]
        out += [
            f"### `{src.name}`",
            "",
            f"**Path:** `{src}`  ",
            f"**Missing links:** {len(file_links)}",
            "",
            "| Line | Missing Target |",
            "|-----:|----------------|",
        ]
        for bl in file_links:
            out.append(f"| {bl.line_number} | `[[{bl.link_target}]]` |")
        out.append("")

    counts: Counter[str] = Counter(bl.link_target for bl in result.broken_links)
    sorted_targets = sorted(counts.items(), key=lambda x: (-x[1], x[0].casefold()))

    out += [
        "## Unique Missing Note Targets (by Reference Count)",
        "",
        f"*{len(sorted_targets)} distinct note name(s) referenced but absent from the vault — sorted by frequency:*",
        "",
        "| Count | Wiki-Link |",
        "|------:|-----------|",
    ]
    for target, count in sorted_targets:
        out.append(f"| {count} | `[[{target}]]` |")
    out.append("")

    return "\n".join(out)


def generate_seed_report(
    result: ScanResult,
    *,
    exclude_synthetic: bool = True,
) -> str:
    """Render a frequency-ranked seed list of orphan wiki-links.

    Produces a Markdown file listing every unique missing link target sorted
    by how many times it is referenced — highest first — so the user can
    prioritise which permanent notes to create first.

    Args:
        result: Populated ScanResult from scan_folder().
        exclude_synthetic: If True, omit entries containing '-synthetic-seed-'.

    Returns:
        Markdown string suitable for use as a note-creation seed list.
    """
    sources: dict[str, list[BrokenLink]] = defaultdict(list)
    for bl in result.broken_links:
        if exclude_synthetic and "-synthetic-seed-" in bl.link_target.lower():
            continue
        sources[bl.link_target].append(bl)

    sorted_items = sorted(
        sources.items(), key=lambda x: (-len(x[1]), x[0].casefold())
    )

    lines: list[str] = [
        "# Seed Wiki-Links — Priority Ranked by Reference Count",
        "",
        f"**Total unique missing links:** {len(sorted_items)}  ",
        f"**Synthetic-seed entries excluded:** {'yes' if exclude_synthetic else 'no'}",
        "",
        "---",
        "",
    ]
    for target, occurrences in sorted_items:
        count = len(occurrences)
        lines += [
            f"## [[{target}]] — {count} reference(s)",
            "",
            "| Source File | Line |",
            "|-------------|-----:|",
        ]
        for bl in sorted(occurrences, key=lambda b: (b.source_file.name.casefold(), b.line_number)):
            lines.append(f"| `{bl.source_file.name}` | {bl.line_number} |")
        lines.append("")
    return "\n".join(lines)


def build_parser() -> argparse.ArgumentParser:
    """Construct the command-line argument parser."""
    parser = argparse.ArgumentParser(
        prog="wiki_orphan_scanner",
        description=(
            "Scan an Obsidian vault folder for [[wiki-links]] whose target "
            "notes do not exist, and emit a Markdown orphan report."
        ),
        epilog=(
            "Examples:\n"
            "  wiki_orphan_scanner.py 05-literature\n"
            "  wiki_orphan_scanner.py 05-literature --vault D:/vault -r\n"
            "  wiki_orphan_scanner.py . -o orphan-report.md -v\n"
            "  wiki_orphan_scanner.py 99-inbox --dry-run\n"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("folder", type=Path, help="Folder to scan for wiki-links.")
    parser.add_argument(
        "--vault", type=Path, default=None, metavar="PATH",
        help="Vault root for link resolution. Auto-detected via .obsidian if omitted.",
    )
    parser.add_argument("-r", "--recursive", action="store_true",
                        help="Recursively scan subdirectories of FOLDER.")
    parser.add_argument("-o", "--output", type=Path, default=None, metavar="PATH",
                        help="Write report to this file (default: stdout).")
    parser.add_argument("--version", action="version", version=f"%(prog)s {__version__}")
    parser.add_argument("-v", "--verbose", action="count", default=0,
                        help="Increase logging verbosity (-v INFO, -vv DEBUG).")
    parser.add_argument("-q", "--quiet", action="store_true",
                        help="Suppress all non-error output.")
    parser.add_argument("-n", "--dry-run", action="store_true",
                        help="Show what would be scanned without running.")
    parser.add_argument(
        "--seed", type=Path, default=None, metavar="PATH",
        help=(
            "Write a frequency-ranked seed list of orphan links to this file. "
            "Entries containing '-synthetic-seed-' are excluded automatically."
        ),
    )
    parser.add_argument(
        "--include-synthetic", action="store_true",
        help="Include -synthetic-seed- entries in the --seed output (excluded by default).",
    )
    return parser


def configure_logging(verbosity: int, quiet: bool) -> None:
    """Configure root logger from CLI verbosity flags."""
    level = (
        logging.ERROR if quiet
        else logging.DEBUG if verbosity >= 2
        else logging.INFO if verbosity == 1
        else logging.WARNING
    )
    logging.basicConfig(
        level=level,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
        stream=sys.stderr,
    )


def _auto_detect_vault_root(folder: Path) -> Path:
    """Walk upward from folder to find a .obsidian marker directory."""
    for candidate in [folder.resolve(), *folder.resolve().parents]:
        if (candidate / ".obsidian").is_dir():
            logger.info("Auto-detected vault root: %s", candidate)
            return candidate
    fallback = Path.cwd()
    logger.info("No .obsidian directory found; using CWD as vault root: %s", fallback)
    return fallback


def main(argv: list[str] | None = None) -> int:
    """Main entry point.

    Returns:
        0=success, 1=unexpected error, 2=path not found, 3=permission denied, 130=interrupted.
    """
    parser = build_parser()
    args = parser.parse_args(argv)
    configure_logging(args.verbose, args.quiet)

    folder: Path = args.folder.resolve()
    vault_root: Path = args.vault.resolve() if args.vault else _auto_detect_vault_root(folder)

    if args.dry_run:
        glob_fn = folder.rglob if args.recursive else folder.glob
        try:
            file_count = sum(1 for _ in glob_fn("*.md")) if folder.is_dir() else 0
        except PermissionError as exc:
            logger.error("Cannot access folder: %s", exc)
            return 3
        print(f"# Dry Run — wiki_orphan_scanner v{__version__}\n")
        print(f"**Scan folder:** `{folder}`  ")
        print(f"**Vault root:** `{vault_root}`  ")
        print(f"**Recursive:** {'yes' if args.recursive else 'no'}  ")
        print(f"**Files that would be scanned:** {file_count}")
        return 0

    try:
        vault_index = build_vault_index(vault_root)
        result = scan_folder(folder, vault_index, recursive=args.recursive)
    except (FolderNotFoundError, VaultNotFoundError) as exc:
        logger.error("%s", exc)
        return 2
    except PermissionError as exc:
        logger.error("Permission denied: %s", exc)
        return 3
    except KeyboardInterrupt:
        logger.warning("Interrupted by user.")
        return 130
    except Exception:
        logger.exception("Unexpected error during scan.")
        return 1

    report = generate_report(result, folder, vault_root, recursive=args.recursive)

    if args.output:
        try:
            args.output.write_text(report, encoding="utf-8")
            if not args.quiet:
                print(f"Report written to: {args.output}", file=sys.stderr)
        except OSError as exc:
            logger.error("Cannot write output file: %s", exc)
            return 3
    else:
        print(report)

    if args.seed:
        exclude = not args.include_synthetic
        seed_report = generate_seed_report(result, exclude_synthetic=exclude)
        try:
            args.seed.parent.mkdir(parents=True, exist_ok=True)
            args.seed.write_text(seed_report, encoding="utf-8")
            if not args.quiet:
                unique_count = seed_report.count("\n| ") - 1  # subtract header row
                print(
                    f"Seed list written to: {args.seed}  ({unique_count} links, sorted by frequency)",
                    file=sys.stderr,
                )
        except OSError as exc:
            logger.error("Cannot write seed file: %s", exc)
            return 3

    return 0


if __name__ == "__main__":
    sys.exit(main())
