#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""add_diagrams — Insert ASCII / Mermaid diagrams into V6 permanent notes.

Scans the V6-elaborated permanent notes directory and, for each note that
has not yet been processed, asks a local Ollama model to generate 2–4
diagrams (a mix of ASCII art and Mermaid syntax) that visually represent
the core concept.  Each diagram is placed in a dedicated
``## 📊 Visual Overview`` section, inserted *immediately after* the YAML
frontmatter block and *before* the ``# Title`` heading so it is the first
thing a reader sees in Obsidian's reading view.

Diagram types generated per note
---------------------------------
- **1 Mermaid diagram** (mandatory) — captures the main structural or
  procedural relationship (flowchart, concept-map, sequence, mindmap, etc.)
- **1–3 ASCII diagrams** (mandatory) — capture supplementary views such as
  a data-flow overview, a comparison table, a state machine, or a
  component-boundary sketch.

Placement (inside the note file)
---------------------------------
::

    ---                          ← YAML frontmatter
    <fields>
    ---

    ## 📊 Visual Overview        ← INSERTED BY THIS SCRIPT
    <!-- diagram-pass:1 (2026-05-21) -->
    ...diagrams...

    # Title                      ← original note content begins here
    ...

Design principles (mirrors ``enhance_notes.py``)
--------------------------------------------------
- **Additive once.**  The script adds the diagram section exactly once
  (gate: ``provenance.diagram-passes == 0``).  Use ``--re-diagram`` to
  force a redo.
- **Idempotent.**  Unchanged notes hit the LLM cache; the sha1-content
  hash is part of the cache key.
- **Frontmatter-preserving.**  Only ``provenance.diagram-passes``,
  ``provenance.diagram-model``, ``provenance.last-diagrammed``, and
  ``updated`` are written.
- **Atomic writes.**  ``<file>.md.tmp → replace`` pattern; no half-written
  note ever exists on disk.

Usage:
    # Dry-run: preview diagram output for 3 notes; nothing written
    python add_diagrams.py --dry-run --limit 3 -v

    # Enhance a single note by stem substring
    python add_diagrams.py --note chain-of-thought

    # Full batch run (default: all un-diagrammed notes)
    python add_diagrams.py

    # Write to a side-by-side preview directory, originals untouched
    python add_diagrams.py --limit 20 --output-dir D:/diagrams-preview

    # Force redo + bypass cache
    python add_diagrams.py --note chain-of-thought --re-diagram --bypass-cache

Version:
    1.0.0
Python:
    >=3.10
Dependencies:
    - stdlib (argparse, dataclasses, datetime, hashlib, logging, pathlib, re, sys)
    - pydantic >= 2.0
    - requests (via lib.llm_client)
    - ruamel.yaml (via lib.frontmatter)
    - Optional: rich (progress bar)

Author:
    Generated by Python Script Designer & Generator — Expert v1.0.0
"""
from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import logging
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Literal

# ── sys.path injection: V3 lib, then V6 ───────────────────────────────────
_HERE = Path(__file__).resolve().parent
_V3_DIR = _HERE.parent / "report-extraction-to-permanent-notes-building-v3"
for _p in (_V3_DIR, _HERE):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

import config_v3                                               # noqa: E402
from lib.frontmatter import parse_frontmatter, render_frontmatter  # noqa: E402
from lib.llm_client import (                                   # noqa: E402
    LLMError,
    OllamaClient,
    OllamaUnavailableError,
    StructuredOutputError,
)
from pydantic import BaseModel, Field, field_validator         # noqa: E402

try:
    from rich.progress import (
        BarColumn,
        MofNCompleteColumn,
        Progress,
        SpinnerColumn,
        TextColumn,
        TimeElapsedColumn,
    )
    _RICH_AVAILABLE = True
except ImportError:  # pragma: no cover
    Progress = None  # type: ignore[assignment,misc]
    _RICH_AVAILABLE = False

logger = logging.getLogger(__name__)


# ════════════════════════════════════════════════════════════════════════════
# Constants
# ════════════════════════════════════════════════════════════════════════════

__version__ = "1.0.0"

#: Cache contract version.  Bump to invalidate every cached diagram run.
PROMPT_CONTRACT_VERSION: str = "diagrams-v3"

#: Default model — same 14B-q5_K_M used by the rest of the V6 pipeline.
DEFAULT_MODEL: str = "qwen2.5:14b-instruct-q5_K_M"

#: Default input directory — the v6-llm-elaborated note home.
DEFAULT_INPUT_DIR: Path = (
    config_v3.VAULT_ROOT
    / "999-report-organizing"
    / "_permanent-notes"
    / "v6-llm-elaborated"
)

#: Maximum characters of note body sent to the LLM as context.
MAX_BODY_CHARS: int = 5000

#: Header for the inserted diagram section (Obsidian-rendered as a section).
DIAGRAM_SECTION_HEADER: str = "## 📊 Visual Overview"

#: Obsidian-friendly note that ASCII diagrams need a fixed-width font.
ASCII_FONT_NOTE: str = (
    "*Best viewed with a monospace/fixed-width font in Obsidian's "
    "source or reading mode.*"
)


# ════════════════════════════════════════════════════════════════════════════
# Custom exceptions
# ════════════════════════════════════════════════════════════════════════════

class DiagramError(Exception):
    """Base exception for add_diagrams."""


class NoteParseError(DiagramError):
    """Raised when a note cannot be parsed (missing frontmatter, etc.)."""


class EmptyDiagramError(DiagramError):
    """Raised when the LLM returns no usable diagrams."""


# ════════════════════════════════════════════════════════════════════════════
# Pydantic schema for structured LLM output
# ════════════════════════════════════════════════════════════════════════════

class Diagram(BaseModel):
    """A single diagram: one Mermaid or one ASCII block."""

    diagram_type: Literal["mermaid", "ascii"] = Field(
        ...,
        description="'mermaid' for Mermaid.js syntax, 'ascii' for plain-text art.",
    )
    caption: str = Field(
        ...,
        min_length=4,
        max_length=120,
        description="Short title / label for the diagram (3–12 words).",
    )
    view_hint: str = Field(
        default="",
        max_length=200,
        description=(
            "One sentence on how to interpret this diagram — what the reader "
            "should look for, or how it connects to the concept."
        ),
    )
    content: str = Field(
        ...,
        min_length=10,
        description=(
            "The raw diagram text.  For 'mermaid': valid Mermaid.js syntax "
            "(no surrounding fences).  For 'ascii': plain-text art using "
            "box-drawing chars or standard ASCII."
        ),
    )

    @field_validator("content")
    @classmethod
    def _strip_code_fences(cls, v: str) -> str:
        """Remove accidental ``` fences the model may have added."""
        v = v.strip()
        # Strip opening fence (```mermaid, ```ascii, ``` etc.)
        v = re.sub(r"^```[a-zA-Z]*\n?", "", v)
        # Strip closing fence
        v = re.sub(r"\n?```$", "", v)
        return v.strip()

    @field_validator("caption", "view_hint")
    @classmethod
    def _clean_text(cls, v: str) -> str:
        return v.strip()


class DiagramResponse(BaseModel):
    """Structured diagram payload returned by the LLM."""

    diagrams: list[Diagram] = Field(
        default_factory=list,
        description="2–4 diagrams for this note.",
    )

    @field_validator("diagrams", mode="before")
    @classmethod
    def _coerce_null(cls, v: object) -> object:
        return [] if v is None else v

    def has_mermaid(self) -> bool:
        return any(d.diagram_type == "mermaid" for d in self.diagrams)

    def is_empty(self) -> bool:
        return len(self.diagrams) == 0 or all(
            not d.content.strip() for d in self.diagrams
        )


# ════════════════════════════════════════════════════════════════════════════
# Note data model
# ════════════════════════════════════════════════════════════════════════════

@dataclass(frozen=True)
class V6Note:
    """A parsed V6 permanent note ready for diagram generation."""

    path: Path
    title: str
    domain: str
    parent_concept: str
    frontmatter: dict[str, Any]
    body: str                   # full body text after YAML frontmatter
    diagram_passes: int         # provenance.diagram-passes (0 = never run)


@dataclass(frozen=True)
class DiagramResult:
    """Outcome of processing a single note."""

    note: V6Note
    ok: bool
    cached: bool
    response: DiagramResponse | None
    error: str | None = None
    written_path: Path | None = None


# ════════════════════════════════════════════════════════════════════════════
# Note loading
# ════════════════════════════════════════════════════════════════════════════

def _safe_str(v: Any, default: str = "") -> str:
    if v is None:
        return default
    if isinstance(v, list):
        return ", ".join(str(x) for x in v if x)
    return str(v)


def load_note(path: Path) -> V6Note:
    """Parse a V6 markdown note into a :class:`V6Note`.

    Raises:
        NoteParseError: On I/O error, empty file, or missing frontmatter.
    """
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as e:
        raise NoteParseError(f"Cannot read {path}: {e}") from e
    if not text.strip():
        raise NoteParseError(f"Empty file: {path}")
    try:
        fm, body = parse_frontmatter(text)
    except Exception as e:
        raise NoteParseError(f"Frontmatter parse failed for {path}: {e}") from e
    if not isinstance(fm, dict) or not fm:
        raise NoteParseError(f"Missing or non-mapping frontmatter: {path}")

    title = _safe_str(fm.get("title")) or path.stem.replace("-", " ").title()
    domain = _safe_str(fm.get("domain"), "general")
    parent = _safe_str(fm.get("parent-concept"), "")

    provenance = fm.get("provenance") or {}
    diagram_passes = 0
    if isinstance(provenance, dict):
        try:
            diagram_passes = int(provenance.get("diagram-passes", 0) or 0)
        except (TypeError, ValueError):
            diagram_passes = 0

    return V6Note(
        path=path,
        title=title,
        domain=domain,
        parent_concept=parent,
        frontmatter=dict(fm),
        body=body,
        diagram_passes=diagram_passes,
    )


def scan_notes(
    input_dir: Path,
    *,
    name_filter: str | None,
    re_diagram: bool,
    limit: int | None,
) -> list[V6Note]:
    """Discover candidate notes for diagram generation under ``input_dir``.

    Skips notes that already have ``provenance.diagram-passes >= 1`` unless
    ``re_diagram`` is True.

    Args:
        input_dir: Root directory to scan for ``*.md`` files.
        name_filter: Case-insensitive substring filter on filename stems.
        re_diagram: When True, include notes already processed.
        limit: Cap on the number of notes returned (for batch sizing).

    Returns:
        Sorted list of :class:`V6Note` candidates.

    Raises:
        FileNotFoundError: When ``input_dir`` does not exist.
    """
    if not input_dir.is_dir():
        raise FileNotFoundError(f"Input directory not found: {input_dir}")
    notes: list[V6Note] = []
    for path in sorted(input_dir.glob("*.md")):
        if name_filter and name_filter.lower() not in path.stem.lower():
            continue
        try:
            note = load_note(path)
        except NoteParseError as e:
            logger.warning("Skipping unparseable note %s: %s", path.name, e)
            continue
        if not re_diagram and note.diagram_passes >= 1:
            logger.debug("Skipping %s — already diagrammed", path.name)
            continue
        notes.append(note)
        if limit is not None and len(notes) >= limit:
            break
    return notes


# ════════════════════════════════════════════════════════════════════════════
# LLM prompts
# ════════════════════════════════════════════════════════════════════════════

_SYSTEM_PROMPT = """\
You are a visual knowledge architect for an Obsidian-based Personal Knowledge
Base (PKB). Your task is to generate 2–3 Mermaid diagrams for a permanent note.

DIAGRAM RULES
=============
1. Generate exactly 2–3 Mermaid diagrams.  No ASCII diagrams.
2. Each diagram MUST visualise a DIFFERENT aspect of the concept:
   - Typical aspects: structural overview, process/algorithm flow, taxonomy /
     hierarchy, comparison table, mechanism, state machine,
     component relationships, input→output data-flow.
3. Mermaid diagrams MUST use valid Mermaid.js syntax.  Preferred diagram types:
   - flowchart LR / TD   — for processes and flows
   - graph TD            — for concept hierarchies / trees
   - sequenceDiagram     — for interaction / pipeline sequences
   - classDiagram        — for taxonomy or type relationships
   - stateDiagram-v2     — for state machines
   Do NOT use ``timeline``, ``xychart-beta``, or ``mindmap`` (poor support).
4. CRITICAL — NEWLINES IN MERMAID: Every node declaration and every edge MUST
   be on its OWN LINE.  Never put multiple statements on the same line.
   CORRECT:
     flowchart LR
       A[Start] --> B[Process]
       B --> C[End]
   WRONG (will break rendering):
     flowchart LR A[Start] --> B[Process] B --> C[End]
5. Keep node labels concise (≤ 30 chars).  NEVER use parentheses `( )` inside
   square-bracket labels like `A[Foo (Bar)]` — Mermaid parses `(` as a shape
   operator and will fail to render.  If parentheses are needed in a label,
   use double-quotes: `A["Foo (Bar)"]`.
6. Caption must be 3–12 words, specific (not generic like "Concept Overview").
7. view_hint must explain what the reader should notice / how to read the diagram.
8. NO surrounding code fences in the ``content`` field — the renderer adds them.

Return ONLY valid JSON matching the schema — no markdown, no preamble, no commentary.
"""

_USER_PROMPT_TEMPLATE = """\
Generate 2–3 Mermaid diagrams for the permanent note below.

Title:           {title}
Domain:          {domain}
Parent concept:  {parent}

=== NOTE BODY (use this as the source of truth for the diagrams) ===
{body_excerpt}
=== END NOTE BODY ===

Return JSON:
{{
  "diagrams": [
    {{
      "diagram_type": "mermaid",
      "caption": "<specific 3–12 word label>",
      "view_hint": "<one sentence on how to read this diagram>",
      "content": "<valid Mermaid.js — NO fences — each statement on its own line>"
    }},
    {{
      "diagram_type": "mermaid",
      "caption": "<specific 3–12 word label for a DIFFERENT aspect>",
      "view_hint": "<one sentence on how to read this diagram>",
      "content": "<valid Mermaid.js — NO fences — each statement on its own line>"
    }}
  ]
}}

CRITICAL: In every content field, each Mermaid statement MUST be on its own
line separated by \\n.  Example of correct content value:
  "flowchart LR\\n  A[Input] --> B[Process]\\n  B --> C[Output]"

Constraints:
- 2–3 mermaid diagrams only; no ascii.
- Each diagram covers a DIFFERENT aspect of the concept.
- Every content field must be non-empty and diagram-ready.
- Do NOT wrap content in code fences.
- JSON only — no commentary.
"""


def _body_excerpt(body: str, max_chars: int = MAX_BODY_CHARS) -> str:
    """Return a truncated body suitable for inclusion in the LLM prompt.

    Args:
        body: Full note body text.
        max_chars: Character budget before truncation.

    Returns:
        Stripped body, truncated at a paragraph boundary if over budget.
    """
    body = body.strip()
    if len(body) <= max_chars:
        return body
    # Truncate at the last paragraph boundary within budget.
    cut = body[:max_chars].rfind("\n\n")
    if cut > max_chars // 2:
        return body[:cut].rstrip() + "\n\n[... truncated for context ...]"
    return body[:max_chars].rstrip() + "\n\n[... truncated for context ...]"


def _build_user_prompt(note: V6Note) -> str:
    return _USER_PROMPT_TEMPLATE.format(
        title=note.title,
        domain=note.domain or "general",
        parent=note.parent_concept or "(none specified)",
        body_excerpt=_body_excerpt(note.body),
    )


# ════════════════════════════════════════════════════════════════════════════
# LLM call
# ════════════════════════════════════════════════════════════════════════════

def _body_hash(body: str) -> str:
    """Stable 16-char content fingerprint used in the cache key."""
    return hashlib.sha1(body.encode("utf-8")).hexdigest()[:16]


def diagram_one(
    note: V6Note,
    client: OllamaClient,
    *,
    model: str,
    bypass_cache: bool,
) -> DiagramResult:
    """Run a single LLM diagram pass for ``note``.

    Args:
        note: The parsed V6 note to diagram.
        client: An active :class:`OllamaClient` instance.
        model: Ollama model name override.
        bypass_cache: When True, skip the LLM response cache.

    Returns:
        :class:`DiagramResult` with ``ok=True`` when diagrams were generated.
    """
    user_prompt = _build_user_prompt(note)
    cache_key_inputs = (
        PROMPT_CONTRACT_VERSION,
        model,
        note.title,
        _body_hash(note.body),
    )
    try:
        rsp = client.chat_json(
            system=_SYSTEM_PROMPT,
            user=user_prompt,
            schema=DiagramResponse,
            cache_key_inputs=cache_key_inputs,
            model=model,
            bypass_cache=bypass_cache,
        )
    except StructuredOutputError as e:
        return DiagramResult(
            note=note, ok=False, cached=False, response=None,
            error=f"Schema validation failed: {e}",
        )
    except OllamaUnavailableError:
        raise   # bubble up — pipeline-level failure
    except LLMError as e:
        return DiagramResult(
            note=note, ok=False, cached=False, response=None,
            error=f"LLM error: {e}",
        )

    response: DiagramResponse = rsp.parsed  # type: ignore[assignment]
    if response.is_empty():
        return DiagramResult(
            note=note, ok=False, cached=rsp.cached, response=response,
            error="LLM returned no usable diagrams",
        )
    return DiagramResult(
        note=note, ok=True, cached=rsp.cached, response=response, error=None,
    )


# ════════════════════════════════════════════════════════════════════════════
# Diagram rendering
# ════════════════════════════════════════════════════════════════════════════

def _fix_bare_arrows(content: str) -> str:
    """Join split arrow lines where the LLM put the target node on the next line.

    Some models emit::

        A -->|Relies on|
          B[Node]

    which is invalid Mermaid syntax.  This joins such pairs into::

        A -->|Relies on| B[Node]

    The fix is applied line-by-line.  A line qualifies as a "bare arrow" when
    it ends with an edge operator (``-->``, ``-->|label|``, ``---``, etc.) and
    contains no closing shape bracket after the operator.  The following
    non-blank line must look like a node reference and must *not* itself
    contain an arrow operator (to avoid accidentally merging two real arrows).

    Args:
        content: Raw mermaid content string (no fences).

    Returns:
        Content with split arrow lines joined.
    """
    # Matches a line whose last non-whitespace is an arrow tail:
    #   optional leading whitespace, some non-newline, then arrow-style ending.
    _bare = re.compile(
        r"^([ \t]*\S[^\n]*?(?:--[>\-xo]+>?|\.\.\.|==>)(?:\|[^|\n]*\|)?)\s*$"
    )
    # Matches lines that contain an arrow (so we don't merge two real arrows).
    _has_arrow = re.compile(r"--[>\-xo]|\.\.\.>|==>")

    lines = content.splitlines()
    result: list[str] = []
    i = 0
    while i < len(lines):
        line = lines[i]
        m = _bare.match(line)
        if m:
            # Peek ahead, skipping any blank lines in between.
            j = i + 1
            while j < len(lines) and not lines[j].strip():
                j += 1
            if j < len(lines):
                nxt = lines[j]
                if nxt.strip() and not _has_arrow.search(nxt):
                    # Merge: arrow line + target line.
                    result.append(line.rstrip() + " " + nxt.strip())
                    i = j + 1
                    continue
        result.append(line)
        i += 1
    return "\n".join(result)


def _fix_mermaid_content(content: str) -> str:
    """Best-effort fix for LLM-produced malformed Mermaid content.

    Applies several targeted fixups in order, then handles the rarer case of
    a completely one-liner output:

    1. **Bare-arrow join** — ``A -->|label|\\n  B`` → ``A -->|label| B``
       (some models emit the arrow and its target node on separate lines).
    2. **Participant bracket** — ``participant X[Label]`` →
       ``participant X as Label`` (sequence-diagram syntax error).
    3. **Single-quoted labels** — ``B['text']`` → ``B["text"]``
       (Mermaid only accepts double-quoted strings).
    4. **Paren-in-brackets quoting** — ``A[Node (detail)]`` →
       ``A["Node (detail)"]`` (parentheses inside ``[]`` break Mermaid's
       shape parser; applies to ALL content, not just one-liners).
    5. **One-liner re-split** — when the entire diagram is collapsed onto one
       line the diagram-type header and node boundaries are split out.

    Args:
        content: Raw mermaid content string (no fences, no callout ``> `` prefix).

    Returns:
        Content with each logical statement on its own line and known syntax
        issues resolved.
    """
    content = content.strip()

    # ── Fix 1: bare arrows (multi-line content — must run before early-return) ──
    # Only pay the line-splitting cost when the signature pattern is present.
    if re.search(r"--[>\-xo]+>?(?:\|[^|\n]*\|)?\s*$", content, re.MULTILINE):
        content = _fix_bare_arrows(content)

    # ── Fix 2: participant X[Y] → participant X as Y ──────────────────────────
    content = re.sub(
        r"participant\s+(\w+)\[([^\]]+)\]",
        r"participant \1 as \2",
        content,
    )

    # ── Fix 3: ['single-quoted labels'] → ["double-quoted labels"] ───────────
    content = re.sub(r"\['([^']+)'\]", r'["\1"]', content)

    # ── Fix 4: [label with (parens)] → ["label with (parens)"] ──────────────
    # e.g.  A[Scale Factor a(t)]  →  A["Scale Factor a(t)"]
    # Mermaid treats '(' inside '[]' as a shape operator — must run on ALL
    # content (multi-line and one-liner alike).
    content = re.sub(
        r"\[([^\]\"]*\([^)]*\)[^\]\"'.]*)\]",
        r'["\1"]',
        content,
    )

    # ── Early-return for well-formed multi-line content ───────────────────────
    # Fix 5 only makes sense for degenerate one-liner LLM output.
    if content.count("\n") >= 2:
        return content

    # ── Fix 5: split one-liner — diagram-type header from first node ──────────
    content = re.sub(
        r"^((?:flowchart|graph|sequenceDiagram|classDiagram|stateDiagram-v2?|erDiagram)\s*\S*)\s+",
        r"\1\n",
        content,
    )
    # Insert newline before any bare node ID that starts a new statement:
    # pattern = closing bracket/paren/brace + whitespace + word-char followed
    # by either a shape opener OR an edge operator.
    content = re.sub(
        r"([\]\)\}])\s+(?=[A-Za-z_]\w*(?:\s*[\[\(\{]|\s+-->|\s+---|\.\.\.>))",
        r"\1\n",
        content,
    )

    return content


def _render_diagram_block(diagram: Diagram, index: int) -> str:
    """Render a single :class:`Diagram` into Obsidian-ready markdown.

    Mermaid diagrams are placed inside a ``[!abstract]`` callout block that
    wraps the fenced code block — this is the most compatible layout for
    Obsidian ≥1.5.  ASCII diagrams use a plain code block (triple backticks)
    with a preceding caption line to keep them readable.

    Args:
        diagram: The diagram to render.
        index: 1-based position counter (used for heading label).

    Returns:
        A self-contained markdown string for this diagram.
    """
    label = f"Diagram {index} — {diagram.caption}"
    hint_line = f"> *{diagram.view_hint.strip()}*\n>\n" if diagram.view_hint.strip() else ""

    if diagram.diagram_type == "mermaid":
        # Obsidian renders Mermaid inside callout bodies as of v1.5+.
        # The nested code fence uses 4 backticks so the 3-backtick mermaid
        # fence does not close the outer callout prematurely.
        # _fix_mermaid_content handles rare LLM one-liner outputs.
        mermaid_content = _fix_mermaid_content(diagram.content)
        return (
            f"> [!abstract] **{label}**\n"
            f"{hint_line}"
            f"> ```mermaid\n"
            + "\n".join(f"> {line}" for line in mermaid_content.splitlines())
            + "\n> ```\n"
        )
    else:
        # ASCII: plain fenced block with caption above.
        return (
            f"**{label}**\n\n"
            f"{ASCII_FONT_NOTE}\n\n"
            + (f"*{diagram.view_hint.strip()}*\n\n" if diagram.view_hint.strip() else "")
            + "```\n"
            + diagram.content
            + "\n```\n"
        )


def build_diagram_section(
    response: DiagramResponse,
    *,
    pass_n: int,
    today: str,
) -> str:
    """Assemble the complete ``## 📊 Visual Overview`` section string.

    Args:
        response: Validated :class:`DiagramResponse` from the LLM.
        pass_n: Pass number stamped into the HTML marker comment.
        today: ISO-8601 date string for the marker.

    Returns:
        A markdown string starting with the section header, ready to prepend
        to the note body.
    """
    marker = f"<!-- diagram-pass:{pass_n} ({today}) -->"
    parts: list[str] = [DIAGRAM_SECTION_HEADER, "", marker, ""]
    for i, diagram in enumerate(response.diagrams, start=1):
        parts.append(_render_diagram_block(diagram, i))
        parts.append("")
    return "\n".join(parts)


# ════════════════════════════════════════════════════════════════════════════
# Body insertion
# ════════════════════════════════════════════════════════════════════════════

#: Matches the YAML frontmatter closing fence at the very start of the body.
_LEADING_WHITESPACE_RE = re.compile(r"^\s+")


def insert_diagram_section(body: str, diagram_section: str) -> str:
    """Insert ``diagram_section`` between the frontmatter and the ``# Title``.

    ``body`` is the text *after* ``parse_frontmatter()`` strips the YAML
    block, so it starts with optional whitespace then the ``# Title`` heading.
    The diagram section is prepended before the title heading.

    Args:
        body: The note body without YAML frontmatter.
        diagram_section: The rendered diagram section string.

    Returns:
        The updated body with the diagram section inserted at the top.

    Example:
        >>> insert_diagram_section("\\n# My Title\\n...", "## Diagrams\\n...")
        '## Diagrams\\n...\\n\\n# My Title\\n...'
    """
    stripped = body.lstrip("\n")
    return diagram_section.rstrip("\n") + "\n\n" + stripped


# ════════════════════════════════════════════════════════════════════════════
# Frontmatter update
# ════════════════════════════════════════════════════════════════════════════

def update_frontmatter(
    fm: dict[str, Any],
    *,
    pass_n: int,
    model: str,
    today: str,
) -> dict[str, Any]:
    """Return a new frontmatter dict with diagram provenance fields applied.

    Only writes/updates provenance sub-fields and ``updated``; all
    user-editable fields (``status``, ``tags``, ``aliases``, ``importance``,
    etc.) are left untouched.

    Args:
        fm: Existing parsed frontmatter dict.
        pass_n: Current diagram pass number (usually 1).
        model: Ollama model name used for the diagrams.
        today: ISO-8601 date string.

    Returns:
        A shallow copy of ``fm`` with diagram provenance applied.
    """
    out = dict(fm)
    out["updated"] = today
    provenance = dict(out.get("provenance") or {})
    provenance["diagram-passes"] = pass_n
    provenance["diagram-model"] = model
    provenance["last-diagrammed"] = today
    out["provenance"] = provenance
    return out


# ════════════════════════════════════════════════════════════════════════════
# File write
# ════════════════════════════════════════════════════════════════════════════

def write_note_atomic(path: Path, content: str) -> None:
    """Atomic write via ``.tmp → replace`` to avoid partial file states.

    Args:
        path: Destination file path.
        content: Full UTF-8 content to write.

    Raises:
        OSError: When the write or rename fails.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    tmp.replace(path)


# ════════════════════════════════════════════════════════════════════════════
# Orchestration
# ════════════════════════════════════════════════════════════════════════════

@dataclass
class RunStats:
    """Aggregate counters for a batch run."""

    scanned: int = 0
    diagrammed: int = 0
    cached: int = 0
    skipped_empty: int = 0
    failed: int = 0
    written: int = 0


def diagram_all(
    notes: list[V6Note],
    client: OllamaClient,
    *,
    model: str,
    bypass_cache: bool,
    dry_run: bool,
    output_dir: Path | None,
    input_dir: Path,
) -> tuple[list[DiagramResult], RunStats]:
    """Run diagram generation across all ``notes``.

    Args:
        notes: Pre-scanned candidates (from :func:`scan_notes`).
        client: Active :class:`OllamaClient`.
        model: Ollama model name.
        bypass_cache: When True, ignore the LLM response cache.
        dry_run: When True, compute but do not write anything to disk.
        output_dir: Optional mirror directory for output files.  When
            ``None``, notes are overwritten in place.
        input_dir: Original input directory (used to compute relative paths
            when ``output_dir`` is set).

    Returns:
        ``(results, stats)`` — the list of per-note outcomes and aggregate
        counters.
    """
    stats = RunStats(scanned=len(notes))
    results: list[DiagramResult] = []
    today = dt.date.today().isoformat()
    progress_ctx, advance = _make_progress(len(notes))

    with progress_ctx as progress:
        task_id = (
            progress.add_task("Diagramming", total=len(notes))
            if progress else None
        )
        for note in notes:
            try:
                result = diagram_one(
                    note, client, model=model, bypass_cache=bypass_cache,
                )
            except OllamaUnavailableError:
                logger.error("Ollama unavailable — aborting run")
                raise
            except Exception as e:  # defensive catch for unexpected errors
                logger.exception("Unexpected error diagramming %s", note.path.name)
                result = DiagramResult(
                    note=note, ok=False, cached=False, response=None,
                    error=f"unexpected: {e}",
                )

            if not result.ok or result.response is None:
                if result.error == "LLM returned no usable diagrams":
                    stats.skipped_empty += 1
                    logger.warning("No diagrams for %s: %s", note.path.name, result.error)
                else:
                    stats.failed += 1
                    logger.error("Failed %s: %s", note.path.name, result.error)
                results.append(result)
                advance(progress, task_id)
                continue

            if result.cached:
                stats.cached += 1
            stats.diagrammed += 1

            pass_n = note.diagram_passes + 1
            diagram_section = build_diagram_section(
                result.response, pass_n=pass_n, today=today,
            )
            # Strip any pre-existing diagram section before inserting the new
            # one — ensures re-diagram runs (pass ≥ 2) don't double-up blocks.
            clean_body = re.sub(
                r"## 📊 Visual Overview[\s\S]*?(?=\n# |\Z)", "", note.body,
            )
            new_body = insert_diagram_section(clean_body, diagram_section)
            new_fm = update_frontmatter(
                note.frontmatter, pass_n=pass_n, model=model, today=today,
            )
            new_content = render_frontmatter(new_fm) + "\n" + new_body

            dest = _resolve_output_path(note.path, input_dir, output_dir)
            if not dry_run:
                try:
                    write_note_atomic(dest, new_content)
                    stats.written += 1
                    logger.info(
                        "Diagrammed %s (pass %d, %s)",
                        note.path.name, pass_n,
                        "cache-hit" if result.cached else "live",
                    )
                except OSError as e:
                    logger.error("Write failed for %s: %s", dest, e)
                    stats.failed += 1
                    results.append(DiagramResult(
                        note=note, ok=False, cached=result.cached,
                        response=result.response, error=f"write failed: {e}",
                    ))
                    advance(progress, task_id)
                    continue
            else:
                logger.info(
                    "Would diagram %s (pass %d, %s)",
                    note.path.name, pass_n,
                    "cache-hit" if result.cached else "live",
                )

            results.append(DiagramResult(
                note=note, ok=True, cached=result.cached,
                response=result.response, error=None, written_path=dest,
            ))
            advance(progress, task_id)

    return results, stats


def _resolve_output_path(
    src: Path,
    input_dir: Path,
    output_dir: Path | None,
) -> Path:
    """Compute the destination path for a note.

    Args:
        src: Source note path.
        input_dir: Root of the input scan.
        output_dir: Optional override destination root.

    Returns:
        ``src`` when ``output_dir`` is ``None`` (in-place overwrite),
        otherwise ``output_dir / relative_path``.
    """
    if output_dir is None:
        return src
    try:
        rel = src.relative_to(input_dir)
    except ValueError:
        rel = Path(src.name)
    return output_dir / rel


def _make_progress(total: int):
    """Return ``(context_manager, advance_fn)``.  No-op when rich is absent."""
    if not _RICH_AVAILABLE or total == 0:
        from contextlib import nullcontext

        def _noop(_p, _t) -> None:  # noqa: ANN001
            return None

        return nullcontext(None), _noop

    progress = Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        BarColumn(),
        MofNCompleteColumn(),
        TimeElapsedColumn(),
    )

    def _advance(p, t) -> None:
        if p is not None and t is not None:
            p.advance(t)

    return progress, _advance


# ════════════════════════════════════════════════════════════════════════════
# CLI
# ════════════════════════════════════════════════════════════════════════════

def build_parser() -> argparse.ArgumentParser:
    """Construct the command-line argument parser.

    Returns:
        A fully configured :class:`argparse.ArgumentParser`.
    """
    parser = argparse.ArgumentParser(
        prog="add_diagrams",
        description=(
            "Insert ASCII / Mermaid diagrams into V6 permanent notes using a "
            "local Ollama model.  Diagrams are placed immediately after the "
            "YAML frontmatter and before the note title."
        ),
        epilog=(
            "Examples:\n"
            "  add_diagrams.py --dry-run --limit 5 -v\n"
            "      Preview diagrams for 5 notes; nothing written.\n"
            "  add_diagrams.py --note chain-of-thought\n"
            "      Add diagrams to the single note matching 'chain-of-thought'.\n"
            "  add_diagrams.py --limit 100\n"
            "      Process the next 100 un-diagrammed notes.\n"
            "  add_diagrams.py --output-dir D:/diagrams-preview\n"
            "      Mirror output to a preview dir; originals untouched.\n"
            "  add_diagrams.py --note schema-theory --re-diagram --bypass-cache\n"
            "      Force a fresh live LLM run, ignoring pass cap and cache.\n"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--input-dir", type=Path, default=DEFAULT_INPUT_DIR,
        help=f"Directory of V6 notes (default: {DEFAULT_INPUT_DIR})",
    )
    parser.add_argument(
        "--output-dir", type=Path, default=None,
        help="Mirror output to this dir instead of overwriting in place.",
    )
    parser.add_argument(
        "--note", type=str, default=None, metavar="SUBSTR",
        help="Filter notes by filename-stem substring (case-insensitive).",
    )
    parser.add_argument(
        "--limit", type=int, default=None, metavar="N",
        help="Cap on the number of notes to process (use ~100 for typical batches).",
    )
    parser.add_argument(
        "--re-diagram", action="store_true",
        help="Process notes that already have diagrams (ignore pass-count gate).",
    )
    parser.add_argument(
        "--bypass-cache", action="store_true",
        help="Force live LLM calls; ignore the response cache.",
    )
    parser.add_argument(
        "--model", type=str, default=DEFAULT_MODEL, metavar="NAME",
        help=f"Ollama model name (default: {DEFAULT_MODEL})",
    )
    parser.add_argument(
        "-n", "--dry-run", action="store_true",
        help="Run LLM and print what would be written; make no file changes.",
    )
    parser.add_argument(
        "--strict", action="store_true",
        help="Exit non-zero when any note fails.",
    )
    parser.add_argument(
        "-v", "--verbose", action="count", default=0,
        help="Increase log verbosity (-v = INFO, -vv = DEBUG).",
    )
    parser.add_argument(
        "-q", "--quiet", action="store_true",
        help="Suppress non-error output.",
    )
    parser.add_argument(
        "--version", action="version", version=f"%(prog)s {__version__}",
    )
    return parser


def configure_logging(verbosity: int, quiet: bool) -> None:
    """Set root logger level based on CLI verbosity flags.

    Args:
        verbosity: Count of ``-v`` flags (0 = WARNING, 1 = INFO, 2+ = DEBUG).
        quiet: When True, suppress output below ERROR.
    """
    if quiet:
        level = logging.ERROR
    elif verbosity >= 2:
        level = logging.DEBUG
    elif verbosity == 1:
        level = logging.INFO
    else:
        level = logging.WARNING
    logging.basicConfig(
        level=level,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )


def main(argv: list[str] | None = None) -> int:
    """Main entry point for the diagram-generation pipeline.

    Args:
        argv: Argument vector (defaults to ``sys.argv[1:]``).

    Returns:
        Exit code: 0 = success, 1 = unexpected error, 2 = input dir not found,
        4 = no notes found, 5 = strict mode with failures, 6 = Ollama unavailable,
        130 = interrupted.
    """
    parser = build_parser()
    args = parser.parse_args(argv)
    configure_logging(args.verbose, args.quiet)

    # ── Discover notes ────────────────────────────────────────────────────
    try:
        notes = scan_notes(
            args.input_dir,
            name_filter=args.note,
            re_diagram=args.re_diagram,
            limit=args.limit,
        )
    except FileNotFoundError as e:
        logger.error("%s", e)
        return 2

    if not notes:
        logger.warning(
            "No eligible notes found in %s (filter=%r, re_diagram=%s).",
            args.input_dir, args.note, args.re_diagram,
        )
        return 4

    logger.info(
        "Found %d note(s) to diagram%s.",
        len(notes),
        " (dry-run — no files will be written)" if args.dry_run else "",
    )

    # ── Connect to Ollama ─────────────────────────────────────────────────
    try:
        client = OllamaClient(
            url=config_v3.OLLAMA_URL,
            model=args.model,
            cache_dir=config_v3.LLM_CACHE_DIR,
        )
    except Exception as e:
        logger.error("Failed to initialise Ollama client: %s", e)
        return 6

    # ── Run diagram pipeline ──────────────────────────────────────────────
    try:
        results, stats = diagram_all(
            notes,
            client,
            model=args.model,
            bypass_cache=args.bypass_cache,
            dry_run=args.dry_run,
            output_dir=args.output_dir,
            input_dir=args.input_dir,
        )
    except OllamaUnavailableError:
        logger.error(
            "Ollama is unreachable at %s. Start Ollama and retry.",
            config_v3.OLLAMA_URL,
        )
        return 6
    except KeyboardInterrupt:
        logger.warning("Interrupted by user.")
        return 130
    except Exception:
        logger.exception("Unexpected pipeline error.")
        return 1

    # ── Summary ───────────────────────────────────────────────────────────
    action = "Would diagram" if args.dry_run else "Diagrammed"
    logger.warning(
        "%s %d/%d notes (%d cached, %d written, %d failed, %d empty).",
        action,
        stats.diagrammed,
        stats.scanned,
        stats.cached,
        stats.written,
        stats.failed,
        stats.skipped_empty,
    )

    if args.strict and stats.failed > 0:
        return 5
    return 0


# ════════════════════════════════════════════════════════════════════════════
# Entry-point guard
# ════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    sys.exit(main())
