#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""enhance_notes — Additive LLM enrichment for existing V6 permanent notes.

Takes a directory of already-elaborated V6 permanent notes and uses a local
Ollama model (default ``qwen2.5:14b-instruct-q5_K_M``) to *append* additional
material to each note: more explanation paragraphs, more practical-implication
callouts, more key distinctions (drawn from a curated catalogue — System 1/2,
declarative/procedural, working/long-term memory, etc.), common
misconceptions with corrections, more figures, more open questions,
mechanism prose, evidence narrative, a synthesis extension, and rationales
explaining WHY each connection in the Connections & Context section matters.

Design principles
-----------------
- **Additive only.** Existing prose is never rewritten. New content is
  appended within the appropriate ``##`` section, marked with an HTML
  comment ``<!-- enhanced-pass:N (YYYY-MM-DD) -->`` for traceability.
- **Idempotent.** A note already enhanced ``--max-passes`` times is
  skipped. Cache key includes the existing-note content hash, so unchanged
  notes hit the cache on re-runs.
- **Section-aware.** Body is parsed into H2 sections and re-assembled in
  the canonical V6 order. Missing sections (e.g. ``## Mechanism``) are
  inserted in the correct position when the LLM provides content.
- **Frontmatter-preserving.** Only fields owned by this script are updated:
  ``enhancement-passes``, ``updated``, ``maturity-stage`` (budding →
  evergreen after pass 2+), ``provenance.enhancement-*``. User-edited
  fields like ``status``, ``tags``, ``aliases``, ``importance`` are left
  untouched.
- **Atomic writes.** ``.tmp → replace`` pattern; ``--output-dir`` mirrors
  the input tree if you want a side-by-side diff.

Usage:
    # Dry-run preview of 3 notes
    python enhance_notes.py --dry-run --limit 3 -v

    # Real run, single note by stem-substring
    python enhance_notes.py --note schema-theory

    # Full run, all notes with fewer than 2 enhancement passes
    python enhance_notes.py --max-passes 2

    # Side-by-side preview (originals untouched)
    python enhance_notes.py --limit 20 --output-dir D:/v6-enhancement-preview

    # Force re-enhancement bypassing the pass-count gate and cache
    python enhance_notes.py --note schema-theory --re-enhance --bypass-cache

Version:
    1.0.0
Python:
    >=3.10
Dependencies:
    - stdlib (argparse, dataclasses, datetime, hashlib, logging, pathlib, re, sys)
    - pydantic >= 2.0
    - requests (via lib.llm_client)
    - ruamel.yaml (via lib.frontmatter)
    - Optional: rich (progress bar)

Author:
    Generated by Python Script Designer & Generator — Expert v1.0.0
"""
from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import logging
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

# ── sys.path injection: V3 lib first, then V6 ──────────────────────────
_HERE = Path(__file__).resolve().parent
_V3_DIR = _HERE.parent / "report-extraction-to-permanent-notes-building-v3"
for _p in (_V3_DIR, _HERE):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

import config_v3                                              # noqa: E402
from lib.frontmatter import parse_frontmatter, render_frontmatter  # noqa: E402
from lib.llm_client import (                                  # noqa: E402
    LLMError,
    OllamaClient,
    OllamaUnavailableError,
    StructuredOutputError,
)

from pydantic import BaseModel, Field, field_validator        # noqa: E402

try:
    from rich.progress import (
        BarColumn, MofNCompleteColumn, Progress, SpinnerColumn,
        TextColumn, TimeElapsedColumn,
    )
    _RICH_AVAILABLE = True
except ImportError:  # pragma: no cover
    Progress = None  # type: ignore[assignment,misc]
    _RICH_AVAILABLE = False


logger = logging.getLogger(__name__)


# ════════════════════════════════════════════════════════════════════════════
# Constants
# ════════════════════════════════════════════════════════════════════════════

__version__ = "1.1.0"

#: Cache contract version. Bump to invalidate every cached enhancement.
#: v2 — added curated key-distinction suggestions, connection rationales,
#:      and common-misconceptions fields to the LLM payload.
PROMPT_CONTRACT_VERSION: str = "enhance-v2"

#: Default model for enhancement. Standardised on the same 14B-q5_K_M as the
#: v3 creation/elaboration pipeline so creation and enhancement share one
#: model footprint (~10 GB VRAM, leaves headroom for context on a 4090).
DEFAULT_MODEL: str = "qwen2.5:14b-instruct-q5_K_M"

#: Default input directory — the v6-llm-elaborated note home.
DEFAULT_INPUT_DIR: Path = (
    config_v3.VAULT_ROOT
    / "999-report-organizing"
    / "_permanent-notes"
    / "v6-llm-elaborated"
)

#: Default cap on enhancement passes per note.
DEFAULT_MAX_PASSES: int = 1

#: Default directory for run reports (one .md per successful run).
DEFAULT_REPORT_DIR: Path = (
    config_v3.VAULT_ROOT
    / "999-report-organizing"
    / "_permanent-notes"
    / "enhanced-permanent-notes-reports"
)

#: Canonical V6 section order. Used to reassemble bodies and to insert
#: missing sections at the right position.
CANONICAL_SECTIONS: tuple[str, ...] = (
    "Core Explanation",
    "Mechanism",
    "Practical Implications",
    "Key Distinctions",
    "Common Misconceptions",
    "Key Figures",
    "Open Questions",
    "Synthesis",
    "Evidence",
    "Connections & Context",
)

#: Sections which the script may append to or create.
#: The Connections & Context section is appendable for *rationale* additions
#: (the original auto-generated relation list at the top of the section is
#: left untouched; rationales are appended below it under their own marker).
APPENDABLE_SECTIONS: frozenset[str] = frozenset({
    "Core Explanation",
    "Mechanism",
    "Practical Implications",
    "Key Distinctions",
    "Common Misconceptions",
    "Key Figures",
    "Open Questions",
    "Synthesis",
    "Evidence",
    "Connections & Context",
})

#: Curated catalogue of key-distinction patterns the LLM should consider
#: when relevant to the concept being enhanced. The LLM is instructed to
#: PICK ONLY those that genuinely apply — not to force-fit irrelevant ones.
KEY_DISTINCTION_SUGGESTIONS: tuple[str, ...] = (
    "System 1 vs System 2 Thinking (fast/automatic vs slow/deliberate)",
    "Declarative vs Procedural Knowledge (knowing-that vs knowing-how)",
    "Explicit vs Implicit Memory (conscious recall vs unconscious influence)",
    "Working Memory vs Long-Term Memory (limited transient vs durable storage)",
    "Reflective vs Reactive Thinking (deliberate review vs immediate response)",
    "Intrinsic vs Extraneous Load (task-inherent vs design-imposed difficulty)",
    "Surface vs Deep Processing (rote/perceptual vs semantic/elaborative)",
    "Recognition vs Recall (cued retrieval vs free retrieval)",
    "Convergent vs Divergent Thinking (single-answer vs many-answer)",
    "Top-Down vs Bottom-Up Processing (concept-driven vs data-driven)",
    "Assimilation vs Accommodation (fit-into-schema vs revise-schema)",
    "Massed vs Spaced Practice (blocked repetition vs distributed)",
    "Performance vs Learning (transient gains vs durable change)",
    "Transfer-Near vs Transfer-Far (similar-context vs novel-context application)",
    "Fixed vs Growth Mindset (ability-as-trait vs ability-as-developable)",
    "Intrinsic vs Extrinsic Motivation (internally vs externally driven)",
    "Maintenance vs Elaborative Rehearsal (looped repetition vs meaningful linking)",
    "Errors of Commission vs Omission (wrong action vs missing action)",
    "Type I vs Type II Error (false positive vs false negative)",
    "Map vs Territory (model/representation vs the thing itself)",
)


# ════════════════════════════════════════════════════════════════════════════
# Custom exceptions
# ════════════════════════════════════════════════════════════════════════════

class EnhanceError(Exception):
    """Base exception for enhance_notes."""


class NoteParseError(EnhanceError):
    """Raised when a note cannot be parsed (missing frontmatter, etc.)."""


class EmptyEnhancementError(EnhanceError):
    """Raised when the LLM returns nothing useful to add."""


# ════════════════════════════════════════════════════════════════════════════
# Pydantic schema for structured LLM output
# ════════════════════════════════════════════════════════════════════════════

class _Implication(BaseModel):
    scenario: str = Field(..., min_length=3, max_length=120)
    body: str = Field(..., min_length=40)


class _Distinction(BaseModel):
    title: str = Field(..., min_length=3, max_length=120)
    body: str = Field(..., min_length=30)


class _Figure(BaseModel):
    name: str = Field(..., min_length=2, max_length=120)
    contribution: str = Field(..., min_length=20)


class _Question(BaseModel):
    question: str = Field(..., min_length=10)
    resolution: str = Field(default="", max_length=600)


class _ConnectionRationale(BaseModel):
    """Why a specific related concept matters to this note.

    ``target`` should match (or be the wiki-link slug of) one of the related
    concepts already listed in the note's frontmatter / Connections section
    \u2014 the LLM is instructed to pick from those, not invent new ones.
    """
    target: str = Field(..., min_length=2, max_length=120)
    relation: str = Field(default="related-to", max_length=60)
    rationale: str = Field(..., min_length=40, max_length=600)


class _Misconception(BaseModel):
    misconception: str = Field(..., min_length=10, max_length=300)
    correction: str = Field(..., min_length=30, max_length=600)


class EnhancementResponse(BaseModel):
    """Structured additive enhancement payload from the LLM.

    Every field is optional \u2014 the model returns only what it has high-quality
    additions for. The post-validator guarantees that at least *something*
    was returned; otherwise the enhancement is treated as a no-op.
    """

    extra_explanation_paragraphs: list[str] = Field(default_factory=list)
    mechanism_addition: str | None = None
    extra_implications: list[_Implication] = Field(default_factory=list)
    extra_distinctions: list[_Distinction] = Field(default_factory=list)
    extra_figures: list[_Figure] = Field(default_factory=list)
    extra_questions: list[_Question] = Field(default_factory=list)
    synthesis_addition: str | None = None
    evidence_addition: str | None = None
    # v2 additions
    connection_rationales: list[_ConnectionRationale] = Field(default_factory=list)
    common_misconceptions: list[_Misconception] = Field(default_factory=list)

    @field_validator(
        "extra_explanation_paragraphs",
        "extra_implications",
        "extra_distinctions",
        "extra_figures",
        "extra_questions",
        "connection_rationales",
        "common_misconceptions",
        mode="before",
    )
    @classmethod
    def _coerce_null_to_empty_list(cls, v: object) -> object:
        # LLMs sometimes emit `null` for empty arrays; treat as [].
        return [] if v is None else v

    @field_validator("extra_explanation_paragraphs")
    @classmethod
    def _strip_blank_paragraphs(cls, v: list[str]) -> list[str]:
        return [p.strip() for p in v if p and p.strip()]

    def is_empty(self) -> bool:
        """True if no field carries new material."""
        return not any([
            self.extra_explanation_paragraphs,
            self.mechanism_addition and self.mechanism_addition.strip(),
            self.extra_implications,
            self.extra_distinctions,
            self.extra_figures,
            self.extra_questions,
            self.synthesis_addition and self.synthesis_addition.strip(),
            self.evidence_addition and self.evidence_addition.strip(),
            self.connection_rationales,
            self.common_misconceptions,
        ])


# ════════════════════════════════════════════════════════════════════════════
# Note model
# ════════════════════════════════════════════════════════════════════════════

@dataclass(frozen=True)
class V6Note:
    """A parsed V6 permanent note ready for enhancement."""
    path: Path
    title: str
    domain: str
    parent_concept: str
    aliases: list[str]
    frontmatter: dict[str, Any]
    body: str
    sections: dict[str, str]   # section name → body (without the "## name" header)
    enhancement_passes: int


@dataclass(frozen=True)
class EnhancementResult:
    note: V6Note
    ok: bool
    cached: bool
    response: EnhancementResponse | None
    error: str | None = None
    written_path: Path | None = None


# ════════════════════════════════════════════════════════════════════════════
# Section parsing
# ════════════════════════════════════════════════════════════════════════════

#: Match an H2 header. Captures the heading text.
_H2_RE = re.compile(r"^##\s+(.+?)\s*$", re.MULTILINE)


def _split_sections(body: str) -> tuple[str, dict[str, str]]:
    """Split a markdown body into (preamble, {section_name: section_body}).

    The preamble is everything before the first ``##`` header (typically
    the H1 title and the ``[!definition]`` callout). Section bodies do
    NOT include their own ``## Header`` line — only the content underneath,
    up to the next H2 or end of file.
    """
    matches = list(_H2_RE.finditer(body))
    if not matches:
        return body, {}
    preamble = body[: matches[0].start()].rstrip() + "\n"
    sections: dict[str, str] = {}
    for i, m in enumerate(matches):
        name = m.group(1).strip()
        start = m.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(body)
        sections[name] = body[start:end].strip("\n")
    return preamble, sections


def _reassemble(preamble: str, sections: dict[str, str]) -> str:
    """Rebuild a body from preamble + sections in canonical order.

    Sections not present in CANONICAL_SECTIONS are appended at the end in
    insertion order (preserves any custom sections the user may have added).
    """
    parts: list[str] = [preamble.rstrip(), ""]
    seen: set[str] = set()
    for name in CANONICAL_SECTIONS:
        if name in sections:
            parts.append(f"## {name}")
            parts.append("")
            parts.append(sections[name].strip("\n"))
            parts.append("")
            seen.add(name)
    for name, content in sections.items():
        if name in seen:
            continue
        parts.append(f"## {name}")
        parts.append("")
        parts.append(content.strip("\n"))
        parts.append("")
    return "\n".join(parts).rstrip() + "\n"


# ════════════════════════════════════════════════════════════════════════════
# Note loading
# ════════════════════════════════════════════════════════════════════════════

def _safe_str(v: Any, default: str = "") -> str:
    if v is None:
        return default
    if isinstance(v, list):
        return ", ".join(str(x) for x in v if x)
    return str(v)


def _safe_list(v: Any) -> list[str]:
    if v is None:
        return []
    if isinstance(v, list):
        return [str(x) for x in v if x]
    return [str(v)]


def load_note(path: Path) -> V6Note:
    """Parse a V6 permanent-note markdown file into a :class:`V6Note`.

    Raises:
        NoteParseError: When the file lacks YAML frontmatter or is empty.
    """
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as e:
        raise NoteParseError(f"Cannot read {path}: {e}") from e
    if not text.strip():
        raise NoteParseError(f"Empty file: {path}")
    try:
        fm, body = parse_frontmatter(text)
    except Exception as e:  # ruamel raises various error types
        raise NoteParseError(f"Frontmatter parse failed for {path}: {e}") from e
    if not isinstance(fm, dict) or not fm:
        raise NoteParseError(f"Missing or non-mapping frontmatter: {path}")
    title = _safe_str(fm.get("title")) or path.stem.replace("-", " ").title()
    domain = _safe_str(fm.get("domain"), "general")
    parent = _safe_str(fm.get("parent-concept"), "")
    aliases = _safe_list(fm.get("aliases"))
    provenance = fm.get("provenance") or {}
    passes = 0
    if isinstance(provenance, dict):
        try:
            passes = int(provenance.get("enhancement-passes", 0) or 0)
        except (TypeError, ValueError):
            passes = 0
    _, sections = _split_sections(body)
    return V6Note(
        path=path,
        title=title,
        domain=domain,
        parent_concept=parent,
        aliases=aliases,
        frontmatter=dict(fm),
        body=body,
        sections=sections,
        enhancement_passes=passes,
    )


def scan_notes(
    input_dir: Path,
    *,
    name_filter: str | None,
    max_passes: int,
    re_enhance: bool,
    limit: int | None,
) -> list[V6Note]:
    """Discover candidate notes for enhancement under ``input_dir``."""
    if not input_dir.is_dir():
        raise FileNotFoundError(f"Input directory not found: {input_dir}")
    notes: list[V6Note] = []
    files = sorted(input_dir.glob("*.md"))
    for path in files:
        if name_filter and name_filter.lower() not in path.stem.lower():
            continue
        try:
            note = load_note(path)
        except NoteParseError as e:
            logger.warning("Skipping unparseable note %s: %s", path.name, e)
            continue
        if not re_enhance and note.enhancement_passes >= max_passes:
            logger.debug(
                "Skipping %s — already enhanced %d/%d times",
                path.name, note.enhancement_passes, max_passes,
            )
            continue
        notes.append(note)
        if limit is not None and len(notes) >= limit:
            break
    return notes


# ════════════════════════════════════════════════════════════════════════════
# LLM prompts
# ════════════════════════════════════════════════════════════════════════════

SYSTEM_PROMPT = (
    "You are a meticulous academic knowledge-base author enriching an "
    "EXISTING permanent note in a Personal Knowledge Base. Your job is "
    "ADDITIVE: you write only NEW material that genuinely deepens the "
    "note. Do not restate, summarize, or rewrite anything already present. "
    "Do not invent biographical claims, citations, or empirical findings "
    "you are not confident about — omit rather than fabricate. Maintain a "
    "neutral scholarly tone matching the existing note. Reply with valid "
    "JSON only — no markdown fences, no preamble, no commentary."
)


_USER_PROMPT_TEMPLATE = """\
Enhance the following permanent note by adding NEW material that deepens it.

Title:           {title}
Domain:          {domain}
Parent concept:  {parent}
Aliases:         {aliases}

Existing related concepts (use these EXACT slugs as targets for
`connection_rationales`; do NOT invent new targets):
{related_concepts}

Key-distinction patterns you MAY draw on (pick only those that genuinely
apply to this concept; do not force-fit irrelevant ones; you may also
propose other distinctions not on this list if they are more apt):
{distinction_suggestions}

=== EXISTING NOTE BODY (DO NOT REPEAT THIS CONTENT) ===
{body_excerpt}
=== END EXISTING NOTE BODY ===

Return JSON with these OPTIONAL fields. Include a field only when you have
genuinely NEW, NON-REDUNDANT material for it. Empty arrays / null are fine.

{{
  "extra_explanation_paragraphs": [
    "1-3 NEW narrative paragraphs (80-180 words each) that add depth the "
    "existing Core Explanation does not cover (e.g. a different angle, a "
    "deeper mechanism, a historical-context paragraph, a contemporary "
    "research thread). Plain prose, no bullets, no headers."
  ],
  "mechanism_addition": "Optional 80-180 word paragraph elaborating the "
    "underlying mechanism. Add ONLY if the note's Mechanism section is "
    "missing or shallow.",
  "extra_implications": [
    {{"scenario": "Short scenario label (e.g. 'Spaced retrieval in MOOCs')",
      "body": "80-150 word concrete application body, scenario-anchored."}}
  ],
  "extra_distinctions": [
    {{"title": "X vs Y",
      "body": "60-120 word concrete contrast naming the two things, what "
              "specifically distinguishes them, and why the distinction "
              "matters for understanding {title}. Aim for 3-5 distinctions "
              "total when the note already has fewer than 3 — draw from the "
              "suggested patterns above when relevant. Do NOT duplicate any "
              "distinction already present in the existing note body."}}
  ],
  "common_misconceptions": [
    {{"misconception": "A common but incorrect belief about {title}, "
                       "stated as a single sentence (e.g. 'People think X "
                       "means Y, but...').",
      "correction": "60-150 word correction explaining what is actually "
                     "true and why the misconception arises. Anchor in the "
                     "concept's mechanism or empirical evidence."}}
  ],
  "connection_rationales": [
    {{"target": "slug-of-related-concept (must match one listed above)",
      "relation": "e.g. prerequisite | sibling | applies-to | contrasts-with | falls-under",
      "rationale": "60-150 word explanation of WHY this connection exists "
                    "— what specifically links {title} to the target, what "
                    "shared mechanism / dependency / contrast underlies the "
                    "link, and what a learner gains by following it. Avoid "
                    "generic phrasing like 'they are related concepts'."}}
  ],
  "extra_figures": [
    {{"name": "Person Name",
      "contribution": "30-80 word description of their specific contribution. "
                       "Omit unless you are confident this person worked on "
                       "this concept."}}
  ],
  "extra_questions": [
    {{"question": "A genuine open question or unresolved tension.",
      "resolution": "1-2 sentences on what evidence or work would resolve it."}}
  ],
  "synthesis_addition": "Optional 1 paragraph that ties the existing "
    "material together at a higher level OR positions the concept within "
    "its broader research programme.",
  "evidence_addition": "Optional 1 paragraph narrative summarising the "
    "empirical evidence base — meta-analyses, key replication results, or "
    "boundary conditions. Omit if you cannot do this confidently."
}}

Rules:
- ADDITIVE ONLY. Do not restate anything in the existing body above.
- Write in flowing prose. No markdown headers, no bullet lists inside fields.
- For `connection_rationales`, the `target` MUST be one of the related-concept
  slugs listed above — do not invent new targets.
- For `extra_distinctions`, prefer distinctions that are foundational to the
  concept's domain (e.g. cognitive-psychology notes benefit from System 1/2,
  declarative/procedural, working/long-term memory contrasts when applicable).
- Wiki-links of the form [[concept-name]] are encouraged inside prose where natural.
- JSON only. No code fences. No commentary.
"""


def _build_body_excerpt(note: V6Note, max_chars: int = 6000) -> str:
    """Compact representation of the existing note body for the prompt.

    The full body of dense V6 notes can exceed model context budgets when
    the prompt template + system prompt are added on top. We truncate
    section by section, preserving the heading structure so the model can
    see what it must NOT duplicate.
    """
    if len(note.body) <= max_chars:
        return note.body.strip()
    parts: list[str] = []
    budget = max_chars
    preamble, sections = _split_sections(note.body)
    if preamble.strip():
        snippet = preamble.strip()[:1500]
        parts.append(snippet)
        budget -= len(snippet)
    for name in CANONICAL_SECTIONS:
        if name not in sections or budget <= 200:
            continue
        body = sections[name].strip()
        snippet = body[: max(200, budget // max(1, len(sections)))]
        parts.append(f"## {name}\n{snippet}")
        budget -= len(snippet) + len(name) + 4
    return "\n\n".join(parts)


_RELATION_FIELDS: tuple[str, ...] = (
    "related", "prerequisites", "specializes", "broader", "see-also",
    "contrasts-with", "contradicts", "applies-to", "formalizes",
    "instance-of", "supports", "refines",
)

_WIKILINK_RE = re.compile(r"\[\[([^\]|#]+?)(?:#[^\]|]*)?(?:\|[^\]]*)?\]\]")


def _extract_related_concepts(fm: dict[str, Any]) -> list[tuple[str, str]]:
    """Extract (slug, relation_type) pairs from frontmatter relation fields.

    Empty placeholder targets like ``[[]]`` are filtered out. Duplicates
    (same slug under different relations) are kept since the relation type
    carries semantic meaning for rationale generation.
    """
    out: list[tuple[str, str]] = []
    seen: set[tuple[str, str]] = set()
    for field in _RELATION_FIELDS:
        raw = fm.get(field)
        if not raw:
            continue
        items = raw if isinstance(raw, list) else [raw]
        for item in items:
            s = str(item).strip()
            if not s:
                continue
            for m in _WIKILINK_RE.finditer(s):
                slug = m.group(1).strip()
                if not slug:
                    continue
                key = (slug, field)
                if key in seen:
                    continue
                seen.add(key)
                out.append(key)
            # Also accept bare slugs (no wiki-link wrapper)
            if "[[" not in s and s:
                key = (s, field)
                if key not in seen:
                    seen.add(key)
                    out.append(key)
    return out


def _build_user_prompt(note: V6Note) -> str:
    related = _extract_related_concepts(note.frontmatter)
    if related:
        related_str = "\n".join(
            f"  - {slug}  ({relation})" for slug, relation in related
        )
    else:
        related_str = "  (none listed in frontmatter)"
    distinction_str = "\n".join(f"  - {d}" for d in KEY_DISTINCTION_SUGGESTIONS)
    return _USER_PROMPT_TEMPLATE.format(
        title=note.title,
        domain=note.domain or "general",
        parent=note.parent_concept or "(none specified)",
        aliases=", ".join(note.aliases) if note.aliases else "(none)",
        related_concepts=related_str,
        distinction_suggestions=distinction_str,
        body_excerpt=_build_body_excerpt(note),
    )


# ════════════════════════════════════════════════════════════════════════════
# LLM call
# ════════════════════════════════════════════════════════════════════════════

def _body_hash(body: str) -> str:
    """Stable content fingerprint used in the cache key."""
    return hashlib.sha1(body.encode("utf-8")).hexdigest()[:16]


def enhance_one(
    note: V6Note,
    client: OllamaClient,
    *,
    model: str,
    bypass_cache: bool,
) -> EnhancementResult:
    """Run a single LLM enhancement pass against ``note``."""
    user_prompt = _build_user_prompt(note)
    cache_key_inputs = (
        PROMPT_CONTRACT_VERSION,
        model,
        note.title,
        _body_hash(note.body),
    )
    try:
        rsp = client.chat_json(
            system=SYSTEM_PROMPT,
            user=user_prompt,
            schema=EnhancementResponse,
            cache_key_inputs=cache_key_inputs,
            model=model,
            bypass_cache=bypass_cache,
        )
    except StructuredOutputError as e:
        return EnhancementResult(
            note=note, ok=False, cached=False, response=None,
            error=f"Schema validation failed: {e}",
        )
    except OllamaUnavailableError:
        raise   # bubble up — pipeline-level failure
    except LLMError as e:
        return EnhancementResult(
            note=note, ok=False, cached=False, response=None,
            error=f"LLM error: {e}",
        )
    response: EnhancementResponse = rsp.parsed  # type: ignore[assignment]
    if response.is_empty():
        return EnhancementResult(
            note=note, ok=False, cached=rsp.cached, response=response,
            error="LLM returned no new material",
        )
    return EnhancementResult(
        note=note, ok=True, cached=rsp.cached, response=response, error=None,
    )


# ════════════════════════════════════════════════════════════════════════════
# Section appenders
# ════════════════════════════════════════════════════════════════════════════

def _marker(pass_n: int, today: str) -> str:
    return f"<!-- enhancement-pass:{pass_n} ({today}) -->"


def _append_paragraphs(
    sections: dict[str, str],
    section_name: str,
    paragraphs: list[str],
    pass_n: int,
    today: str,
) -> bool:
    """Append plain-prose paragraphs to a section. Returns True if changed."""
    cleaned = [p.strip() for p in paragraphs if p and p.strip()]
    if not cleaned:
        return False
    block = "\n\n".join(cleaned)
    addition = f"\n\n{_marker(pass_n, today)}\n{block}\n"
    if section_name in sections:
        sections[section_name] = sections[section_name].rstrip() + addition
    else:
        sections[section_name] = addition.lstrip("\n")
    return True


def _append_implications(
    sections: dict[str, str],
    items: list[_Implication],
    existing_count: int,
    pass_n: int,
    today: str,
) -> bool:
    if not items:
        return False
    blocks: list[str] = [_marker(pass_n, today)]
    for i, imp in enumerate(items, start=existing_count + 1):
        body = imp.body.strip().replace("\n", "\n> ")
        blocks.append(
            f"> [!example] **Application {i} — {imp.scenario.strip()}**\n> {body}"
        )
    addition = "\n\n" + "\n\n".join(blocks) + "\n"
    section = "Practical Implications"
    if section in sections:
        sections[section] = sections[section].rstrip() + addition
    else:
        sections[section] = addition.lstrip("\n")
    return True


def _append_distinctions(
    sections: dict[str, str],
    items: list[_Distinction],
    pass_n: int,
    today: str,
) -> bool:
    if not items:
        return False
    blocks: list[str] = [_marker(pass_n, today)]
    for d in items:
        body = d.body.strip().replace("\n", "\n> ")
        blocks.append(
            f"> [!key-distinction] **{d.title.strip()}**\n> {body}"
        )
    addition = "\n\n" + "\n\n".join(blocks) + "\n"
    section = "Key Distinctions"
    if section in sections:
        sections[section] = sections[section].rstrip() + addition
    else:
        sections[section] = addition.lstrip("\n")
    return True


def _append_figures(
    sections: dict[str, str],
    items: list[_Figure],
    pass_n: int,
    today: str,
) -> bool:
    if not items:
        return False
    lines: list[str] = [_marker(pass_n, today)]
    for f in items:
        lines.append(f"- **{f.name.strip()}** — {f.contribution.strip()}")
    addition = "\n\n" + "\n".join(lines) + "\n"
    section = "Key Figures"
    if section in sections:
        sections[section] = sections[section].rstrip() + addition
    else:
        sections[section] = addition.lstrip("\n")
    return True


def _append_questions(
    sections: dict[str, str],
    items: list[_Question],
    pass_n: int,
    today: str,
) -> bool:
    if not items:
        return False
    blocks: list[str] = [_marker(pass_n, today)]
    for q in items:
        body_lines = [f"> {q.question.strip()}"]
        if q.resolution and q.resolution.strip():
            body_lines.append(">")
            body_lines.append(f"> *What would resolve it:* {q.resolution.strip()}")
        blocks.append("> [!open-question] **Question**\n" + "\n".join(body_lines))
    addition = "\n\n" + "\n\n".join(blocks) + "\n"
    section = "Open Questions"
    if section in sections:
        sections[section] = sections[section].rstrip() + addition
    else:
        sections[section] = addition.lstrip("\n")
    return True


def _append_misconceptions(
    sections: dict[str, str],
    items: list[_Misconception],
    pass_n: int,
    today: str,
) -> bool:
    """Append a Common Misconceptions section / block. Returns True if changed."""
    if not items:
        return False
    blocks: list[str] = [_marker(pass_n, today)]
    for m in items:
        misc = m.misconception.strip().rstrip(".") + "."
        correction = m.correction.strip().replace("\n", "\n> ")
        blocks.append(
            f"> [!warning] **Misconception** — {misc}\n>\n> {correction}"
        )
    addition = "\n\n" + "\n\n".join(blocks) + "\n"
    section = "Common Misconceptions"
    if section in sections:
        sections[section] = sections[section].rstrip() + addition
    else:
        sections[section] = addition.lstrip("\n")
    return True


def _append_connection_rationales(
    sections: dict[str, str],
    items: list[_ConnectionRationale],
    pass_n: int,
    today: str,
) -> bool:
    """Append a 'Why these connections matter' subsection to Connections & Context.

    The original auto-generated relation list (Falls under, Prerequisites, etc.)
    is preserved verbatim; rationales are appended below it under their own
    enhancement marker so they can be identified and rolled back.
    """
    if not items:
        return False
    blocks: list[str] = [
        _marker(pass_n, today),
        "### Why these connections matter",
    ]
    for c in items:
        target = c.target.strip().strip("[]")
        relation = (c.relation or "related-to").strip()
        rationale = c.rationale.strip().replace("\n", "\n> ")
        blocks.append(
            f"> [!connection] **[[{target}]]** — *{relation}*\n> {rationale}"
        )
    addition = "\n\n" + "\n\n".join(blocks) + "\n"
    section = "Connections & Context"
    if section in sections:
        sections[section] = sections[section].rstrip() + addition
    else:
        sections[section] = addition.lstrip("\n")
    return True


def merge_response(
    note: V6Note,
    response: EnhancementResponse,
    *,
    pass_n: int,
    today: str,
) -> tuple[str, dict[str, str]]:
    """Merge an EnhancementResponse into a copy of the note's sections.

    Returns:
        (preamble, updated_sections) ready for ``_reassemble``.
    """
    preamble, _ = _split_sections(note.body)
    sections: dict[str, str] = dict(note.sections)
    existing_implications = sections.get("Practical Implications", "").count(
        "[!example]"
    )

    _append_paragraphs(
        sections, "Core Explanation", response.extra_explanation_paragraphs,
        pass_n, today,
    )
    if response.mechanism_addition and response.mechanism_addition.strip():
        _append_paragraphs(
            sections, "Mechanism", [response.mechanism_addition], pass_n, today,
        )
    _append_implications(
        sections, response.extra_implications, existing_implications, pass_n, today,
    )
    _append_distinctions(sections, response.extra_distinctions, pass_n, today)
    _append_misconceptions(sections, response.common_misconceptions, pass_n, today)
    _append_figures(sections, response.extra_figures, pass_n, today)
    _append_questions(sections, response.extra_questions, pass_n, today)
    if response.synthesis_addition and response.synthesis_addition.strip():
        _append_paragraphs(
            sections, "Synthesis", [response.synthesis_addition], pass_n, today,
        )
    if response.evidence_addition and response.evidence_addition.strip():
        _append_paragraphs(
            sections, "Evidence", [response.evidence_addition], pass_n, today,
        )
    _append_connection_rationales(
        sections, response.connection_rationales, pass_n, today,
    )
    return preamble, sections


# ════════════════════════════════════════════════════════════════════════════
# Frontmatter update
# ════════════════════════════════════════════════════════════════════════════

def update_frontmatter(
    fm: dict[str, Any],
    *,
    pass_n: int,
    model: str,
    today: str,
) -> dict[str, Any]:
    """Return a new frontmatter dict with enhancement provenance applied.

    Preserves all user-editable fields. Only writes/updates:
        - updated
        - maturity-stage  (budding → evergreen after pass >= 2)
        - depth-level     ('elaborated' → 'enhanced')
        - provenance.enhancement-passes
        - provenance.enhancement-model
        - provenance.enhancement-method
        - provenance.last-enhanced
    """
    out = dict(fm)
    out["updated"] = today
    if pass_n >= 2 and out.get("maturity-stage") == "budding":
        out["maturity-stage"] = "evergreen"
    if out.get("depth-level") in (None, "", "elaborated"):
        out["depth-level"] = "enhanced"
    provenance = dict(out.get("provenance") or {})
    provenance["enhancement-passes"] = pass_n
    provenance["enhancement-model"] = model
    provenance["enhancement-method"] = "enhance_notes-v1"
    provenance["last-enhanced"] = today
    out["provenance"] = provenance
    return out


# ════════════════════════════════════════════════════════════════════════════
# File write
# ════════════════════════════════════════════════════════════════════════════

def write_note_atomic(path: Path, content: str) -> None:
    """Atomic write: ``.tmp`` then replace."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    tmp.replace(path)


# ════════════════════════════════════════════════════════════════════════════
# Orchestration
# ════════════════════════════════════════════════════════════════════════════

@dataclass
class RunStats:
    scanned: int = 0
    enhanced: int = 0
    cached: int = 0
    skipped_empty: int = 0
    failed: int = 0
    written: int = 0


def enhance_all(
    notes: list[V6Note],
    client: OllamaClient,
    *,
    model: str,
    bypass_cache: bool,
    dry_run: bool,
    output_dir: Path | None,
    input_dir: Path,
) -> tuple[list[EnhancementResult], RunStats]:
    """Enhance every note in ``notes``. Returns (results, stats)."""
    stats = RunStats(scanned=len(notes))
    results: list[EnhancementResult] = []
    today = dt.date.today().isoformat()
    progress_ctx, advance = _make_progress(len(notes))
    with progress_ctx as progress:
        task_id = progress.add_task("Enhancing", total=len(notes)) if progress else None
        for note in notes:
            try:
                result = enhance_one(
                    note, client, model=model, bypass_cache=bypass_cache,
                )
            except OllamaUnavailableError:
                logger.error("Ollama unavailable — aborting run")
                raise
            except Exception as e:  # defensive
                logger.exception("Unexpected error enhancing %s", note.path.name)
                result = EnhancementResult(
                    note=note, ok=False, cached=False, response=None,
                    error=f"unexpected: {e}",
                )

            if not result.ok or result.response is None:
                stats.failed += 1
                if result.error == "LLM returned no new material":
                    stats.skipped_empty += 1
                    stats.failed -= 1
                logger.warning(
                    "No enhancement for %s: %s", note.path.name, result.error,
                )
                results.append(result)
                advance(progress, task_id)
                continue

            if result.cached:
                stats.cached += 1
            stats.enhanced += 1

            pass_n = note.enhancement_passes + 1
            preamble, merged_sections = merge_response(
                note, result.response, pass_n=pass_n, today=today,
            )
            new_body = _reassemble(preamble, merged_sections)
            new_fm = update_frontmatter(
                note.frontmatter, pass_n=pass_n, model=model, today=today,
            )
            new_content = render_frontmatter(new_fm) + "\n" + new_body

            dest = _resolve_output_path(note.path, input_dir, output_dir)
            if not dry_run:
                try:
                    write_note_atomic(dest, new_content)
                    stats.written += 1
                except OSError as e:
                    logger.error("Write failed for %s: %s", dest, e)
                    stats.failed += 1
                    results.append(EnhancementResult(
                        note=note, ok=False, cached=result.cached,
                        response=result.response, error=f"write failed: {e}",
                    ))
                    advance(progress, task_id)
                    continue

            results.append(EnhancementResult(
                note=note, ok=True, cached=result.cached,
                response=result.response, error=None, written_path=dest,
            ))
            logger.info(
                "%s %s (pass %d, %s)",
                "Would enhance" if dry_run else "Enhanced",
                note.path.name, pass_n,
                "cache-hit" if result.cached else "live",
            )
            advance(progress, task_id)
    return results, stats


def _resolve_output_path(
    src: Path, input_dir: Path, output_dir: Path | None,
) -> Path:
    if output_dir is None:
        return src
    try:
        rel = src.relative_to(input_dir)
    except ValueError:
        rel = Path(src.name)
    return output_dir / rel


def _make_progress(total: int):
    """Return (context_manager, advance_fn). No-op when rich is missing."""
    if not _RICH_AVAILABLE or total == 0:
        from contextlib import nullcontext

        def _noop(_p, _t):  # noqa: ANN001
            return None
        return nullcontext(None), _noop

    progress = Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        BarColumn(),
        MofNCompleteColumn(),
        TimeElapsedColumn(),
    )

    def _advance(p, t):
        if p is not None and t is not None:
            p.advance(t)

    return progress, _advance


# ════════════════════════════════════════════════════════════════════════════
# CLI
# ════════════════════════════════════════════════════════════════════════════

def build_parser() -> argparse.ArgumentParser:
    """Construct the command-line argument parser."""
    parser = argparse.ArgumentParser(
        prog="enhance_notes",
        description=(
            "Additive LLM enhancement for existing V6 permanent notes. "
            "Appends new paragraphs, callouts, figures, and questions to "
            "each note without rewriting existing prose."
        ),
        epilog=(
            "Examples:\n"
            "  enhance_notes.py --dry-run --limit 3 -v\n"
            "      Preview enhancement for 3 notes; no files written.\n"
            "  enhance_notes.py --note schema-theory\n"
            "      Enhance the single note matching 'schema-theory'.\n"
            "  enhance_notes.py --max-passes 2\n"
            "      Enhance every note with fewer than 2 prior passes.\n"
            "  enhance_notes.py --limit 20 --output-dir D:/v6-preview\n"
            "      Mirror enhanced notes to a preview dir; originals untouched.\n"
            "  enhance_notes.py --note schema-theory --re-enhance --bypass-cache\n"
            "      Force a fresh live LLM enhancement, ignoring pass cap & cache.\n"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--input-dir", type=Path, default=DEFAULT_INPUT_DIR,
        help=f"Directory of V6 notes to scan (default: {DEFAULT_INPUT_DIR})",
    )
    parser.add_argument(
        "--output-dir", type=Path, default=None,
        help="Mirror enhanced notes here instead of overwriting in place.",
    )
    parser.add_argument(
        "--note", type=str, default=None, metavar="SUBSTR",
        help="Filter notes by filename-stem substring (case-insensitive).",
    )
    parser.add_argument(
        "--limit", type=int, default=None, metavar="N",
        help="Process at most N notes.",
    )
    parser.add_argument(
        "--max-passes", type=int, default=DEFAULT_MAX_PASSES, metavar="N",
        help=(
            f"Skip notes already enhanced N times (default: {DEFAULT_MAX_PASSES}). "
            "Use --re-enhance to override."
        ),
    )
    parser.add_argument(
        "--re-enhance", action="store_true",
        help="Ignore the pass-count gate and enhance regardless.",
    )
    parser.add_argument(
        "--model", type=str, default=DEFAULT_MODEL,
        help=f"Ollama model id (default: {DEFAULT_MODEL}).",
    )
    parser.add_argument(
        "--bypass-cache", action="store_true",
        help="Force live LLM calls; ignore cache.",
    )
    parser.add_argument(
        "-n", "--dry-run", action="store_true",
        help="Run LLM (and cache results) but write no files.",
    )
    parser.add_argument(
        "--strict", action="store_true",
        help="Exit non-zero if any note fails enhancement.",
    )
    parser.add_argument(
        "-v", "--verbose", action="count", default=0,
        help="Increase logging verbosity (repeatable).",
    )
    parser.add_argument(
        "-q", "--quiet", action="store_true",
        help="Suppress non-error output.",
    )
    parser.add_argument(
        "--report-dir", type=Path, default=DEFAULT_REPORT_DIR,
        help=(
            f"Directory for run reports (default: {DEFAULT_REPORT_DIR}). "
            "A timestamped markdown report is written after each non-dry-run "
            "that enhanced at least one note."
        ),
    )
    parser.add_argument(
        "--no-report", action="store_true",
        help="Suppress writing the run report.",
    )
    parser.add_argument(
        "--version", action="version", version=f"%(prog)s {__version__}",
    )
    return parser


def configure_logging(verbosity: int, quiet: bool) -> None:
    """Configure root logger from CLI verbosity flags."""
    if quiet:
        level = logging.ERROR
    elif verbosity >= 2:
        level = logging.DEBUG
    elif verbosity == 1:
        level = logging.INFO
    else:
        level = logging.WARNING
    logging.basicConfig(
        level=level,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )


def _summarize_response(resp: EnhancementResponse | None) -> dict[str, int]:
    """Return per-section addition counts for a single enhancement response."""
    if resp is None:
        return {}
    counts: dict[str, int] = {}
    if resp.extra_explanation_paragraphs:
        counts["Core Explanation paragraphs"] = len(resp.extra_explanation_paragraphs)
    if resp.mechanism_addition:
        counts["Mechanism addition"] = 1
    if resp.extra_implications:
        counts["Practical Implications"] = len(resp.extra_implications)
    if resp.extra_distinctions:
        counts["Key Distinctions"] = len(resp.extra_distinctions)
    if resp.common_misconceptions:
        counts["Common Misconceptions"] = len(resp.common_misconceptions)
    if resp.extra_figures:
        counts["Key Figures"] = len(resp.extra_figures)
    if resp.extra_questions:
        counts["Open Questions"] = len(resp.extra_questions)
    if resp.synthesis_addition:
        counts["Synthesis addition"] = 1
    if resp.evidence_addition:
        counts["Evidence addition"] = 1
    if resp.connection_rationales:
        counts["Connection rationales"] = len(resp.connection_rationales)
    return counts


def write_run_report(
    results: list[EnhancementResult],
    stats: RunStats,
    args: argparse.Namespace,
    *,
    report_dir: Path,
) -> Path:
    """Write a markdown report of an enhancement run.

    The report lists every successfully enhanced note with a per-section
    breakdown of what the LLM added. Useful for reviewing and rolling back.

    Args:
        results: All EnhancementResults from the run.
        stats: Aggregate run statistics.
        args: Parsed CLI args (used for run metadata).
        report_dir: Destination directory; created if missing.

    Returns:
        The path to the written report file.

    Raises:
        OSError: If the report directory or file cannot be written.
    """
    report_dir.mkdir(parents=True, exist_ok=True)
    ts = dt.datetime.now()
    stamp = ts.strftime("%Y-%m-%d_%H%M%S")
    report_path = report_dir / f"enhancement-run-{stamp}.md"

    enhanced = [r for r in results if r.ok]
    cached_only = [r for r in enhanced if r.cached]
    live = [r for r in enhanced if not r.cached]
    failed = [r for r in results if not r.ok]

    lines: list[str] = []
    lines.append("---")
    lines.append(f"title: Enhancement Run — {ts.isoformat(timespec='seconds')}")
    lines.append("type: enhancement-run-report")
    lines.append("tags: [enhancement-report, v6-pipeline]")
    lines.append(f"run-timestamp: '{ts.isoformat(timespec='seconds')}'")
    lines.append(f"model: {args.model}")
    lines.append(f"input-dir: '{args.input_dir}'")
    if args.output_dir:
        lines.append(f"output-dir: '{args.output_dir}'")
    lines.append(f"scanned: {stats.scanned}")
    lines.append(f"enhanced: {stats.enhanced}")
    lines.append(f"cache-hits: {stats.cached}")
    lines.append(f"skipped-empty: {stats.skipped_empty}")
    lines.append(f"failed: {stats.failed}")
    lines.append(f"files-written: {stats.written}")
    lines.append("---")
    lines.append("")
    lines.append(f"# Enhancement Run — {ts.strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **Model:** `{args.model}`")
    lines.append(f"- **Input directory:** `{args.input_dir}`")
    if args.output_dir:
        lines.append(f"- **Output directory:** `{args.output_dir}`")
    else:
        lines.append("- **Output directory:** *(in-place)*")
    lines.append(f"- **Scanned:** {stats.scanned}")
    lines.append(f"- **Enhanced:** {stats.enhanced} "
                 f"(live: {len(live)}, cache-hits: {len(cached_only)})")
    lines.append(f"- **Skipped (empty LLM result):** {stats.skipped_empty}")
    lines.append(f"- **Failed:** {stats.failed}")
    lines.append(f"- **Files written:** {stats.written}")
    lines.append("")

    if enhanced:
        lines.append("## Enhanced Notes")
        lines.append("")
        lines.append("| # | Note | Cache | Additions |")
        lines.append("|---:|------|:-----:|-----------|")
        for i, r in enumerate(enhanced, start=1):
            stem = r.note.path.stem
            counts = _summarize_response(r.response)
            additions = (
                ", ".join(f"{k}: {v}" for k, v in counts.items())
                if counts else "_(no new material)_"
            )
            cache_marker = "✓" if r.cached else " "
            lines.append(f"| {i} | [[{stem}]] | {cache_marker} | {additions} |")
        lines.append("")

        lines.append("## Per-Note Detail")
        lines.append("")
        for r in enhanced:
            stem = r.note.path.stem
            lines.append(f"### [[{stem}]]")
            lines.append("")
            lines.append(f"- **Source path:** `{r.note.path}`")
            if r.written_path:
                lines.append(f"- **Written to:** `{r.written_path}`")
            lines.append(f"- **Cache hit:** {'yes' if r.cached else 'no'}")
            lines.append(f"- **Pass count after run:** "
                         f"{r.note.enhancement_passes + 1}")
            counts = _summarize_response(r.response)
            if counts:
                lines.append("- **Additions:**")
                for k, v in counts.items():
                    lines.append(f"  - {k}: **{v}**")
            else:
                lines.append("- **Additions:** _none — LLM returned an empty response._")
            lines.append("")

    if failed:
        lines.append("## Failed Notes")
        lines.append("")
        for r in failed:
            stem = r.note.path.stem
            lines.append(f"- [[{stem}]] — `{r.error}`")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Generated by `enhance_notes.py` "
                 f"v{__version__}.*")
    lines.append("")

    text = "\n".join(lines)
    tmp = report_path.with_suffix(".md.tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(report_path)
    return report_path


def _print_summary(stats: RunStats, dry_run: bool) -> None:
    title = "DRY-RUN SUMMARY" if dry_run else "ENHANCEMENT SUMMARY"
    bar = "=" * 60
    lines = [
        "",
        bar,
        f"  {title}",
        bar,
        f"  Scanned:                    {stats.scanned}",
        f"  Enhanced:                   {stats.enhanced} (cache-hits: {stats.cached})",
        f"  Skipped (empty LLM result): {stats.skipped_empty}",
        f"  Failed:                     {stats.failed}",
        f"  Files written:              {stats.written}",
        bar,
    ]
    # Robust against Windows cp1252 stdout if any non-ASCII slips in.
    try:
        sys.stdout.write("\n".join(lines) + "\n")
    except UnicodeEncodeError:
        sys.stdout.write(
            ("\n".join(lines) + "\n").encode("ascii", "replace").decode("ascii")
        )


def main(argv: list[str] | None = None) -> int:
    """Main entry point.

    Returns:
        0 success, 1 uncaught, 2 input-dir not found, 4 no notes,
        5 strict + failures, 6 ollama unavailable, 130 interrupted.
    """
    parser = build_parser()
    args = parser.parse_args(argv)
    configure_logging(args.verbose, args.quiet)

    try:
        notes = scan_notes(
            args.input_dir,
            name_filter=args.note,
            max_passes=args.max_passes,
            re_enhance=args.re_enhance,
            limit=args.limit,
        )
    except FileNotFoundError as e:
        logger.error("%s", e)
        return 2

    if not notes:
        logger.error(
            "No notes selected (input=%s, filter=%s, max-passes=%d).",
            args.input_dir, args.note, args.max_passes,
        )
        return 4

    logger.info("Selected %d note(s) for enhancement.", len(notes))

    try:
        with OllamaClient(
            model=args.model,
            cache_dir=config_v3.LLM_CACHE_DIR,
        ) as client:
            try:
                results, stats = enhance_all(
                    notes, client,
                    model=args.model,
                    bypass_cache=args.bypass_cache,
                    dry_run=args.dry_run,
                    output_dir=args.output_dir,
                    input_dir=args.input_dir,
                )
            except OllamaUnavailableError as e:
                logger.error("Ollama unavailable: %s", e)
                return 6
    except OllamaUnavailableError as e:
        logger.error("Ollama unavailable on startup: %s", e)
        return 6
    except KeyboardInterrupt:
        logger.warning("Interrupted by user.")
        return 130

    _print_summary(stats, args.dry_run)

    # Write the run report (skip on dry-run, on --no-report, or if nothing changed).
    if not args.dry_run and not args.no_report and stats.enhanced > 0:
        try:
            report_path = write_run_report(
                results, stats, args, report_dir=args.report_dir,
            )
            logger.info("Run report written: %s", report_path)
        except OSError as e:
            logger.warning("Could not write run report: %s", e)

    if args.strict and stats.failed > 0:
        logger.error("Strict mode: %d failure(s).", stats.failed)
        return 5
    return 0


# ════════════════════════════════════════════════════════════════════════════
# Entry-point guard
# ════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        sys.exit(130)
    except Exception:
        logger.exception("Uncaught exception")
        sys.exit(1)
